### ISSUE TITLE
Create new application in another directory than $GOPATH/src

### ISSUE THREAD

**Issue by phndiaye** [beego/bee#11]
Hi !

When using `bee new [app_name]` with a custom directory, it returns me the following error : 
`Unable to create an application outside of $GOPATH` 
and tells me to create the application in `$GOPATH/src`, which works.

So, i wonder if it's possible to create app in custom directory, since it's not documented in the `bee help` command.

**Comment by jinchizhong** [comment]
Hi friend,

I met the same problem. I use [gvm](https://github.com/moovweb/gvm) to manager go versions and packages in different dirs.
Put project into such a strange dir(/home/jcz/.gvm/pkgsets/go1.3/global/src) is a bad choice...

**Comment by amrfaissal** [comment]
@phndiaye Same as #210. A PR is submitted to fix it.

**Comment by amrfaissal** [comment]
@astaxie Why this issue is still open? I think it's already solved in PR #210

**Comment by RanQiwu** [comment]
> @astaxie Why this issue is still open? I think it's already solved in PR #210

@amrfaissal Do you think your PR solved the problem? This problem still exists today.
