### ISSUE TITLE
Can not set arguments when use bee run

### ISSUE THREAD

**Issue by thanhtranit** [beego/bee#110]
Hi team,
When i used `bee run`, I can not set more arguments. But I use `go run` in same project, it worked.

Example:

```
var runMode = flag.String("runmode", "dev", "run mode dev/prod")

func main() {

    flag.Parse()
    fmt.Println(*runMode)

    if beego.RunMode == "dev" {
        beego.DirectoryIndex = true
        beego.StaticDir["/swagger"] = "swagger"
    }

    beego.Run()
}
```

`bee run appName -runmode=prod` 
It will print `dev`

`go run main.go -runmode=prod`
It will print `prod`

How to set arguments which mode `bee run` and `go run` ?

**Comment by astaxie** [comment]
bee tools is just for develop tools. `bee run` just watch the file and auto build the source code. I think it didn't need to pass the params to the application. why you want to do that? runmode always changed in the config file. 

if you don't want to change it in config, you also can set to ENV, and then read from that.

**Comment by lei-cao** [comment]
Indeed, Bee can achieve that already.
Copy `https://github.com/beego/bee/blob/master/bee.json` to your project path, and add the commands you need.

```
{
	"version": 0,
	"gopm": {
		"enable": false,
		"install": false
	},
	"go_install": false,
	"watch_ext": [],
	"dir_structure": {
		"watch_all": false,
		"controllers": "",
		"models": "",
		"others": []
	},
	"cmd_args": ["-runmode=prod"],
	"envs": [],
	"database": {
		"driver": "mysql"
	}
}
```
