### ISSUE TITLE
bee can not found my GOPATH

### ISSUE THREAD

**Issue by whinette** [beego/bee#111]
While I did not encounter any problems before.
Logs:

> > env
> > GOPATH=/nfs/zfs-student-4/users/2013/mweibel/Dropbox/rendu/goproj
> > pwd 
> > /nfs/zfs-student-4/users/2013/mweibel/Dropbox/rendu/goproj/src
> > bee new hop
> > 2015/05/08 16:31:38 [ERRO] Unable to create an application outside of $GOPATH(/nfs/zfs-student-4/users/2013/mweibel/Dropbox/rendu/goproj)

if I give it myself the GOPATH with the env command it works:

> > env GOPATH=/nfs/zfs-student-4/users/2013/mweibel/Dropbox/rendu/goproj/src bee new framework0
> > [INFO] Creating application...

I'm using zsh with omzsh

**Comment by astaxie** [comment]
use the `go env`, it looks you has some wrong GOPATH in the env. maybe you has two GOPATH and one is a wrong path.

**Comment by whinette** [comment]
go env is exactly the same path. :/

**Comment by astaxie** [comment]
I have no idea on that. but I have encounter it before for the wrong GOPATH.
