### ISSUE TITLE
"bee run" fail with error : [ERRO] Fail to watch directory[no space left on device]

### ISSUE THREAD

**Issue by vmintam** [beego/bee#127]
Dear Guys,

 When I create very basic new project with : bee new newproj 
 then, i goto the newproj dir and run : bee run.
one error display : [ERRO] Fail to watch directory[no space left on device]

I have just checked and saw solution: 
 Need to change value : /proc/sys/fs/inotify/max_user_watches to higher .
as suggest in : https://github.com/howeyc/fsnotify.

 example in my machine : edit /etc/sysctl.conf, add line :
fs.inotify.max_user_watches = 131072 . 

run sysctl -p for update.

now, bee run  is OK.

**Comment by astaxie** [comment]
Good tips

**Comment by amrfaissal** [comment]
@astaxie To be added on README.md.

**Comment by Anteoy** [comment]
Excuse me,it dose not work for me,how can I do anything else?

**Comment by Anteoy** [comment]
I just restart my vscode,it works but I never find the real reason.
