### ISSUE TITLE
bee api -conn=root:@tcp\(127.0.0.1:3306\)/test 生成controller为空

### ISSUE THREAD

**Issue by guaiguaihw** [beego/bee#130]
rt！谢大我按照视频生成mysql连接，可是controller为空，model里面的文件也只有struct，内容不全。这是什么原因呢？？？

**Comment by astaxie** [comment]
controller为空基本上是因为你的数据库没有主键引起的

**Comment by guaiguaihw** [comment]
感谢谢大解惑，已解决！
