### ISSUE TITLE
why can't i not install  bee tool?

### ISSUE THREAD

**Issue by thiennghv** [beego/bee#133]
Go worked smoothly but i try many time go get..../bee and this is my .bashrc "export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/GoApp
export PATH=$PATH:$GOPATH/bin/bee
". But bee not worked! Please help me!

**Comment by astaxie** [comment]
`go get -u github.com/beego/bee`

**Comment by LaurierMantel** [comment]
Need to set export `PATH=$PATH:$GOPATH/bin` not `export PATH=$PATH:$GOPATH/bin/bee`
