### ISSUE TITLE
Error: sql: unknown driver "sqlite"

### ISSUE THREAD

**Issue by VarunBatraIT** [beego/bee#134]
```
Error: sql: unknown driver "sqlite" (forgotten import?)%
```
It works great in app but when I run bee migrate, it gives me this error

```
{
	"version": 0,
		"database": {
			"driver": "sqlite",
			"conn": "sample.sqlite3"
		}
 }
```

I get following error:

```
2015/10/15 15:25:17 [INFO] Using 'sqlite' as 'driver'
2015/10/15 15:25:17 [INFO] Using 'sample.sqlite3' as 'conn'
2015/10/15 15:25:17 [INFO] Running all outstanding migrations
2015/10/15 15:25:17 [ERRO] Could not connect to sqlite: sample.sqlite3
2015/10/15 15:25:17 [ERRO] Error: sql: unknown driver "sqlite" (forgotten import?)%
```

What could be the issue?

**Comment by VarunBatraIT** [comment]
Could it be because sqlite driver isn't included?
I don't see it here:
https://github.com/beego/bee/blob/master/g_appcode.go

**Comment by astaxie** [comment]
now bee migrate only support mysql and postgres

**Comment by VarunBatraIT** [comment]
Lets forget about the migration, can I just create tables in case of sqlite3 when app starts? Just like XORM? I just hope that answer is yes :)
Thanks for the response.
