### ISSUE TITLE
watcher is not watching .tpl inside another folder

### ISSUE THREAD

**Issue by apung** [beego/bee#136]
I have .tpl files inside `templates` folder. So I modify bee.json. But when I change some file, it is not restarting..

Here is my bee.json

```
{
    "version": 0,
    "gopm": {
        "enable": false,
        "install": false
    },
    "go_install": false,
    "watch_ext": [".tpl"],
    "dir_structure": {
        "watch_all": false,
        "controllers": "",
        "models": "",
        "others": ["/Users/apung/Development/Go/src/mysecretproject/templates"]
    },
    "cmd_args": [],
    "envs": [],
    "database": {
        "driver": "mysql"
    }
}
```

here is my stdout to make sure that `templates` folder is added via `bee.json`

```
Apungs-MacBook-Air:mysecretproject apung$ bee run
2015/10/26 19:38:45 [INFO] Uses 'mysecretproject' as 'appname'
2015/10/26 19:38:45 [INFO] Detected bee.json
2015/10/26 19:38:45 [INFO] Initializing watcher...
2015/10/26 19:38:45 [TRAC] Directory(/Users/apung/Development/Go/src/mysecretproject/controllers)
2015/10/26 19:38:45 [TRAC] Directory(/Users/apung/Development/Go/src/mysecretproject)
2015/10/26 19:38:45 [TRAC] Directory(/Users/apung/Development/Go/src/mysecretproject/models)
2015/10/26 19:38:45 [TRAC] Directory(/Users/apung/Development/Go/src/mysecretproject/routers)
2015/10/26 19:38:45 [TRAC] Directory(/Users/apung/Development/Go/src/mysecretproject/tests)
2015/10/26 19:38:45 [TRAC] Directory(/Users/apung/Development/Go/src/mysecretproject/templates)
2015/10/26 19:38:45 [INFO] Start building...
2015/10/26 19:38:49 [SUCC] Build was successful
```

oh yes, I fall in :sparkling_heart: with ![beego](http://i.imgur.com/YtX9vEH.png) beego

**Comment by astaxie** [comment]
as template is .tpl. while bee only support .go files

**Comment by apung** [comment]
I am thinking now, about the purpose of `watch_ext`

**Comment by guillaumenel** [comment]
Can we put in documentation description of bee.json, please:

To run custom configuration options, you can create bee.json in your project root (from the same path as you would run `bee`). 
This allows you to configure, i.e. additional watches. To watch all ".tpl" files in specific folders, you can modify bee.json like this:
```

{
	"version": 0,
	"gopm": {
		"enable": false,
		"install": false
	},
	"go_install": false,
	"watch_ext": ["tpl"],
	"dir_structure": {
		"watch_all": false,
		"controllers": "",
		"models": "",
		"others": ["views/home/","views/layouts"]
	},
	"cmd_args": [],
	"envs": [],
	"database": {
		"driver": "mysql"
	}
}

```
In this modifcation we've added **".tpl"** to the watch_ext array and added additional folders to dir_structure.others array: **"others": ["views/home/","views/layouts"]**

For an example of the bee.json configuration file, reference the package:
https://github.com/beego/bee/blob/master/bee.json

**Comment by sergeylanzman** [comment]
Today bee support live reload with websocket and watch to html,tpl,js,css files.
