### ISSUE TITLE
[Proposal] generate postgres migration

### ISSUE THREAD

**Issue by WnP** [beego/bee#138]
`bee generate migration` command looks been designed for MySQL and not for Postgresql

Implementing such a feature for postgres looks not that difficult, all modifications must be applied [on this part of the code](https://github.com/beego/bee/blob/e2ee2a8a79ae22f23758d8fc19449a7ae95d3a4b/g_scaffold.go#L44-L101)

By the way imho, some questions must be solved before
## `Not Null` rule(s)

When looking [getSqlType](https://github.com/beego/bee/blob/e2ee2a8a79ae22f23758d8fc19449a7ae95d3a4b/g_scaffold.go#L72-L101) function. it looks like that all fields are defined `NOT NULL`

**except** for `int*` and `uint*` which are defined `DEFAULT NULL` [see here](https://github.com/beego/bee/blob/e2ee2a8a79ae22f23758d8fc19449a7ae95d3a4b/g_scaffold.go#L89-L92)

imho, a better approach is to set all fields to `NOT NULL` by default, or even better using a flag like `!` to determine which fields are nullable are which are not, eg.

```
foo:int,bar:!int
```

where -for example- `foo` is nullable and `bar` is not nullable
## Getting fields definitions from beego ORM

What do you think about taking fields definition directly from beego ORM?
- for MySQL using [mysqlTypes](https://github.com/astaxie/beego/blob/a89f14d80dab442927bdc11d641aa1250ab8ad71/orm/db_mysql.go#L42-L60)
- for PostgreSQL using [postgresTypes](https://github.com/astaxie/beego/blob/a89f14d80dab442927bdc11d641aa1250ab8ad71/orm/db_postgres.go#L41-L59)

it's just a`map[string]string` so it's realy easy to find which one match or not, no `switch` statement required

Indeed to do that we need to make `mysqlTypes` and `postgresTypes` exportable

---

Let me know your thoughts

**Comment by WnP** [comment]
1) `not null` policy is explained [in the documentation](http://beego.me/docs/mvc/model/models.md#null)
2) mysqlTypes and postgresTypes are not adapted for this kind of operations, better manage migration using [beego.orm.commander](https://github.com/astaxie/beego/blob/master/orm/cmd.go) `sqlall` command

**Comment by sergeylanzman** [comment]
Postgresql support rewrite inhttps://github.com/beego/bee/pull/222 . If this still relevant, please reopen issue.
