### ISSUE TITLE
bee new 与 run 应该在任何路径使用

### ISSUE THREAD

**Issue by me308209600** [beego/bee#14]
我用windows系统,切换路径太麻烦.我希望BEE可以和REVEL一样在任何路径使用new,run命令,这样多方便.代码放在$GOPATH\src我不反对.但是我在其他路径就不能使用bee命令了,这个我认为应该改进.

**Comment by tqyq** [comment]
Rules are made to be broken.
I think "bee run" should be used as a common tool for other go apps.

**Comment by astaxie** [comment]
no, bee will not to support other go apps. it's only designed for beego
