### ISSUE TITLE
bee pack do not work when the project use godep.

### ISSUE THREAD

**Issue by yanyiwu** [beego/bee#143]
Because godep will rewrite main.go from 

```
import (
"github.com/astaxie/beego"
)
```

```
import (
"xxx.com/yyy/Godeps/_workspace/src/github.com/astaxie/beego"
)
```

**Comment by yanyiwu** [comment]
I fix this bug in https://github.com/beego/bee/pull/144

**Comment by astaxie** [comment]
I think you need to make sure the godep inside your GOPATH. 

GOPATH := $(CURDIR)/Godeps/_workspace:$(GOPATH)
