### ISSUE TITLE
Support bee run with build tags

### ISSUE THREAD

**Issue by mmindenhall** [beego/bee#149]
I'm building an application that has multiple profiles (e.g., small, medium, large).  Each profile adds additional features, which includes additional REST APIs.  To build the application for each profile, we're using go build tags (also called build constraints).

I'd like a `-tags` param added to `bee run`, which will just be passed through to the build phase.

For example, to build my executable for the small profile, I use:
```
$ go build -tags profile_small
```

To run with bee, I'd like to use:

```
$ bee run -tags profile_small
```

**Comment by ConnorDoyle** [comment]
+1

**Comment by mmindenhall** [comment]
Hi @ConnorDoyle, that support was added in PR #173.
