### ISSUE TITLE
mac 在安装Bee的时候提示出错

### ISSUE THREAD

**Issue by aprilsky** [beego/bee#15]
beego 可以正常安装的，但Bee 工具安装的时候 必须 sudo .
但即使sudo ，却提示 没有设置“GOPATH”
[apple@pc-201009121709 bee]$echo $GOPATH
/Users/apple/work/gopath
[apple@pc-201009121709 bee]$sudo go get github.com/beego/bee
package github.com/beego/bee: cannot download, $GOPATH not set. For more details see: go help gopath
[apple@pc-201009121709 bee]$

**Comment by cow11023** [comment]
zhangyiran@zhangyirandeMacBook-Pro src % go install github.com/beego/beego/v2@latest
package github.com/beego/beego/v2 is not a main package
