### ISSUE TITLE
'bee test ...' should accept 'go test' flags and pass them through

### ISSUE THREAD

**Issue by ccll** [beego/bee#16]
I'm integrating 'bee' workflow into tools like 'gulp' or 'grunt', and it almost work, except 'bee test...' just run 'go test' without any arguments, while I have some basic needs:
1. run 'go test' in verbose mode (with '-v' flag)
2. run 'go test' on all sub-packages (with 'go test ./...')

As long as these are specific needs, I think a better and more general approach is to have 'bee test' pass extra flags directly to 'go test', then 'bee test app -v ./...' invokes 'go test -v ./...'.
Another approach is to add an extra field in 'bee.json'. But in a automated workflow, command line arguments are far more friendly than configuration files. So a command line based solution is better.

How do you think about this?
If this approach is acceptable, I'll implement it and send a pull request.

**Comment by sergeylanzman** [comment]
You can create this command with ```bee rs```. From 1.8.1 bee support custom command. Set in Beefile your test command.
