### ISSUE TITLE
Documentation generations can't undestand custom non struct types

### ISSUE THREAD

**Issue by KilledKenny** [beego/bee#170]
I recently realized that bee only supports structs and builtin data types.

Eample:

``` go
type FailType string
type Broken struct {
    F FailType
}
```

Bee is going trow the error `can't find the object: models.FailType`

Bee should probably understand sutch a simple data structures or at least not do a os.Exit when it comes across a it.

**Comment by sergeylanzman** [comment]
Please check again. bee generate docs rewrite with swagger 2.0. If this still relevant, please reopen issue
