### ISSUE TITLE
how to build my own bee?

### ISSUE THREAD

**Issue by goldalworming** [beego/bee#177]
I need to change api template with my condition

go build /home/lmvm/go/src/github.com/beego/bee/bee.go
# command-line-arguments
../beego/bee/bee.go:76: undefined: cmdNew
../beego/bee/bee.go:77: undefined: cmdRun
../beego/bee/bee.go:78: undefined: cmdPack
../beego/bee/bee.go:79: undefined: cmdApiapp
../beego/bee/bee.go:80: undefined: cmdHproseapp
../beego/bee/bee.go:83: undefined: cmdBale
../beego/bee/bee.go:84: undefined: cmdVersion
../beego/bee/bee.go:85: undefined: cmdGenerate
../beego/bee/bee.go:87: undefined: cmdMigrate
../beego/bee/bee.go:88: undefined: cmdFix
../beego/bee/bee.go:88: too many errors

how to build it for myself?

**Comment by youngsterxyf** [comment]
@goldalworming `go build github.com/beego/bee`

**Comment by goldalworming** [comment]
it works, but my template not work :(
