### ISSUE TITLE
bee run -> recompile -> can't replace running.exe on mapped network drive

### ISSUE THREAD

**Issue by ITSecMedia** [beego/bee#185]
The bee tool doesn't kill the running executable and therefore can't replace the running beego project app executable after recompiling the new changes if you work on a mapped network drive in Windows 10.

You have to kill the process-tree and restart, it worked flawlessly on a regular drive, the issue seems related to a mapped network drive / NAS

Can anyone verify this please, as it happens here.

Error shown:

2016/03/22 14:42:39 [INFO] Start building...
go install xxx/myapp: open myapp.exe: The process cannot access the file because it is being used by another process.
2016/03/22 14:42:43 [ERRO] ============== Build failed ===================

Only bee tool has acess to it, easy to see in processexplorer process-tree.

**Comment by steamonimo** [comment]
Perhaps the new Windows file caching treates the shared executable as an addition to the cache. Thus the executable will become part of the Windows Paging. As such it can not be replaced. We have seen similar problems with executables we wanted to update in Windows shares. Our approach worked till the latest W10 kernels arrived. From then the replacment process became much more complicated. In my impression the file becomes part of the Windows Paging/Caching with the first use via network. But perhaps Windows is starting the Paging/Caching proactively now?

**Comment by ITSecMedia** [comment]
Thanks for your time to reply.
Honestly have no idea for the reason but I found another solution for my problem. I appreciate!

**Comment by sergeylanzman** [comment]
If this still relevant, please reopen issue
