### ISSUE TITLE
bee 1.4.1 does not identify changes in API annotations

### ISSUE THREAD

**Issue by steamonimo** [beego/bee#186]
// @Title create
// @Description create object
// @Param   body        body    models.Object   true        "The object content"
// @Success 200 {string} models.Object.Id
// @Failure 403 body is empty
// @router /:apikey(.+)/:id(.+)/xy [get]

After changes to @router beego does not identify that the interface has been changed. Thus the call will not succeed.

How can I force beego to recreate all the interfaces defined in the @router annotations?

**Comment by astaxie** [comment]
@sacheendra remove the `lastupdate.tmp` in the project

**Comment by kishanpatel** [comment]
@steamonimo I think that was for you.

**Comment by steamonimo** [comment]
@sacheendra I deleted lastupdate.tmp to provoke the recreation of commentsRouter... but this does not work. Currently I have to maintain commentsRouter... manually to keep it in sync.

**Comment by sergeylanzman** [comment]
Please check again. bee generate docs + routes rewrite with swagger 2.0. If this still relevant, please reopen issue
