### ISSUE TITLE
Show Go version not accuracy when bee run

### ISSUE THREAD

**Issue by ysqi** [beego/bee#192]
My PC is  64bit win10 ,  Change env in cmd:

``` bat
set GOARCH=386
set CGO_ENABLED=1
```

Got info after run bee : 

``` bat
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 windows/amd64
```

Should be show Go version `go1.6 windows/386` then not `go 1.6 windows/amd64` .
Go version info should be show from Go env item `GOARCH` , like this:

``` bash
> go env
set GOARCH=386
set GOBIN=C:\go\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows 
set GORACE=
set GOROOT=c:\go
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

**Comment by amrfaissal** [comment]
I don't think this is an issue. `bee version` prints the Go version as reported by `runtime.Version`. Changing `GOARCH ` or `GOOS ` variables won't affect that.

**Comment by amrfaissal** [comment]
Already fixed.
