### ISSUE TITLE
bee pack command how to add the compiler parameters？bee pack命令如何加入编译参数？

### ISSUE THREAD

**Issue by luo12yan** [beego/bee#195]
I want to join -ldflags "-s -w" parameter when packaged to reduce the size of the resulting program.

I do not know how to add bee pack should compile parameters?

=====================================
我要在打包的时候加入 -ldflags “-s -w”参数以减少最终生成程序的大小。
不知道bee pack应当如何加入编译参数？

**Comment by amrfaissal** [comment]
@luo12yan Use `-ba` option to pass additional args to `go build`:
```shell
// go version <= 1.6
 $ bee pack -ba "-ldflags '-s'"

// go version >= 1.7
 $ bee pack -ba "-ldflags '-s -w'"
````
