### ISSUE TITLE
Scaffold for Model generation and DB Migration

### ISSUE THREAD

**Issue by sivakumar07** [beego/bee#199]
Beego tools have any scaffold command for Model generation and DB Migration like rails? That will be helpful to maintain the DB schema inside the app.

**Comment by u007** [comment]
https://github.com/beego/bee

**Comment by kumarsiva07** [comment]
Its good. But I cannot create tables. Can only add columns using migrate command. How do i add constraints like FK, Index? How do i create new tables?

**Comment by sergeylanzman** [comment]
`bee generate model` or app create tables. Each model with table.
