### ISSUE TITLE
Can't generate application code outside of GOPATH

### ISSUE THREAD

**Issue by u007** [beego/bee#201]
i'am facing a this issue on the directory i'am having a working beego project.
bee generate scaffold user -fields="id:int64,firstname:string,lastname:string,gender:string,dob:string,email:string" -driver="mysql"

returns:
2016/05/04 00:34:07 [INFO] Detected bee.json
2016/05/04 00:34:07 [INFO] Using 'user' as scaffold name
2016/05/04 00:34:07 [INFO] Do you want me to create a user model? [yes|no]]  yes
2016/05/04 00:34:09 [INFO] Using 'User' as model name
2016/05/04 00:34:09 [INFO] Using 'models' as package name
2016/05/04 00:34:09 [ERRO] Could not create model file: open /Users/james/www/gowork/src/auto/models/user.go: file exists
Jamess-iMac-i5: auto james$ bee generate scaffold user -fields="id:int64,firstname:string,lastname:string,gender:string,dob:string,email:string,mobile_no:string,jobtitle:string" -driver="mysql"
2016/05/04 00:34:43 [INFO] Detected bee.json
2016/05/04 00:34:43 [INFO] Using 'user' as scaffold name
2016/05/04 00:34:43 [INFO] Do you want me to create a user model? [yes|no]]  yes
2016/05/04 00:34:44 [INFO] Using 'User' as model name
2016/05/04 00:34:44 [INFO] Using 'models' as package name
2016/05/04 00:34:44 [INFO] model file generated: /Users/james/www/gowork/src/auto/models/user.go
2016/05/04 00:34:44 [INFO] Do you want me to create a user controller? [yes|no]]  yes
2016/05/04 00:34:47 [INFO] Using 'User' as controller name
2016/05/04 00:34:47 [INFO] Using 'controllers' as package name
2016/05/04 00:34:47 [INFO] Using matching model 'User'
2016/05/04 00:34:47 [ERRO] Can't generate application code outside of GOPATH '/Users/james/www/gowork'
Jamess-iMac-i5: auto james$ pwd
/Users/james/www/gowork/src/auto
Jamess-iMac-i5: auto james$ export | grep GOPATH
declare -x GOPATH="/Users/james/www/gowork"

**Comment by u007** [comment]
also happen with
bee generate controller user

**Comment by astaxie** [comment]
yea, not allowed

**Comment by u007** [comment]
hi Astaxie, glad to see your reply :)
please look at the path:
declare -x GOPATH="/Users/james/www/gowork"
Can't generate application code outside of GOPATH '/Users/james/www/gowork'

isn't this the same path?

**Comment by astaxie** [comment]
@u007 could you post your `go env`

**Comment by u007** [comment]
Hi astaxie, here you go :)

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/james/www/gowork"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="/usr/bin/gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by amrfaissal** [comment]
@u007 @astaxie This issue should be closed (fix in PR above).

**Comment by RanQiwu** [comment]
> yea, not allowed

Why this restriction? I think it's a natural requirement to create projects outside of GOPATH.

**Comment by amrfaissal** [comment]
@RanQiwu I agree. The issue is a bit old and the current version of `bee` does not support Go Modules yet.
