### ISSUE TITLE
bee pack does NOT compile the latest code

### ISSUE THREAD

**Issue by GeorgeValentin** [beego/bee#203]
Sometimes use bee pack to deploy web app, it does **NOT** compile the latest code.
Only when  run command `bee run` and  `bee pack`, it finally  compile the latest code.
Is that a bug?
I suggest you guys add `bee clean` command if necessary.

**Comment by GeorgeValentin** [comment]
maybe it's because i do NOT upload the `routers/commentsRouter_xxoo_controllers.go`

**Comment by amrfaissal** [comment]
@GeorgeValentin Is this still an issue?
