### ISSUE TITLE
Swagger UI Not Properly Generated By Bee

### ISSUE THREAD

**Issue by verrol** [beego/bee#204]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

3. What did you do?
a. generate an 'api' application using 'bee api'
b. run application and generate docs:
  $ bee run -downdoc=true -gendoc=true
c. try accessing swagger UI, navigate to 'http://localhost:8080/swagger/swagger-1#'

4. What did you expect to see?
Testable swagger API of my RESTful endpoints

5. What did you see instead?
see attached screenshot
![screen shot 2016-05-08 at 10 05 08 am](https://cloud.githubusercontent.com/assets/1181207/15098189/6340493a-1504-11e6-8148-810da5707979.png)

**Comment by fungl164** [comment]
+1

**Comment by astaxie** [comment]
please upgrade to latest bee. support swagger2.0 now
