### ISSUE TITLE
non-standard import "github.com/astaxie/beego" in standard package "beetest/controllers"

### ISSUE THREAD

**Issue by haterbj** [beego/bee#205]
RUN MAIN.GO

package main

import (
	_ "beetest/routers"

	"github.com/astaxie/beego"
)

func main() {
	beego.Run()
}

d:\go\src\beetest\controllers\default.go:4:2: non-standard import "github.com/astaxie/beego" in standard package "beetest/controllers"
d:\go\src\beetest\routers\router.go:5:2: non-standard import "github.com/astaxie/beego" in standard package "beetest/routers"

THX

**Comment by qianguozheng** [comment]
how to fix it ? 
I have `go get github.com/astaxie/beego/cache` but it still show me:
```
/usr/local/go/src/goERP/utils/cache.go:10:2: non-standard import "github.com/astaxie/beego/cache" in standard package "goERP/utils"
```
