### ISSUE TITLE
自动路由

### ISSUE THREAD

**Issue by uniqueque** [beego/bee#209]
自动路由少过滤了这些controller自身方法，版本差异问题？
exceptMethod := []string{"GetInt8", "GetInt16", "GetInt32", "GetInt64", "GetFiles",
		"XSRFToken", "CheckXSRFCookie", "XSRFFormHTML", "HandlerFunc", "Mapping", "URLMapping", "renderTemplate", "URLFor"}

自动路由无法自定义请求方法，我目前是将注解路由的部分功能加到自动路由里，能自定义路劲，请求方式，再加上restful

**Comment by astaxie** [comment]
please follow the issue template
