### ISSUE TITLE
bee run from different folder

### ISSUE THREAD

**Issue by berk-can** [beego/bee#219]
I want to run a bee project from my home folder without using cd to enter folder but 'bee run projectName' doesnt work, I can't enter path, what should I do (I don't know if it is a issue)

**Comment by amrfaissal** [comment]
@berk-can The ability to run a Beego application from a different folder is implemented. Can you give it a try? Otherwise can you close the issue? /cc @astaxie

**Comment by berk-can** [comment]
do you mean --main:PATH sadly it doesnt work

**Comment by amrfaissal** [comment]
Did you install `bee` from the develop branch? Normally from anywhere you can do:
````shell
$ bee run my-app
# OR
$ bee run github.com/username/my-app
````
It will lookup `my-app` in your `GOPATH` and run it.

**Comment by berk-can** [comment]
ok that's done it, thank you so much
