### ISSUE TITLE
orm problem

### ISSUE THREAD

**Issue by cddaiwei** [beego/bee#228]
I have a problem with beego orm 

I defined the following table

//table group  defined
type Group struct {
    Id                        int
    Name                  string // name for group 
    Creater                _User   `orm:"rel(fk);column(creater)"` //create for group 
    MemberUserList   []_User `orm:"rel(m2m);rel_table(group_member)"` //group member list
    AdminList             []*User `orm:"rel(m2m);rel_table(group_admin)"`  //group admin list
}

//table user defined
type User struct {
    Id                         int
    Name                    string // name for user
    GroupCreateList    []_Group `orm:"reverse(many)"` //create list 
    GroupMemberList []_Group `orm:"reverse(many);rel_table(group_member)"` //member list
    GroupAdminList    []*Group `orm:"reverse(many);rel_table(group_admin)"`  //admin list
}

following codes（1）
    o := orm.NewOrm()
    user := User{}
    o.QueryTable("user").Filter("id", 1).One(&user)
    o.LoadRelated(&user, "GroupMemberList") 
   o.LoadRelated(&user, "GroupAdminList")
can  execute success

but following codes（2）
    o := orm.NewOrm()
       group := Group{}
       o.QueryTable("group").Filter("id", 1).One(&group)

```
    o.LoadRelated(&group, "MemberUserList")  //here report panic: runtime error: invalid memory                                         //address or nil pointer dereference
o.LoadRelated(&user, "AdminList")
```

I want to know why

**Comment by sergeylanzman** [comment]
If this still relevant, please open issue in https://github.com/astaxie/beego
