### ISSUE TITLE
using 'bee run' and show error:fork/exec /usr/local/bin/go: exec format error

### ISSUE THREAD

**Issue by xumeng** [beego/bee#237]
Cannot using 'bee run', and it show error as below.
**/src/quickstart git:(master) ✗>bee run
bee :1.4.1
beego :1.6.1
fork/exec /usr/local/bin/go: exec format error**

Software version:
**bee :1.4.1
beego :1.6.1
go version go1.5.2 darwin/amd64**

**Comment by astaxie** [comment]
Could you post the output from `go env`

**Comment by xumeng** [comment]
>go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/amon/Desktop/workspace/golang:/Users/amon/Desktop/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by astaxie** [comment]
I have no idea on this issue

**Comment by sergeylanzman** [comment]
If this still relevant, please reopen issue
