### ISSUE TITLE
API doc dosn't escape the "`" character

### ISSUE THREAD

**Issue by tnextday** [beego/bee#238]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?
bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

`bee generate docs`  need  escape  string  when the API doc contains the ` character

**Comment by astaxie** [comment]
@tnextday could you provider an example for the issue?

**Comment by tnextday** [comment]
```
// @APIVersion 1.0.0
// @Title beego Test `API
// @Description beego has a very cool tools to autogenerate documents for your API
// @Contact astaxie@gmail.com
// @TermsOfServiceUrl http://beego.me/
// @License Apache 2.0
// @LicenseUrl http://www.apache.org/licenses/LICENSE-2.0.html
package routers

import (
	"demo/controllers"

	"github.com/astaxie/beego"
)

func init() {
	ns := beego.NewNamespace("/v1",
		beego.NSNamespace("/object",
			beego.NSInclude(
				&controllers.ObjectController{},
			),
		),
		beego.NSNamespace("/user",
			beego.NSInclude(
				&controllers.UserController{},
			),
		),
	)
	beego.AddNamespace(ns)
}
```


> // @Title beego Test `API

在 title 里面包含一个反引号，但是`bee generate docs` 生成的代码并没有进行处理，导致代码错误

这个在 api 文档比较小的时候还好找，如果包含两个反引号，生成的字符串代码还在一行，非常难确定问题所在
