### ISSUE TITLE
Bee does not detect a Beego project

### ISSUE THREAD

**Issue by deluan** [beego/bee#247]
I have a private Beego project, and have been using the `bee run` command version 1.4.1. 

Today I upgraded `bee` to 1.5 and it stopped working with my project. I don't have a standard project struct, which is most probably causing the issue. 

Is there a reason why `bee run` has to check for a Beego project? I've been using it with some non-Beego projects and it used to work like a charm, before the upgrade.

**Comment by deluan** [comment]
I found the cause of the problem: I deploy my project to Heroku, and as I have multiple "main" packages, one for each command to be compiled. I follow their suggestion of placing each command in a subfolder under `/cmd` directory. So I have:

* /cmd/web/web.go
* /cmd/seed/seed.go

This layout does not work with `bee run` command, even when I specify the -main parameter. When I move the web.go file to the root of my project it works!

Is there any changes to how I should invoke the `bee run` command? I cannot find a way to run my app with it using my current layout.

Thanks

**Comment by amrfaissal** [comment]
@deluan What do you mean by:
> I have multiple "main" packages

Each cmd(web, seed) contains a separate `func main()`?

**Comment by deluan** [comment]
Exactly, as explained in this blog post:
https://medium.com/@benbjohnson/structuring-applications-in-go-3b04be4ff091#.prt0nemu1

**Comment by amrfaissal** [comment]
AFAIK, `bee run` makes use of `isBeegoProject(path)` function that checks whether there is a `*.go` file in the root folder with a `func main()` or not. So the "cmd" structure described in the link above won't work.

I am not sure if the "cmd" structure makes sense in the context of a Beego web application which produces a single binary.

Maybe @astaxie has a different opinion.

**Comment by deluan** [comment]
Yes, looking at `bee run` code, looks like that's what is happening. 

At first I was baffled by this [Heroku recommendation](https://devcenter.heroku.com/articles/deploying-go#the-procfile), but it makes sense in a Cloud context. In my exemple, `seed` is a scheduled job that runs every day. It is triggered by an external Scheduler, so it needs to be an executable command on its own.

So in this situation, I thought that I should use the `--main` parameter, right? But it does not work, and gives me the same behavior.

**Comment by astaxie** [comment]
@deluan I will try to fix it soon for non beego project

**Comment by deluan** [comment]
Thanks @astaxie. Meanwhile, a quick fix for me was to move my `web.go` file to the root of the project, and leave the `seed.go` in the `cmd` structure. That way it works locally with `bee run`, and also works in Heroku.

**Comment by amrfaissal** [comment]
@astaxie I've raised a PR that fixes this. @deluan You can now use the `-main` option to specify the main file to run the application from.
