### ISSUE TITLE
bee produced executable not the same with go install?

### ISSUE THREAD

**Issue by newyangyang** [beego/bee#254]
To my knowledge, when I use `bee projectName` , bee called `go install` to make a executable. But the executable file made with `go install` directly is slightly smaller in size. How come? bee add extra info to the executable?

**Comment by sergeylanzman** [comment]
Not, bee run go install and go build 
https://github.com/beego/bee/blob/932f16ba4e0d685df00ab03efa8288673db34014/watch.go#L142
