### ISSUE TITLE
bee generate appcode 的bug

### ISSUE THREAD

**Issue by szyhf** [beego/bee#256]
If use symlink to define GOPATH, bee generate won't work .

Example:

``` shell
ln -s /mnt/go/ /go/
export GOPATH=/go

cd /go/src
bee api hello_api
cd /go/src/hello_api
bee generate appcode -driver=mysql -level=1 -conn='xxx@xxx'
> [ERRO] Can't generate application code outside of GOPATH '/go'
```

In g_appcode.go(line 985), using function EvalSymlinks, and got wg = "/mnt/go", but curpath = "/go/src/hello_api" now, that causing the bug.

When using "bee" tool in GOPATH but echo "code is outside of GOPATH"

**Comment by szyhf** [comment]
#257 I add a pull request to fix it but I'm not sure if it is suitable.

**Comment by sergeylanzman** [comment]
If this still relevant, please reopen issue.
