### ISSUE TITLE
Undefined Swagger and beego variables while running bee run

### ISSUE THREAD

**Issue by jjamaral** [beego/bee#262]
Hi!

bee   :1.4.1
beego :1.6.1
Go    :go version go1.6.2 linux/amd64

While running bee API app on production, I have this error:
```
2016/08/26 07:01:11 [SUCC] Docs successfully generated!
2016/08/26 07:01:11 ============== generate docs ===================
# quoteservice/docs
docs/docs.go:17: undefined: swagger.ResourceListing
docs/docs.go:18: undefined: swagger.APIDeclaration
docs/docs.go:30: undefined: beego.GlobalDocAPI
docs/docs.go:37: undefined: beego.GlobalDocAPI
2016/08/26 07:01:11 [ERRO] ============== Build failed ===================
```

I've already tried running go get -u github.com/beego/bee but still have the same error.

Any help please?

Thanks in advance!

**Comment by astaxie** [comment]
if you run the `go get -u`, it should be bee 1.5.0. And then you need to remove the docs folder

**Comment by jjamaral** [comment]
Thank you @astaxie, it works!
