### ISSUE TITLE
windows 10 bee new 创建的项目import路径错误

### ISSUE THREAD

**Issue by CodyGuo** [beego/bee#270]
windows 10

package main

main.go
router.go
default_test.go
import (
	_ "github.com\beego\test/routers"
	"github.com/astaxie/beego"
)

**Comment by amrfaissal** [comment]
@CodyGuo Are you using `bee` inside a terminal emulator? Can you reproduce this issue in Windows command-line?

**Comment by CodyGuo** [comment]
1、go env
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=G:\gopath
set GORACE=
set GOROOT=D:\go
set GOTOOLDIR=D:\go\pkg\tool\windows_386
set CC=gcc
set GOGCCFLAGS=-m32 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\CodyGuo\AppData\Local\Temp\go-build721172330=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
2、system
windows 10

今天突然心情好就学习下beego，刚用bee就发现这个问题了。
全新代码编译的bee工具

**Comment by amrfaissal** [comment]
@astaxie I got this issue when I used a Terminal emulator on Windows, but works fine on the Windows Command-Line. Can you check?

**Comment by CodyGuo** [comment]
我的电脑上装有go，有gopath，在G:\gopath\src\github.com 这样的目录下创建就会有这个问题。在G:\gopath\src下创建就没这个问题

**Comment by ucote** [comment]
我也遇到了这个问题，解决方法是手动把import路径替换掉。我认为是有必要进行修复的，因为我喜欢根据工作类型的不同，对解决方案进行分类。
