### ISSUE TITLE
bee generate docs issue.

### ISSUE THREAD

**Issue by leochan007** [beego/bee#272]
after generation, i get new swagger folder ,but can't access to it via 127.0.0.1:8080/docs

**Comment by astaxie** [comment]
should access 127.0.0.1:8080/swagger

**Comment by leochan007** [comment]
i try it but still some res can't be found.

[beego] 2016/09/07 - 09:34:25 | 404 |           0s| nomatch|  GET     /favicon.ico
[beego] 2016/09/07 - 09:34:27 | 200 |     1.0018ms|   match|  GET     /swagger
[beego] 2016/09/07 - 09:34:27 | 404 |           0s| nomatch|  GET     /css/typography.css
[beego] 2016/09/07 - 09:34:27 | 404 |      998.3µs| nomatch|  GET     /css/reset.css
[beego] 2016/09/07 - 09:34:27 | 404 |           0s| nomatch|  GET     /css/screen.css
[beego] 2016/09/07 - 09:34:27 | 404 |           0s| nomatch|  GET     /css/print.css
[beego] 2016/09/07 - 09:34:27 | 404 |           0s| nomatch|  GET     /lib/object-assign-pollyfill.js
[beego] 2016/09/07 - 09:34:27 | 404 |           0s| nomatch|  GET     /lib/jquery-1.8.0.min.js
[beego] 2016/09/07 - 09:34:27 | 404 |           0s| nomatch|  GET     /lib/jquery.slideto.min.js
[beego] 2016/09/07 - 09:34:27 | 404 |     1.0005ms| nomatch|  GET     /lib/jquery.wiggle.min.js
[beego] 2016/09/07 - 09:34:27 | 404 |           0s| nomatch|  GET     /lib/jquery.ba-bbq.min.js
[beego] 2016/09/07 - 09:34:27 | 404 |      1.013ms| nomatch|  GET     /lib/handlebars-4.0.5.js
[beego] 2016/09/07 - 09:34:27 | 404 |      500.7µs| nomatch|  GET     /lib/lodash.min.js
[beego] 2016/09/07 - 09:34:27 | 404 |           0s| nomatch|  GET     /lib/backbone-min.js
[beego] 2016/09/07 - 09:34:27 | 404 |           0s| nomatch|  GET     /swagger-ui.js
[beego] 2016/09/07 - 09:34:28 | 404 |           0s| nomatch|  GET     /lib/highlight.9.1.0.pack.js
[beego] 2016/09/07 - 09:34:28 | 404 |           0s| nomatch|  GET     /lib/highlight.9.1.0.pack_extended.js
[beego] 2016/09/07 - 09:34:28 | 404 |      500.2µs| nomatch|  GET     /lib/jsoneditor.min.js
[beego] 2016/09/07 - 09:34:28 | 404 |      500.7µs| nomatch|  GET     /lib/marked.js
[beego] 2016/09/07 - 09:34:28 | 404 |           0s| nomatch|  GET     /lib/swagger-oauth.js
[beego] 2016/09/07 - 09:34:28 | 404 |           0s| nomatch|  GET     /images/logo_small.png
[beego] 2016/09/07 - 09:34:28 | 404 |           0s| nomatch|  GET     /images/favicon-32x32.png
[beego] 2016/09/07 - 09:34:28 | 404 |           0s| nomatch|  GET     /images/favicon-32x32.png
[beego] 2016/09/07 - 09:34:28 | 404 |           0s| nomatch|  GET     /images/favicon-16x16.png

**Comment by astaxie** [comment]
`127.0.0.1:8080/swagger/`

**Comment by leochan007** [comment]
go   get it . it works. but why need a '/' more?

**Comment by astaxie** [comment]
> it works. but why need a '/' more

As in the swagger/index.html all the url are relative. So it you not add `/`, it will access the the root url
