### ISSUE TITLE
SecurityDefinitions on swagger specs

### ISSUE THREAD

**Issue by Seraf** [beego/bee#273]
Hello,

I didn't find a way to add a SecurityDefinitions in the swagger.json generated by Bee.

It's defined in the struct in github.com/astaxie/beego/swagger/ but not used by the doc generation.

Is it possible to add by default this block ?  : 

``` json
 "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    }
```

The ideal thing should be able to specify the block somewhere to customize it, but at least providing the default api_key that has always been used by swagger should be a good thing.

Thanks

**Comment by astaxie** [comment]
@Seraf good suggestion. I will try to add into the router.go. As this is the global config. 

```
// @APIVersion 1.0.0
// @Title beego Test API
// @Description beego has a very cool tools to autogenerate documents for your API
// @Contact astaxie@gmail.com
// @TermsOfServiceUrl http://beego.me/
// @License Apache 2.0
// @LicenseUrl http://www.apache.org/licenses/LICENSE-2.0.html
```

**Comment by Seraf** [comment]
Thanks, that would be awesome !

**Comment by sergeylanzman** [comment]
@astaxie I can make this? 
```
// @securityDefinitions name                   type       flow            tokenUrl                       description

// @securityDefinitions Client_Authentication oauth2 application https://api.demo.com/oauth/token  OAuth 2.0 - Application Only Credentials

// @securityDefinitions Client_Authentication1 oauth2 application https://api.demo.com/oauth/token  OAuth 2.0 - Application Only Credentials


//  @scopes:  scope_name1  description
//  @scopes:  scope_name2  description
//  @scopes:  scope_name3  description
//  @scopes:  scope_name4  description
```

**Comment by astaxie** [comment]
@sergeylanzman go for it. Appreciate.

**Comment by Seraf** [comment]
Hello @sergeylanzman, any news on this issue ?

As I'm using my api with JWT token, that will be a nice feature ^^

Thanks

**Comment by sergeylanzman** [comment]
@Seraf sorry , not started(on vocation)

**Comment by Seraf** [comment]
Hello,

Sorry for the bump, as I use JWT everywhere, my swagger interface is not usable anymore.
Have you some news about this feature please ?

Thanks !

**Comment by raulfortes** [comment]
@sergeylanzman any news about this ?

**Comment by franzwilhelm** [comment]
@raulfortes @Seraf, i have successfully implemented the complete swagger security spec in this PR: https://github.com/beego/bee/pull/436

Test passed, only waiting for merge!

**Comment by raulfortes** [comment]
Tks @franzwilhelm  ! Good Job !

**Comment by franzwilhelm** [comment]
@sergeylanzman @astaxie. please vlose this as it got solved in my pr.
