### ISSUE TITLE
a little bug

### ISSUE THREAD

**Issue by mu2611** [beego/bee#279]
![75cccdbf-8d28-45d3-9bce-2428dda69d93](https://cloud.githubusercontent.com/assets/2748359/18423731/39532db0-78da-11e6-98ae-c518b4b8cd9d.jpg)

**Comment by amrfaissal** [comment]
@mu2611 Works fine for me!

**Comment by amrfaissal** [comment]
@mu2611 Can you please close this issue? It's the same as #295.
