### ISSUE TITLE
1.5.2的version输出bug

### ISSUE THREAD

**Issue by mu2611** [beego/bee#295]
![3b529c35-f854-401c-a9db-0bb2e886deb1](https://cloud.githubusercontent.com/assets/2748359/19543042/ad2cfda8-96a6-11e6-866b-9080577c09f7.png)

操作系统：macOS 10.12

期间安装过go1.7.2，后继续安装的go1.7.3

**Comment by amrfaissal** [comment]
The `GoVersion: go1.7.2` is the runtime version i.e. the result of calling `runtime.Version()`. I think you need to update your Golang distribution by removing the folder `/usr/local/go` and extract it again.

**Comment by astaxie** [comment]
@amrfaissal I think this is the issue. As when you download the bee the runtime already build into that binary. But if we upgrade the Go again. actually the binary still use the old version. So I think need to get the version Dynamic

https://github.com/beego/bee/commit/270a52100c9d889fe5041ecc12e38078874c1e74#diff-ccde124315e74e68fae484840d08dff5

**Comment by amrfaissal** [comment]
@astaxie Good point. I've raised a PR.

**Comment by mu2611** [comment]
well done
