### ISSUE TITLE
融合了dev分支之后build不过了

### ISSUE THREAD

**Issue by kira8565** [beego/bee#297]
.\g_docs.go:784: cannot assign int to mp.Default (type string) in multiple assignment
.\g_docs.go:789: cannot assign bool to mp.Default (type string) in multiple assignment
.\g_docs.go:793: cannot assign float64 to mp.Default (type string) in multiple assignment
.\g_docs.go:797: cannot assign float64 to mp.Default (type string) in multiple assignment

**Comment by astaxie** [comment]
dev 对 dev
