### ISSUE TITLE
cross compile error, on mac compile with GOOS=linux GOARCH=amd64

### ISSUE THREAD

**Issue by sunlianqiang** [beego/bee#304]
I pack the program in mac for linux, sometimes go wrong after I upgrade my OS X from 10.11 to 10.12.
At first, I got one false in ten packs, now I can get 9 false in ten packs. 

**➜  ucvd-oss git:(dev_master) go env**
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
**GOOS="linux"**
GOPATH="/Users/slq/Desktop/go:/Users/slq/golang/own:/Users/slq/Desktop/Golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0"
CXX="clang++"
**CGO_ENABLED="0"**

**➜  ucvd-oss git:(dev_master) bee pack -be GOOS=linux**
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.5.2
2016/11/03 15:24:18 Packaging application: /Users/slq/Desktop/Golang/src/ucvd-oss
2016/11/03 15:24:18 Building application...
2016/11/03 15:24:18 Env: GOOS=linux GOARCH=amd64
# gopkg.in/mgo.v2/bson
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x799f0757f7b3 pc=0x1ed59]

runtime stack:
runtime.throw(0x45f860, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.(*gcWork).put(0xc820020720, 0xc8204c0000)
	/usr/local/go/src/runtime/mgcwork.go:87 +0x49
runtime.greyobject(0xc8204c0000, 0x0, 0x0, 0xc81ffd9fff, 0x0, 0xbc0200, 0xc820020720)
	/usr/local/go/src/runtime/mgcmark.go:1015 +0x2f1
runtime.shade(0xc8204c0000)
	/usr/local/go/src/runtime/mgcmark.go:953 +0x9a
runtime.gcmarkwb_m(0xc8204c0038, 0xc8204c0000)
	/usr/local/go/src/runtime/mbarrier.go:91 +0xc1
runtime.writebarrierptr_nostore1.func1()
	/usr/local/go/src/runtime/mbarrier.go:117 +0x134
runtime.systemstack(0xc82001e000)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:668

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82008f5c8 sp=0xc82008f5c0
runtime.writebarrierptr_nostore1(0xc8204c0038, 0xc8204c0000)
	/usr/local/go/src/runtime/mbarrier.go:118 +0x71 fp=0xc82008f600 sp=0xc82008f5c8
runtime.writebarrierptr(0xc8204c0038, 0xc8204c0000)
	/usr/local/go/src/runtime/mbarrier.go:137 +0x4b fp=0xc82008f630 sp=0xc82008f600
cmd/compile/internal/gc.Nod(0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/subr.go:379 +0x3c1 fp=0xc82008f650 sp=0xc82008f630
cmd/compile/internal/gc.newname(0xc8204ab800, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:372 +0x6c fp=0xc82008f688 sp=0xc82008f650
cmd/compile/internal/gc.newfuncname(0xc8204ab800, 0xc820000180)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:384 +0x25 fp=0xc82008f6a8 sp=0xc82008f688
cmd/compile/internal/gc.methodname1(0xc8204bfef0, 0xc8204bfc20, 0xc820090868)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1333 +0xa77 fp=0xc82008f830 sp=0xc82008f6a8
cmd/compile/internal/gc.(*yyParserImpl).Parse(0xc82002e048, 0xbb5728, 0x9a5260, 0x0)
	go.y:1497 +0xf96a fp=0xc820093ab0 sp=0xc82008f830
cmd/compile/internal/gc.yyparse()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:1854 +0xb4 fp=0xc820093af0 sp=0xc820093ab0
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:348 +0x1b6f fp=0xc820093df0 sp=0xc820093af0
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc820093e58 sp=0xc820093df0
main.main()
	/usr/local/go/src/cmd/compile/main.go:26 +0x189 fp=0xc820093f30 sp=0xc820093e58
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820093f80 sp=0xc820093f30
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820093f88 sp=0xc820093f80
exit status 2

**Comment by amrfaissal** [comment]
@sunlianqiang Maybe it's related to clang. Try to set `CC` to the absolute path of clang:
`$ CC=/path/to/clang GOOS=linux bee pack`

**Comment by sunlianqiang** [comment]
I have  confirmed that it's not related to clang. Maybe it is because I haven't "go install" the packages in linux_amd64 environment, if so it's not bee's error. But before I upgrade my mac from os x 10.11 to os x 10.12, I also didn't "go install" the packages and I haven't get an error for months!

**Comment by amrfaissal** [comment]
@sunlianqiang Is this still an issue?
