### ISSUE TITLE
beego/bee/watch.go:27:2: no buildable Go source files in github.com/howeyc/fsnotify

### ISSUE THREAD

**Issue by mi-work** [beego/bee#307]
question:
go get github.com/beego/bee
 github.com/beego/bee/watch.go:27:2: no buildable Go source files in github.com/howeyc/fsnotify

resolve:
vim watch.go
 27     //"github.com/howeyc/fsnotify"
 28     "gopkg.in/fsnotify.v0"

**Comment by amrfaissal** [comment]
@mi-work I don't think `gopkg.in/fsnotify.v0` is ready yet. To solve your problem, just do a `go get`:
`go get -u github.com/howeyc/fsnotify`.
