### ISSUE TITLE
不能下载bee

### ISSUE THREAD

**Issue by wangChange** [beego/bee#311]
linux ：

$ go get github.com/beego/bee

^C
下载好多次，每次都是一两个小时不动
-----------------------------------------------------

$ go build
conf.go:22:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
	/data/fooce/src/gopkg.in/yaml.v2 (from $GOPATH)

$ pwd
/data/gocode/src/github.com/beego/bee

$ go version
go version go1.7.3 linux/amd64

vim /etc/profile
export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH
export GOPATH=/data/fooce

以上是相关配置
-----------------------------

mac问题：

$ go get github.com/beego/bee

# cd .; git clone https://github.com/go-sql-driver/mysql /Users/wangguangjian/code/mycode/go/fooce/src/github.com/go-sql-driver/mysql
Cloning into '/Users/wangguangjian/code/mycode/go/fooce/src/github.com/go-sql-driver/mysql'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
package github.com/go-sql-driver/mysql: exit status 128
# cd .; git clone https://github.com/smartystreets/assertions /Users/wangguangjian/code/mycode/go/fooce/src/github.com/smartystreets/assertions
Cloning into '/Users/wangguangjian/code/mycode/go/fooce/src/github.com/smartystreets/assertions'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
package github.com/smartystreets/assertions: exit status 128

$ go version
go version go1.7.1 darwin/amd64

求助。。。。。

**Comment by wangChange** [comment]
下载gopkg.in/yaml.v2也是这样 很长时间不动

**Comment by astaxie** [comment]
网络问题我也没办法

**Comment by wangChange** [comment]
下载beego很正常  很快就下载好了  应该不是网络问题。。  
试了好多次下载beego  服务器用的阿里云

**Comment by wangChange** [comment]
@astaxie

**Comment by wangChange** [comment]
下载beego很正常 很快就下载好了 应该不是网络问题。。

试了好多次下载bee

 服务器用的阿里云

**Comment by astaxie** [comment]
从这个https://github.com/spf13/hugo/issues/297来看是git的版本问题，你试试用新版本的git

**Comment by wangChange** [comment]
好的谢谢，辛苦了 @astaxie
