### ISSUE TITLE
1.7.3的go 新建项目运行后报错   pkg parser.ParseDir error

### ISSUE THREAD

**Issue by zx84289061** [beego/bee#313]
go 1.7.3    按教程一键生成的项目报错 [ERRO] the myapi/controllers pkg parser.ParseDir error

**Comment by zx84289061** [comment]
换1.6.3还是一样的错

**Comment by amrfaissal** [comment]
@zx84289061 Can you reproduce this issue? Also Can you paste the entire error?

**Comment by astaxie** [comment]
@zx84289061 already solve the issue and still open it. As he contact me by QQ.
