### ISSUE TITLE
bee run error compile

### ISSUE THREAD

**Issue by mjniuz** [beego/bee#328]
I try to create new project then run it, but error message show like this

can't load package: C:\Users\Alan\go\src\myproject\main.go:5:2: non-standard import "github.com/astaxie/beego" in standard package "myproject"
..\github.com\astaxie\beego\config\ini.go:18:2: cannot find package "bufio" in any of:
        C:\Users\Alan\go\src\bufio (from $GOROOT)
        ($GOPATH not set)
..\github.com\astaxie\beego\admin.go:18:2: cannot find package "bytes" in any of:
        C:\Users\Alan\go\src\bytes (from $GOROOT)
        ($GOPATH not set)
..\github.com\astaxie\beego\context\acceptencoder.go:19:2: cannot find package "compress/flate" in any of:
        C:\Users\Alan\go\src\compress\flate (from $GOROOT)
        ($GOPATH not set)

and many more error for cannot find package

my GOPATH
$ echo $GOPATH
/c/Users/Alan/go

**Comment by amrfaissal** [comment]
Did you try `go get -v github.com/astaxie/beego`?
