### ISSUE TITLE
bee v1.6.0  Cannot find the object: models.Object

### ISSUE THREAD

**Issue by lenye** [beego/bee#332]
1、使用 bee api beetest 创建 API 应用；
2、运行应用；
3、swagger上的model为空；

**bee version**
├── Beego     : 1.7.2
├── GoVersion : go1.7.4
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : D:\gopath;G:\go
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Tuesday, 6 Dec 2016

**bee run -gendoc=true -downdoc=true**

2016/12/06 14:09:07 INFO     ▶ 0020 Start building...
2016/12/06 14:09:07 WARN     ▶ 0001 Cannot find the object: models.Object
2016/12/06 14:09:07 WARN     ▶ 0002 Cannot find the object: models.Object
2016/12/06 14:09:07 WARN     ▶ 0003 Cannot find the object: models.Object
2016/12/06 14:09:07 WARN     ▶ 0004 Cannot find the object: models.Object
2016/12/06 14:09:07 WARN     ▶ 0005 Cannot find the object: models.Object
2016/12/06 14:09:07 WARN     ▶ 0006 Cannot find the object: models.User
2016/12/06 14:09:07 WARN     ▶ 0007 Cannot find the object: models.User
2016/12/06 14:09:07 WARN     ▶ 0008 Cannot find the object: models.User
2016/12/06 14:09:07 WARN     ▶ 0009 Cannot find the object: models.User
2016/12/06 14:09:07 WARN     ▶ 0010 Cannot find the object: models.User
2016/12/06 14:09:07 SUCCESS  ▶ 0011 Docs successfully generated!
2016/12/06 14:09:07 INFO     ▶ 0021 ============== Generate Docs ===================

but run bee v.1.5.2 is OK

**Comment by angzhi** [comment]
这个bug还是存在......

**Comment by lenye** [comment]
Cannot find the object: models.Object 提示信息没了，但是

> 3、swagger上的model为空；

问题还在。。。

**Comment by astaxie** [comment]
```
➜  src cd beetest
➜  beetest bee run -gendoc=true -downdoc=true
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.2
2016/12/30 19:20:26 INFO     ▶ 0001 Using 'beetest' as 'appname'
2016/12/30 19:20:26 INFO     ▶ 0002 Loading default configuration...
2016/12/30 19:20:26 INFO     ▶ 0003 Downloading 'https://github.com/beego/swagger/archive/v2.zip' to 'swagger.zip'...
2016/12/30 19:20:33 SUCCESS  ▶ 0004 800610 bytes downloaded!
2016/12/30 19:20:33 INFO     ▶ 0005 Unzipping 'swagger.zip'...
2016/12/30 19:20:33 SUCCESS  ▶ 0006 Done! Deleting 'swagger.zip'...
2016/12/30 19:20:33 INFO     ▶ 0007 Initializing watcher...
2016/12/30 19:20:33 INFO     ▶ 0008 Watching: /Users/astaxie/develop/gopath/src/beetest/controllers
2016/12/30 19:20:33 INFO     ▶ 0009 Watching: /Users/astaxie/develop/gopath/src/beetest
2016/12/30 19:20:33 INFO     ▶ 0010 Watching: /Users/astaxie/develop/gopath/src/beetest/models
2016/12/30 19:20:33 INFO     ▶ 0011 Watching: /Users/astaxie/develop/gopath/src/beetest/routers
2016/12/30 19:20:33 INFO     ▶ 0012 Watching: /Users/astaxie/develop/gopath/src/beetest/tests
github.com/astaxie/beego/utils
github.com/astaxie/beego/grace
github.com/astaxie/beego/config
beetest/models
github.com/astaxie/beego/logs
github.com/astaxie/beego/toolbox
github.com/astaxie/beego/session
github.com/astaxie/beego/context
github.com/astaxie/beego
beetest/controllers
beetest/routers
beetest
2016/12/30 19:20:34 INFO     ▶ 0013 Generating the docs...
2016/12/30 19:20:35 SUCCESS  ▶ 0014 Docs generated!
2016/12/30 19:20:35 SUCCESS  ▶ 0015 Built Successfully!
2016/12/30 19:20:35 INFO     ▶ 0016 Restarting 'beetest'...
2016/12/30 19:20:35 SUCCESS  ▶ 0017 './beetest' is running...
2016/12/30 19:20:35 [I] [parser.go:91] generate router from comments
2016/12/30 19:20:35 [I] [router.go:232] /Users/astaxie/develop/gopath/src/beetest/controllers no changed
2016/12/30 19:20:35 INFO     ▶ 0018 Event fired: "/Users/astaxie/develop/gopath/src/beetest/routers/commentsRouter_controllers.go": CREATE
2016/12/30 19:20:35 [I] [asm_amd64.s:2086] http server Running on http://:8080
beetest/routers
beetest
2016/12/30 19:20:36 INFO     ▶ 0019 Skipping: "/Users/astaxie/develop/gopath/src/beetest/routers/commentsRouter_controllers.go": CHMOD
2016/12/30 19:20:37 INFO     ▶ 0020 Generating the docs...
2016/12/30 19:20:37 SUCCESS  ▶ 0021 Docs generated!
2016/12/30 19:20:38 SUCCESS  ▶ 0022 Built Successfully!
2016/12/30 19:20:38 INFO     ▶ 0023 Restarting 'beetest'...
2016/12/30 19:20:38 SUCCESS  ▶ 0024 './beetest' is running...
2016/12/30 19:20:38 [I] [router.go:232] /Users/astaxie/develop/gopath/src/beetest/controllers no changed
2016/12/30 19:20:38 [I] [router.go:232] /Users/astaxie/develop/gopath/src/beetest/controllers no changed
2016/12/30 19:20:38 [I] [asm_amd64.s:2086] http server Running on http://:8080
```

**Comment by lenye** [comment]
**v1.6.2**，bee run -gendoc=true
没有 Cannot find the object: models.Object 提示信息。

> 3、swagger上的model为空；

这个问题还在。

http://127.0.0.1:8080/swagger/#!/object/ObjectController_GetAll
swagger上的model为空；

![_2017-01-04t03-35-28 789z](https://cloud.githubusercontent.com/assets/109106/21631106/80d3d0d0-d272-11e6-8935-827686a83793.png)

![2fc75a42-cd1b-11e6-86f2-4683a9b317b9](https://cloud.githubusercontent.com/assets/109106/21631134/e8d62eda-d272-11e6-8c59-85391473b973.png)

**Comment by dylanlyu** [comment]
請在g_docs.go的第84行底下加入

`curPath, _ := os.Getwd()`
`parsePackagesFromDir(curPath)`

再重新編譯安裝
$ go build;go install

這樣子這個問題就解決了.
不知道為什麼在commit 03f2057版的時候被拿掉了.

**Comment by sergeylanzman** [comment]
Please check in develop branch
fix in https://github.com/beego/bee/pull/367

**Comment by ansiz** [comment]
> This bug is still exist when I make my porject on $GOPATH/src using soft link

Due to golang filepath.Walk does not follow symbolic links. 

> Walk walks the file tree rooted at root, calling walkFn for each file or directory in the tree, including root. All errors that arise visiting files and directories are filtered by walkFn. The files are walked in lexical order, which makes the output deterministic but means that for very large directories Walk can be inefficient. Walk does not follow symbolic links.
