### ISSUE TITLE
Can't run beego project normally after upgrade beego version

### ISSUE THREAD

**Issue by luffyke** [beego/bee#340]
### Action
Upgrade beego version from 1.6.1 to 1.7.2

### Error msg
perform ```bee fix``` command with 'Upgrade Done' successful message.
but get below error message after perform ```bee run```
```
docs/docs.go:17: undefined: swagger.ResourceListing
docs/docs.go:18: undefined: swagger.APIDeclaration
docs/docs.go:30: undefined: beego.GlobalDocAPI
docs/docs.go:37: undefined: beego.GlobalDocAPI
```

### Env
bee: 1.6.1
Beego     : 1.7.2
GoVersion : go1.7.4

**Comment by luffyke** [comment]
i use the new bee tool to create a new api project, and compare with the old project.

then remove ```_ "project_name/docs"``` in main.go, remove docs and swagger folder, then the old project is normal now.

**Comment by astaxie** [comment]
yea, the new swagger don't rely on the go files now. It will generate swagger.json now
