### ISSUE TITLE
error updating bee

### ISSUE THREAD

**Issue by dazmiller** [beego/bee#348]
C:\gowork\work\bin>go get -u github.com/beego/bee

# github.com/smartystreets/goconvey/convey/reporting
..\src\github.com\beego\bee\vendor\github.com\smartystreets\goconvey\convey\reporting\reports.go:9: import c:\gowork\work\pkg\windows_amd64/github.com/smartystreets/goconvey/convey/gotest.a: object is [windows amd64 go1.6.1 X:none] expected [windows amd64 go1.7 X:framepointer]

C:\gowork\work\bin>bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.0

├── Beego     : 1.7.2
├── GoVersion : go1.7
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 2
├── GOPATH    : c:\gowork\work;C:\gowork\work\src\nohassls-platform\admin
├── GOROOT    : C:\Go\
├── Compiler  : gc
└── Date      : Wednesday, 11 Jan 2017

**Comment by astaxie** [comment]
as you already update the Go version, you need to delete all the files in `$GOPATH/pkg`

**Comment by dazmiller** [comment]
Ah, will do, thank you for such a quick reply, I will try it now.

**Comment by dazmiller** [comment]
Perfect, worked firstime, I will close and leave this here incase anyone else has the same issue. Thank you for such a wonderful framework.
