### ISSUE TITLE
bee.json, Beefile does not work

### ISSUE THREAD

**Issue by wesley6j** [beego/bee#354]
I am using beego with postgresql. Therefore bee.json(Beefile) file can save a lot of typing. But it seems that while bee cli will read these files if they exist, the settings are not applied. I have Beefile inside project folder like this:
```
database:
  driver: "postgres"
  conn: "postgres://user:@localhost:5432/site?sslmode=disable"
```
The out put of `bee migrate`:

```
Loading configuration from 'Beefile'...
Using 'mysql' as 'driver'
Using 'root:@tcp(127.0.0.1:3306)/test' as 'conn'
```

Bee, beego, golang version:
```
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.6.2

├── Beego     : 1.7.2
├── GoVersion : go1.7.4
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/user/gowork
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Wednesday, 15 Feb 2017
```

**Comment by amrfaissal** [comment]
@wesley6j It works fine. Maybe your `Beefile` isn't well formatted. Having something like this:
```
database:
driver: "postgres"
```
Would cause `bee migrate` to fallback for `mysql` driver.

**Comment by wesley6j** [comment]
@amrfaissal I am sure it is indented as required. To be sure, I tried json format as well. json format does not work either:
```
{
	"database": {
		"driver": "postgres",
		"conn": "postgres://user:@localhost:5432/site?sslmode=disable"
	}
}
```

output:
```
▶ 0001 Loading configuration from 'bee.json'...
▶ 0002 Using 'mysql' as 'driver'
```

**Comment by wesley6j** [comment]
I am confused how[loadConfig](https://github.com/beego/bee/blob/master/conf.go#L81) works. So I put Println to see what is going on:
```
	fmt.Println(conf)
	err := loadConfig()
	fmt.Println(conf)
```
and it really does not do anything it is supposed to do:
```
{0 {false false} false [] {false   []} [] [] { [] []} { }}
2017/02/15 18:05:33 INFO     ▶ 0001 Loading configuration from 'bee.json'...
{0 {false false} false [] {false controllers models []} [] [] { [] []} { }}
```
It is confusing to me that `conf` was a type in [conf.go](https://github.com/beego/bee/blob/master/conf.go), but it is supposed to hold data like this?
```
if mDriver == "" {
	mDriver = docValue(conf.Database.Driver)
	if mDriver == "" {
		mDriver = "mysql"
	}
}
```

**Comment by wesley6j** [comment]
OK, I get it. conf is defined as a variable with anonymous struct. The problem is when conf is passed to a function to load data, its pointer should be passed: `err = parseJSON(path, &conf)`. I will make a pull request to fix it.

**Comment by wesley6j** [comment]
It has been solved in dev branch a long time ago...
