### ISSUE TITLE
bee command not found

### ISSUE THREAD

**Issue by vijeshkrishna** [beego/bee#360]
i am unable to create project with beego.I have installed beego inside my work space directory.

These are the env varibles i have set 

$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=c:\go_workspace
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

I have installed beego inside the gopath directory

**Comment by amrfaissal** [comment]
Did you try `go get -v github.com/beego/bee` ?

**Comment by astaxie** [comment]
what's PATH? did you add `$GOPATH/bin` into the `PATH`?

**Comment by RajatBanerjee** [comment]
https://github.com/beego/bee/issues/711
Installing it explicitly helped
