### ISSUE TITLE
bee new 不能识别go 1.8 默认的gopath

### ISSUE THREAD

**Issue by PandaFang** [beego/bee#379]
环境 windows 10 ， 没有手动配置gopath， 安装后golang后默认在用户目录下的go文件夹是gopath
按照文档在 go\src>bee new hello  创建的目录结构确实  src\hello ， 也就是说 在src下又建了一个src。所以我需要在 go 目录运行bee new
C:\Users\panda\go\src>bee new hello

| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.0
2017/03/17 11:28:03 WARN     ▶ 0001 You current workdir is not inside $GOPATH/src.
2017/03/17 11:28:03 INFO     ▶ 0002 Creating application...
        create   src\hello\
        create   src\hello\conf\
        create   src\hello\controllers\
        create   src\hello\models\
        create   src\hello\routers\
        create   src\hello\tests\
        create   src\hello\static\
        create   src\hello\static\js\
        create   src\hello\static\css\
        create   src\hello\static\img\
        create   src\hello\views\
        create   src\hello\conf\app.conf
        create   src\hello\controllers\default.go
        create   src\hello\views\index.tpl
        create   src\hello\routers\router.go
        create   src\hello\tests\default_test.go
        create   src\hello\main.go
2017/03/17 11:28:03 SUCCESS  ▶ 0003 New application successfully created!

当然手工配置一下gopath则无此问题

**Comment by astaxie** [comment]
谢谢，这个是Go1.8引入的新机制，我们需要支持一下
