### ISSUE TITLE
1.8.1 问题 bee api testapi4 -driver=mysql -conn="root:123456@tcp(192.168.0.4:3306)/didong"

### ISSUE THREAD

**Issue by clearluo** [beego/bee#400]
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.1
2017/03/31 18:00:26 WARN     ▶ 0001 You current workdir is not inside $GOPATH/src.
2017/03/31 18:00:26 INFO     ▶ 0002 Creating API...
        create   f:/go/src/testapi4
        create   f:\go\src\testapi4\conf
        create   f:\go\src\testapi4\controllers
        create   f:\go\src\testapi4\tests
        create   f:\go\src\testapi4\conf\app.conf
        create   f:\go\src\testapi4\main.go
2017/03/31 18:00:26 INFO     ▶ 0003 Using 'mysql' as 'driver'
2017/03/31 18:00:26 INFO     ▶ 0004 Using 'root:123456@tcp(192.168.0.4:3306)/didong' as 'conn'
2017/03/31 18:00:26 INFO     ▶ 0005 Using '' as 'tables'
2017/03/31 18:00:26 INFO     ▶ 0006 Analyzing database tables...
2017/03/31 18:00:26 FATAL    ▶ 0007 Cannot generate application code outside of GOPATH 'f:\go\'

**Comment by clearluo** [comment]
1.8.1 bee api 疑问

**Comment by amrfaissal** [comment]
@clearluo Can you copy/paste the output of `bee version` or `bee version -o json`?

**Comment by clearluo** [comment]
@amfaissal
 {
    "GoVersion": "go1.8",
    "GOOS": "windows",
    "GOARCH": "amd64",
    "NumCPU": 4,
    "GOPATH": "f:\\go\\",
    "GOROOT": "D:\\Go\\",
    "Compiler": "gc",
    "BeeVersion": "1.8.1",
    "BeegoVersion": "1.8.0"
}

**Comment by amrfaissal** [comment]
I think you should be inside you `%GOPATH%` before running `bee api`, so:
```
> cd %GOPATH%/src
> bee api testapi4
```

**Comment by clearluo** [comment]
bee api testapi4 is succful, but <bee api testapi5-driver=mysql -conn="root:123456@tcp(localhost:3306)/db" > is fail   
Cannot generate application code outside of GOPATH 'f:\go\'
I already inside %GOPATH%/src

**Comment by ayonsaha2011** [comment]
same problem here

**Comment by astaxie** [comment]
@amrfaissal this is the issue cause in new version as the window use `F:` while we use `f:` When that compare failed. Could you help to fix it?

**Comment by ieworks** [comment]
The command key is changed in new version,  Next command works for me:
bee generate appcode -SQLConn="root:sd-9898w@tcp(127.0.0.1:3306)/msresource?charset=utf8&loc=Local" -Level=1

**Comment by astaxie** [comment]
@ieworks that's another issue, I already fixed in develop now.

@clearluo fixed in develop branch
