### ISSUE TITLE
mac运行bee直接被kill了

### ISSUE THREAD

**Issue by AlpherJang** [beego/bee#403]
刚通过go get安装了bee，但是一运行bee就直接被os给kill了，什么报错信息也 没有，无论bee的什么指令都会被kill，安装目录都是在GOPATH下，beego跟tour也在里面但是都能正常运行只有bee不行，请问我改如何解决呢 
![image](https://cloud.githubusercontent.com/assets/11204522/24575609/600405a0-16dd-11e7-8ccc-b634b8094259.png)

**Comment by amrfaissal** [comment]
@AlpherJang This issue is fixed in `hotfix-dlv-support` branch. Same as https://github.com/beego/bee/issues/399.

**Comment by jackluo2012** [comment]
完全没有看懂是怎么解决的,切了版本也不行啊??

**Comment by astaxie** [comment]
@jackluo2012 这个是Mac下面Go1.8的问题，请升级Go

**Comment by jackluo2012** [comment]
hi,谢大，我是升了版本的，而且还是1.8.1之前在公司死活不行，回来家里，就好了

**Comment by AlpherJang** [comment]
你切换到hotfix-dlv-support分支然后运行进入相应的代码目录执行go install来安装当前分分支的bee工具就好了

**Comment by jackluo2012** [comment]
谢谢大家，已经可以了

**Comment by crazyhl** [comment]
请问应该如何解决啊，我也遇到了这个问题了，但是hotfix-dlv-support已经没有了

**Comment by astaxie** [comment]
@crazyhl 升级到Go1.8.1 重装就可以，这是Go1.8引入的bug

**Comment by crazyhl** [comment]
@astaxie 好的，我现在是1.7.5 我升级一下试试

**Comment by blust** [comment]
1.11也有这个问题吗？
