### ISSUE TITLE
api command bug with -conn parameter

### ISSUE THREAD

**Issue by thg303** [beego/bee#404]
`bee api matnax -driver=postgres -conn=user:password@localhost/db_name`
with postgres database, it results to a FATAL error:
`0007 Could not show tables: missing "=" after "user:password@localhost/db_name" in connection info string"`

I chased the source, looks like it is about "**generate/g_appcode.go**", "**GetTableNames**" function at line 515:
`// GetTableNames for PostgreSQL
func (*PostgresDB) GetTableNames(db *sql.DB) (tables []string) {
	rows, err := db.Query(`
		SELECT table_name FROM information_schema.tables
		WHERE table_catalog = current_database() AND
		table_type = 'BASE TABLE' AND
		table_schema NOT IN ('pg_catalog', 'information_schema')`)
	...
}`

I think WHERE statement should be like:
`table_schema = 'public'`

I tried to set up development environment for this package, but I am new to Go and I have no idea how to do it. it would be great if there was such documentations.

**Comment by ogero** [comment]
You are using mysql driver connection string syntax.  
Try following [pq - GoDoc](https://godoc.org/github.com/lib/pq) examples for connection strings.  
   
`bee api matnax -driver=postgres -conn="postgres://user:password@localhost/db_name"`  
`bee api matnax -driver=postgres -conn="user=user password=password host=localhost dbname=db_name"`
