### ISSUE TITLE
Delve support for darwin/amd64

### ISSUE THREAD

**Issue by dylanlyu** [beego/bee#406]
i try 
go get -u github.com/beego/bee
and
bee version
```
[bee]$ bee version
Killed: 9
[bee]$
```
try go get github.com/beego/bee reinstall.
The result is the same
but git change commit to 69023e9ae0b0d65cc2394c791c5af777311a06d4 this version.
is fine and is work.

```
[bee]$ go install
[bee]$ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.0

├── Beego     : 1.8.0
├── GoVersion : go1.8
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/dylan/.go:/Users/dylan/goProject
├── GOROOT    : /usr/local/opt/go/libexec
├── Compiler  : gc
└── Date      : Wednesday, 5 Apr 2017
[bee]$
```
I guess it should be delve question.
Is there any idea of this problem?

**Comment by amrfaissal** [comment]
@dylanlyu This is the same as https://github.com/beego/bee/issues/399. Can you please give the fix a try and let me know if it working for you? Thanks.

**Comment by dylanlyu** [comment]
is work.but bee dlv not Unknown
```
[bee]$ go install
[bee]$ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.8.1

├── Beego     : 1.8.0
├── GoVersion : go1.8
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/dylan/.go:/Users/dylan/goProject
├── GOROOT    : /usr/local/opt/go/libexec
├── Compiler  : gc
└── Date      : Wednesday, 5 Apr 2017
[bee]$ bee dlv
bee: Unknown subcommand.
Use bee help for more information.
[bee]$ 
```

**Comment by amrfaissal** [comment]
Delve support for `darwin/amd64` have some problems and I don't think its fully supported. Currently, `bee dlv` works only for `windows/amd64` and `linux/amd64`.

**Comment by dylanlyu** [comment]
It seems irrelevant to the certificate.
I not know.
Maybe you're right

**Comment by amrfaissal** [comment]
@dylanlyu Delve do support darwin/amd64 platforms. I'll attach the binaries to the pull request and I'd really appreciate if you can give it a test as I don't have an OSX machine.

**Comment by amrfaissal** [comment]
@astaxie Delve requires cgo for cross compilation. I tried to use `goxc` but It requires to change C Toolchain every time and for each platform. I came across this tool: https://github.com/karalabe/xgo which abstracts the complexity inside a Docker container. It generates the binaries without a problem but It doesn't bundle them in zip files and push them to Github. What do you think? I've modified the Makefile to use `xgo` directly but it only generates the binaries.

**Comment by dylanlyu** [comment]
Hi,
this develop branch is error!

```
[bee]$ bee
Killed: 9
```
Maybe this commit d9306e9fcf27d628f94f288c582c9a07c2f989ca

**Comment by astaxie** [comment]
@dylanlyu please update your Go version to `1.8.1`. This issue caused by XCode 8.3 https://github.com/golang/go/issues/19734

**Comment by dylanlyu** [comment]
is work!
Delve is work!

**Comment by astaxie** [comment]
@amrfaissal I just find these tools to replace `goxc`

1. https://github.com/karalabe/xgo to cross compile which support cgo
2. https://github.com/tcnksm/ghr upload release binary

**Comment by amrfaissal** [comment]
@astaxie Nice :+1:

**Comment by wuceyang** [comment]
1.8.1 is not work

**Comment by amrfaissal** [comment]
@wuceyang Make sure you have the latest version. Did you try: `go get -u github.com/beego/bee`?
