### ISSUE TITLE
安装bee 之后，启动不成功。

### ISSUE THREAD

**Issue by h3idan** [beego/bee#407]
```bash
xxxx @ ~/go/bin
 [110] → go get github.com/beego/bee

xxxx @ ~/go/bin
 [111] → bee new myblog
Killed: 9

xxxx @ ~/go/bin
 [112] →

```

bee 没有办法使用。总是killed是个什么鬼？

**Comment by amrfaissal** [comment]
Can you paste the output of `bee version -o json`?

**Comment by h3idan** [comment]
no, any command of bee always outout'killed 9'.

**Comment by h3idan** [comment]
no, any command of bee always output 'killed 9'.

**Comment by amrfaissal** [comment]
Ok, this issue is fixed in `hotfix-dlv-support` branch. See #399.

**Comment by h3idan** [comment]
OK. thx, I'll try once again.
