### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by HypnosNova** [beego/bee#408]
C:\Users\Administrator.PC-20121130NBVV\Desktop\bee-master>go build
# github.com/beego/bee/vendor/github.com/derekparker/delve/pkg/proc
D:\Go\src\github.com\beego\bee\vendor\github.com\derekparker\delve\pkg\proc\disasm.go:9: undefined: ArchInst

发生错误，ArchInst没有定义

**Comment by amrfaissal** [comment]
This was fixed in `develop` branch. If you have a `windows/amd64` platform, it should work fine for you.
