### ISSUE TITLE
bee 更新后启动时崩溃

### ISSUE THREAD

**Issue by wabzsy** [beego/bee#420]
更新之前是好用的 更新之后就运行不起来了
 

更新时提示:
Desktop > go get -u github.com/beego/bee
unexpected directory layout:
	import path: github.com/derekparker/delve/service
	root: /Users/wabzsy/Projects/Golang/src
	dir: /Users/wabzsy/Projects/Golang/src/github.com/beego/bee/vendor/github.com/derekparker/delve/service
	expand root: /Users/wabzsy/Projects/Golang/src
	expand dir: /Users/wabzsy/Projects/Golang/src/github.com/beego/bee/vendor/github.com/derekparker/delve/service
	separator: /

去掉-u参数之后能更新 但是不能运行
bin > go get github.com/beego/bee
bin > bee
[1]    50600 killed     bee

用gdb调试显示
Starting program: /Users/wabzsy/Projects/Golang/bin/bee
warning: Mach error at "darwin-nat.c:483" in function "void darwin_resume_inferior(struct inferior *)": (os/kern) invalid argument (0x4)
During startup program terminated with signal SIGKILL, Killed.

不知道是什么原因?
系统: macOS 10.12.4

**Comment by Pythonify** [comment]
兄弟我跟你一样的情况，怎么解决的？

**Comment by astaxie** [comment]
系统: macOS 10.12.4 的问题，你必须升级到Go1.8.1

**Comment by Pythonify** [comment]
哦好，谢谢
