### ISSUE TITLE
Why default credentials for migrations are hardcoded?

### ISSUE THREAD

**Issue by osavchenko** [beego/bee#424]
When I run command `bee migrate` without any parameters it's trying to use database credentials like `root:@tcp(127.0.0.1:3306)/test`. Why it can't take from configuration or somewhere else?

**Comment by astaxie** [comment]
@osavchenko bee will read from `-conn` first, if it's empty then it will read from config (Beefile or bee.json). if it's still empty, then it will use the default value `root:@tcp(127.0.0.1:3306)/test`

https://github.com/beego/bee/blob/master/cmd/commands/migrate/migrate.go#L91-L96
