### ISSUE TITLE
bee Killed: 9

### ISSUE THREAD

**Issue by raulfortes** [beego/bee#425]
rfortes@srad:~/Projects/go$ bee
Killed: 9
rfortes@srad:~/Projects/go$ bee version
Killed: 9

What i can do ?

My config:
go version go1.8.1 darwin/amd64
uname -a
Darwin srad.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
MacOS Sierra 10.12.4

**Comment by amrfaissal** [comment]
Did you try to remove `bee` completely from your $GOPATH and install it again?

**Comment by liuyang8903** [comment]
go version go1.8 darwin/amd64
MacOS Sierra 10.12.4
我也遇到同样的问题，我尝试删除bee执行文件重新安装，但是依然报Killed: 9错误

**Comment by amrfaissal** [comment]
Are you using the binary format directly? Or you installed `bee` using: `go get github.com/beego/bee`?

**Comment by liuyang8903** [comment]
bee命令带参数，不带参数都报Killed: 9，我尝试了删除 $GOPATH/src目录下github.com/beego/bee源码使用go get github.com/beego/bee命令安装和有源码使用go get -u github.com/beego/bee进行更新都是同样的错误

**Comment by raulfortes** [comment]
@amrfaissal Yes i tried to remove bee and install again using go get -u github.com/beego/bee
What more i can do ?

**Comment by volcano822** [comment]
我也遇到同样的问题。 go get -u github.com/beego/bee安装后，运行bee or bee help 同样报错“Killed: 9”

**Comment by astaxie** [comment]
this is the Go 1.8 issue. please upgrade to latest version and reinstall bee.

 go get -u github.com/beego/bee

**Comment by raulfortes** [comment]
@astaxie Im using go version go1.8.1 darwin/amd64 . I tried to reinstall bee an beego but the problem persist. What i can do ?

**Comment by astaxie** [comment]
@raulfortes did you retry `go get -u github.com/beego/bee`?

**Comment by raulfortes** [comment]
@astaxie I try again now and it works ! tks

**Comment by AbooJan** [comment]
It only work for me at `Bee` version 1.6.2 (Tag 1.6.2), `master`\`develop` not word.
Whatever my Go version update to 1.8 and delete update the `Bee`, It still show Killed: 9. 
My system is macOS 10.12.4。

It use command `go get -d github.com/beego/bee`, and then open it's src folder, then checkout to `Tag 1.6.2`, command `go build`, run the `bee` .

**Comment by astaxie** [comment]
@AbooJan you need to upgrade to Go 1.8.1
