### ISSUE TITLE
为什么bee api创建的项目，run和代码改变后，总是编译和运行两次

### ISSUE THREAD

**Issue by StoneThroll** [beego/bee#449]
![image](https://user-images.githubusercontent.com/7332370/27162689-355bf638-51b5-11e7-9a82-64ae2173922e.png)
![image](https://user-images.githubusercontent.com/7332370/27162697-3f704e9e-51b5-11e7-8b6e-5fbe1ecce2dc.png)

版本信息
![image](https://user-images.githubusercontent.com/7332370/27162716-4dff5c66-51b5-11e7-8c81-2e9ee563726e.png)

**Comment by fengjiongmax** [comment]
可以看到第一次编译的时候会有 generate router from comments，第二次没有
根据 [官方文档](https://beego.me/docs/mvc/controller/router.md#%E6%B3%A8%E8%A7%A3%E8%B7%AF%E7%94%B1)的说法，在检测到文件夹内容有变动之后会生成`routers/commentsRouter.go`这个文件，再进行下面的编译。
在第一次编译完后重新监控文件夹内容，发现了新文件（或者这个文件被重新生成过），就再一次进行编译。
你可以试试看分别修改models和controllers里面的文件，会发现修改models里面的文件不会编译两次，但是修改controllers里面的文件会编译两次。
