### ISSUE TITLE
昨晚更新bee到最新版本.bee命令无法运行

### ISSUE THREAD

**Issue by liteck** [beego/bee#451]
昨晚更新bee到最新版本.bee命令无法运行.
然后checkout到v1.8.3.同样无法运行.
checkout到 1.6.2后.才可以运行..
运行bee..就出现 [1]    1252 killed     bee new hell
环境:
├── Beego     : 1.8.3
├── GoVersion : go1.8
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── Compiler  : gc
└── Date      : Monday, 19 Jun 2017

**Comment by liteck** [comment]
测试了一下.发现..是 
github.com/beego/bee/cmd/commands/dlv 这个地方.引起的.....我注释了就可以运行了

**Comment by liteck** [comment]
再具体点是 github.com/derekparker/delve 这个包..这个包去掉..也可以运行...不知道是不是mac系统的关系

**Comment by qinhao** [comment]
+1

**Comment by fishioon** [comment]
https://github.com/golang/go/issues/19734
应该是这个问题，
go build -ldflags -s
应该就可以了

**Comment by gebaolei** [comment]
+1

**Comment by astaxie** [comment]
大家记得更新Go到1.8.1以上，这是最新的Mac系统的问题引起的

**Comment by anazh** [comment]
@astaxie 更新到1.8.3 [go1.8.3 darwin/amd64] 还是一样
