### ISSUE TITLE
Cannot Generate API Postgres

### ISSUE THREAD

**Issue by kieusonlam** [beego/bee#460]
Hi,

I trying generate api project using postgres
`bee api beeapi -driver=postgres -conn=postgres://postgres:postgres@127.0.0.1:5432/beeapi?sslmode=disable`
I got this errors
```
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.0
2017/08/01 15:58:45 INFO     ▶ 0001 Creating API...
        create   C:\Users\kieusonlam\go\src\beeapi
        create   C:\Users\kieusonlam\go\src\beeapi\conf
        create   C:\Users\kieusonlam\go\src\beeapi\controllers
        create   C:\Users\kieusonlam\go\src\beeapi\tests
        create   C:\Users\kieusonlam\go\src\beeapi\conf\app.conf
        create   C:\Users\kieusonlam\go\src\beeapi\main.go
2017/08/01 15:58:45 INFO     ▶ 0002 Using 'postgres' as 'driver'
2017/08/01 15:58:45 INFO     ▶ 0003 Using 'postgres://postgres:postgres@127.0.0.1:5432/beeapi?sslmode=disable' as 'conn'
2017/08/01 15:58:45 INFO     ▶ 0004 Using '' as 'tables'
2017/08/01 15:58:45 INFO     ▶ 0005 Analyzing database tables...
2017/08/01 15:58:45 FATAL    ▶ 0006 GOPATH environment variable is not set or empty
```
am I doing wrong something?

I using Windows 10 by the way.

**Comment by astaxie** [comment]
`GOPATH environment variable is not set or empty`

does you set the GOPATH?

**Comment by yonathanwsusilo** [comment]
Hi @astaxie, I have problem when generate api project using postgres
`bee api loginJurnalSC -tables="ms_users" -driver=postgres -conn=postgres://postgres:postgres@127.0.0.1:5432/test?sslmode=disable`

I got a fact that controller is not created

> ______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0
2020/02/05 00:33:37 INFO     ▶ 0001 Creating API...
        create   /Users/yonathanws/go/src/loginJurnalSC
        create   /Users/yonathanws/go/src/loginJurnalSC/conf
        create   /Users/yonathanws/go/src/loginJurnalSC/controllers
        create   /Users/yonathanws/go/src/loginJurnalSC/tests
        create   /Users/yonathanws/go/src/loginJurnalSC/conf/app.conf
        create   /Users/yonathanws/go/src/loginJurnalSC/main.go
2020/02/05 00:33:37 INFO     ▶ 0002 Using 'postgres' as 'driver'
2020/02/05 00:33:37 INFO     ▶ 0003 Using 'postgres://postgres:postgres@127.0.0.1:5432/postgres?sslmode=disable' as 'conn'
2020/02/05 00:33:37 INFO     ▶ 0004 Using 'ms_users' as 'tables'
2020/02/05 00:33:37 INFO     ▶ 0005 Analyzing database tables...
2020/02/05 00:33:38 INFO     ▶ 0006 Creating model files...
        create   /Users/yonathanws/go/src/loginJurnalSC/models/ms_users.go
2020/02/05 00:33:38 INFO     ▶ 0007 Creating controller files...
2020/02/05 00:33:38 INFO     ▶ 0008 Creating router files...
        create   /Users/yonathanws/go/src/loginJurnalSC/routers/router.go
2020/02/05 00:33:38 SUCCESS  ▶ 0009 New API successfully created!

at INFO 0007 creating controller files, but it not generate some file. Why?
