### ISSUE TITLE
bee migrate not work with MariaDB@10.2.9

### ISSUE THREAD

**Issue by airylinus** [beego/bee#477]
I got Fatal error when execute 

>\>bee migrate refresh -driver=mysql -conn="root:blablawawa@tcp(127.0.0.1:3306)/test"
>\>2017/10/03 16:09:52 FATAL    ▶ 0004 Column migration.timestamp type mismatch: TYPE: timestamp, DEFAULT: current_timestamp()

After some dig work, I found this:

Create table in MariaDB@10.2.9 with SQL below:

```sql
CREATE TABLE migrations (
  | created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'date migrated or rolled back',
  | ) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

And then we got this:

>\> show create table migrations;
>\>`created_at` timestamp NOT NULL DEFAULT **current_timestamp()** COMMENT 'date migrated or rolled back',

_note: **current_timestamp** NOW turn to **current_timestamp()**_

Bee will validate `default ` value this way [code](https://sourcegraph.com/github.com/beego/bee@e6bb3f893cfd4e57549f60b45aa77e03b1040ad8/-/blob/cmd/commands/migrate/migrate.go?utm_source=share#L190) that makes migrate not work with MariaDB@10.2.9

**Comment by natansdj** [comment]
I have the same issue.

Bee         : 1.10.0
Beego     : 1.11.1
GoVersion : go1.11.5
MariaDB@10.2.8

> FATAL    ▶ 0005 Column migration.timestamp type mismatch: TYPE: timestamp, DEFAULT: current_timestamp()

Any news about this?

**Comment by Sotatek-HenryPham** [comment]
```
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0
2019/02/18 16:50:59 INFO     ▶ 0001 Using 'mysql' as 'driver'
2019/02/18 16:50:59 INFO     ▶ 0002 Using 'root:@tcp(127.0.0.1:3306)/bee_go_trading' as 'conn'
2019/02/18 16:50:59 INFO     ▶ 0003 Using '/Users/phonglan/go/src/trading/database/migrations' as 'dir'
2019/02/18 16:50:59 INFO     ▶ 0004 Running all outstanding migrations
2019/02/18 16:50:59 FATAL    ▶ 0005 Column migration.timestamp type mismatch: TYPE: timestamp, DEFAULT: current_timestamp()
```
```
mysql  Ver 15.1 Distrib 10.3.12-MariaDB, for osx10.14 (x86_64) using readline 5.1
```
```
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0

├── Beego     : 1.11.1
├── GoVersion : go1.11.5
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 4
├── GOPATH    : /Users/phonglan/go
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Monday, 18 Feb 2019
```
Me too, I have the same issue :(.

Someone help me to resolve this issue?

**Comment by jenishj-crest** [comment]
Facing same issue 

`
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0
2019/03/25 11:05:00 INFO     ▶ 0001 Using 'mysql' as 'driver'
2019/03/25 11:05:00 INFO     ▶ 0002 Using 'root:Abcdefg1@/bee?charset=utf8' as 'conn'
2019/03/25 11:05:00 INFO     ▶ 0003 Using '/home/crest/go/src/BeeApi/database/migrations' as 'dir'
2019/03/25 11:05:00 INFO     ▶ 0004 Running all outstanding migrations
2019/03/25 11:05:00 INFO     ▶ 0005 Creating 'migrations' table...
2019/03/25 11:05:01 FATAL    ▶ 0006 Column migration.timestamp type mismatch: TYPE: timestamp, DEFAULT: current_timestamp()

`

**Comment by LasNeo** [comment]
same issue

`
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.10.0
2019/03/29 01:33:34 INFO     ▶ 0001 Using 'mysql' as 'driver'
2019/03/29 01:33:34 INFO     ▶ 0002 Using 'root:@tcp(127.0.0.1:3306)/mx' as 'conn'
2019/03/29 01:33:34 INFO     ▶ 0003 Running all outstanding migrations
2019/03/29 01:33:34 INFO     ▶ 0004 Creating 'migrations' table...
2019/03/29 01:33:34 FATAL    ▶ 0005 Column migration.timestamp type mismatch: TYPE: timestamp, DEFAULT: current_timestamp()`

**Comment by HDFWebsite** [comment]
解决方式
https://blog.csdn.net/weixin_43671322/article/details/89537182
