### ISSUE TITLE
bee 工具执行失败

### ISSUE THREAD

**Issue by TianQingS** [beego/bee#489]
提示： write /dev/stdout: A device attached to the system is not functioning.

beego/bee/logger.(*BeeLogger).must:og这里出错了。
go1.9.2， windows/amd64环境

**Comment by TianQingS** [comment]
err := logRecordTemplate.Execute(l.output, record)
if err != nil {
		panic(err)
}

**Comment by TianQingS** [comment]
找到问题了，编码问题

**Comment by caylaXu** [comment]
能问下怎么解决的吗？我安装完bee version的时候报一样的错

**Comment by caylaXu** [comment]
> 找到问题了，编码问题
能问下怎么解决的吗？我安装完bee version的时候报一样的错
