### ISSUE TITLE
zsh: killed     bee 

### ISSUE THREAD

**Issue by giovapanasiti** [beego/bee#495]
I installed Beego on a mac os computer but I can't run bee command anyhow. Whatever I try to do I get this error:

```
zsh: killed     bee version
```

**Comment by astaxie** [comment]
it looks this related to the Go version. Could you update to the latest Go version

**Comment by giovapanasiti** [comment]
I don't think so I was running Go1.8, updated it to the latest 1.9 and still get the same error message
