### ISSUE TITLE
可否支持一下Docker

### ISSUE THREAD

**Issue by YiNo** [beego/bee#541]
我给beego提个需求:
 bee run 是编译+运行， go build 又不支持生成 commentsRouter_controllers.go , 编译出来的会导致404.  
可否把 bee build  加一个参数， 做成只编译的。   来支持一下docker.

有人说用bee pack 但是pack会打成一个tar包。

**Comment by DennisMao** [comment]
已支持

**Comment by YiNo** [comment]
> 已支持

how to use?

**Comment by DennisMao** [comment]
@YiNo https://github.com/beego/bee#bee-dockerize

**Comment by amrfaissal** [comment]
Closing this one since your question has been answered.
