### ISSUE TITLE
Macbook Pro Mojave bee 不能安装

### ISSUE THREAD

**Issue by dcsty** [beego/bee#551]
> 安装bee工具的时候提示错误

github.com/beego/bee
/usr/local/go/pkg/tool/darwin_amd64/link: /usr/local/go/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)

> go version go1.10 darwin/amd64

> go env的信息：

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dcs/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dcs/Desktop/xxx/GoLang"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/k7/f0rmqypj6gz6gzx1n566qbjw0000gn/T/go-build553239454=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by jjeejj** [comment]
我也遇到这样的问题了，有解决的吗？ 
`combining dwarf failed: Unknown load command 0x32 (50)`

**Comment by fzzf0618** [comment]
我也遇到了，不知道怎么解决

**Comment by firesh** [comment]
@fzzf0618 @jjeejj @dcsty 找到答案了，go v1.11.1版本已经解决了。brew安装的go目前不能直接brew ugrade升级，要自己手动升级。

**Comment by jjeejj** [comment]
@firesh  是可以用 `brew upgrade go` 升级 `go` 的。升级成功后，重新配置一下 `GOPATH` 环境变量就好了
![image](https://user-images.githubusercontent.com/15176971/47094524-f6404a00-d25d-11e8-9e10-1aff0b8ee12b.png)

**Comment by firesh** [comment]
@jjeejj 我这没成功，所以手动升级了。可以那就更好。

**Comment by fzzf0618** [comment]
@firesh 谢谢！

**Comment by dcsty** [comment]
@firesh 今天才想起来问了个问题，我的问题也一直没解决呢，今天看了你的回答才解决了问题，多谢了

**Comment by corningsun** [comment]
@firesh 
brew 安装的 go 目录是 `/usr/local/Cellar/go/1.xxx.xx/`

先删除非 brew 安装的go

```
sudo rm -rf /usr/local/go
rm -rf /usr/local/bin/go
rm -rf /usr/local/opt/go
```

然后配置 GOPATH 等环境变量就可以了

```
# go
export GOPATH=/usr/local/Cellar/go/1.12.9
export GOROOT=/usr/local/Cellar/go/1.12.9/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
```
查看当前生效的 go 
```
$ which go
/usr/local/Cellar/go/1.12.9/bin/go

$ go version
go version go1.12.9 darwin/amd64
```

**Comment by lzcdev** [comment]
> @firesh
> brew 安装的 go 目录是 `/usr/local/Cellar/go/1.xxx.xx/`
> 
> 先删除非 brew 安装的go
> 
> ```
> sudo rm -rf /usr/local/go
> rm -rf /usr/local/bin/go
> rm -rf /usr/local/opt/go
> ```
> 
> 然后配置 GOPATH 等环境变量就可以了
> 
> ```
> # go
> export GOPATH=/usr/local/Cellar/go/1.12.9
> export GOROOT=/usr/local/Cellar/go/1.12.9/libexec
> export PATH=$PATH:$GOPATH/bin
> export PATH=$PATH:$GOROOT/bin
> ```
> 
> 查看当前生效的 go
> 
> ```
> $ which go
> /usr/local/Cellar/go/1.12.9/bin/go
> 
> $ go version
> go version go1.12.9 darwin/amd64
> ```

亲测可用
