### ISSUE TITLE
Doesn`t colorize logs in log file

### ISSUE THREAD

**Issue by SavostinVladimir** [beego/bee#564]
When I run my app with logs to stdout it's ok, I see the colorful logs, but when I write log to the file it's not colorful! What do I do wrong?? Thanks

**Comment by daftred** [comment]
Ascii log color formats are specific to the terminal. I don't think the file log configuration by default includes the log color ascii special characters.

**Comment by amrfaissal** [comment]
As @daftred stated, the ASCII codes are specific to the terminal and only works on terminal output. I'm closing this for now. If you have a feature request in mind, please feel free to create a new one.
