### ISSUE TITLE
MAC 10.14.3 安装bee报错 go1.11.4版本

### ISSUE THREAD

**Issue by Zengzehao** [beego/bee#590]
错误信息：
cengzehaodeMacBook-Pro:~ zengzehao$ go get -u -v github.com/beego/bee
github.com/beego/bee (download)
github.com/beego/bee/vendor/github.com/derekparker/delve/proc
# github.com/beego/bee/vendor/github.com/derekparker/delve/proc
ld: malformed file
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd:4:18: error: unknown enumerated scalar
platform:        zippered
                 ^~~~~~~~
 file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zengzehao/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/zengzehao/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xt/p72g3jsd0zncc1yv8vnzs3l00000gn/T/go-build444504700=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by justloader** [comment]
升级 Xcode

**Comment by askuy** [comment]
support go mod
