### ISSUE TITLE
install bee fail，Unsupported go mod？

### ISSUE THREAD

**Issue by haytoo1** [beego/bee#591]
My steps is：
1. `go mod init`
2. `go get -u github.com/astaxie/beego `，it works
3. `go get -u github.com/beego/bee`，fail，

error message:
```
go: github.com/derekparker/delve@v1.2.0: parsing go.mod: unexpected module path "github.com/go-delve/delve"
go: error loading module requirements
```

**Comment by realguan** [comment]
module test

replace github.com/beego/bee v1.10.0 => github.com/realguan/bee v1.12.1

go 1.12

**Comment by RanQiwu** [comment]
> replace the source , solved perfectly! github.com/realguan/bee v1.12.1
> 
> module test
> 
> replace github.com/beego/bee v1.10.0 => github.com/realguan/bee v1.12.1
> 
> go 1.12

666

**Comment by titusjoyson** [comment]
```
Subpackage github.com/derekparker/delve/service/rpc2 is missing. (Package is required by github.com/beego/bee@master.)	
Subpackage github.com/derekparker/delve/service/rpccommon is missing. (Package is required by github.com/beego/bee@master.)	
Subpackage github.com/derekparker/delve/pkg/terminal is missing. (Package is required by github.com/beego/bee@master.)	
Subpackage github.com/derekparker/delve/service is missing. (Package is required by github.com/beego/bee@master.)
```

**Comment by kurosakisora** [comment]
vim go.mod, add this fixed.

replace github.com/derekparker/delve => github.com/go-delve/delve v1.4.0 // indirect

**Comment by askuy** [comment]
supoort go mod
