### ISSUE TITLE
go 1.11 编译报错，github.com/derekparker/delve@v1.2.0: parsing go.mod: unexpected modu

### ISSUE THREAD

**Issue by frankxieke** [beego/bee#601]
github.com/derekparker/delve@v1.2.0: parsing go.mod: unexpected module

**Comment by frankxieke** [comment]
使用go 1.9没有问题

**Comment by frankxieke** [comment]
大佬是不是考虑支持下go 1.11

**Comment by realguan** [comment]
replace the source , solved perfectly!  github.com/realguan/bee v1.12.1

module test

replace github.com/beego/bee v1.10.0 => github.com/realguan/bee v1.12.1

go 1.12

**Comment by askuy** [comment]
support go mod
