### ISSUE TITLE
算了，不折腾了，心累，使用Gin去。

### ISSUE THREAD

**Issue by RanQiwu** [beego/bee#611]

**Comment by RanQiwu** [comment]
1. CLI使用有 `GOPATH` 限制是个非常愚蠢的行为。
2. CLI生成的代码有缺陷，需要大量手动修复。

**Comment by realguan** [comment]
bee好久没更新了，go mod 下很多问题。我折腾了一个星期才解决。这有个教程给你看看 http://www.678fly.cn/

**Comment by RanQiwu** [comment]
> bee好久没更新了，go mod 下很多问题。我折腾了一个星期才解决。这有个教程给你看看 http://www.678fly.cn/

非常感觉！

**Comment by RanQiwu** [comment]
@realguan 这个教程很好，我已经可以正常运行起来了。但是router有问题：
![image](https://user-images.githubusercontent.com/22112008/61035975-bb3d0280-a3fa-11e9-8583-90b401c41bcc.png)
![image](https://user-images.githubusercontent.com/22112008/61036012-c98b1e80-a3fa-11e9-89bd-0a1f6ac0567c.png)

**Comment by RanQiwu** [comment]
`bee generate controller ` 也有问题。
![image](https://user-images.githubusercontent.com/22112008/61038124-078a4180-a3ff-11e9-9961-30690b09e8fa.png)

**Comment by RanQiwu** [comment]
Bee: https://github.com/RanQiwu/bee
Usage: `go get github.com/ranqiwu/bee`

Beego: https://github.com/RanQiwu/beego_
Usage: `go get github.com/RanQiwu/beego_`

It just works for me.

Simple steps:
```bash
# Install Bee
go get github.com/ranqiwu/bee

# Create project
bee api PROJECTNAME
cd PROJECTNAME
go mod init PROJECTNAME
bee run
```

**Comment by ykrl089** [comment]
> Bee: https://github.com/RanQiwu/bee
> Usage: `go get github.com/ranqiwu/bee`
> 
> Beego: https://github.com/RanQiwu/beego_
> Usage: `go get github.com/RanQiwu/beego_`
> 
> It just works for me.
> 
> Simple steps:
> 
> ```shell
> # Install Bee
> go get github.com/ranqiwu/bee
> 
> # Create project
> bee api PROJECTNAME
> cd PROJECTNAME
> go mod init PROJECTNAME
> bee run
> ```

稍微有点问题，bee run的时候无法生成注解路由

**Comment by RanQiwu** [comment]
生成注解路由是beego的问题，它不支持GOPATH外，要把beego也要换一起成我改的那个。
