### ISSUE TITLE
install bee on ubuntu error.在Ubuntu上安装bee报错.

### ISSUE THREAD

**Issue by samshuai** [beego/bee#615]
error info:
root@HTYY:~/go# go get -u github.com/beego/bee
# github.com/beego/bee/vendor/golang.org/x/sys/unix
src/github.com/beego/bee/vendor/golang.org/x/sys/unix/syscall_linux_amd64.go:65:1: error: redefinition of ‘gettimeofday’
 func gettimeofday(tv *Timeval) (err syscall.Errno)
 ^
src/github.com/beego/bee/vendor/golang.org/x/sys/unix/gccgo_linux_amd64.go:14:1: note: previous definition of ‘gettimeofday’ was here
 func gettimeofday(tv *Timeval) (err syscall.Errno) {
 ^
src/github.com/beego/bee/vendor/golang.org/x/sys/unix/syscall_unix.go:52:1: error: redefinition of ‘Syscall’
 func Syscall(trap, a1, a2, a3 uintptr) (r1, r2 uintptr, err syscall.Errno)
 ^
src/github.com/beego/bee/vendor/golang.org/x/sys/unix/gccgo.go:17:1: note: previous definition of ‘Syscall’ was here
 func Syscall(trap, a1, a2, a3 uintptr) (r1, r2 uintptr, err syscall.Errno) {
 ^
src/github.com/beego/bee/vendor/golang.org/x/sys/unix/syscall_unix.go:53:1: error: redefinition of ‘Syscall6’
 func Syscall6(trap, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err syscall.Errno)
 ^
src/github.com/beego/bee/vendor/golang.org/x/sys/unix/gccgo.go:24:1: note: previous definition of ‘Syscall6’ was here
 func Syscall6(trap, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err syscall.Errno) {
 ^
src/github.com/beego/bee/vendor/golang.org/x/sys/unix/syscall_unix.go:54:1: error: redefinition of ‘RawSyscall’
 func RawSyscall(trap, a1, a2, a3 uintptr) (r1, r2 uintptr, err syscall.Errno)
 ^
src/github.com/beego/bee/vendor/golang.org/x/sys/unix/gccgo.go:38:1: note: previous definition of ‘RawSyscall’ was here
 func RawSyscall(trap, a1, a2, a3 uintptr) (r1, r2 uintptr, err syscall.Errno) {
 ^
src/github.com/beego/bee/vendor/golang.org/x/sys/unix/syscall_unix.go:55:1: error: redefinition of ‘RawSyscall6’
 func RawSyscall6(trap, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err syscall.Errno)
 ^
src/github.com/beego/bee/vendor/golang.org/x/sys/unix/gccgo.go:43:1: note: previous definition of ‘RawSyscall6’ was here
 func RawSyscall6(trap, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err syscall.Errno) {
 ^

**Comment by samshuai** [comment]
root@HTYY:/etc/v2ray# go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-linux-gnu/8"
GCCGO="/usr/bin/x86_64-linux-gnu-gccgo-8"
CC="x86_64-linux-gnu-gcc-8"
CXX="x86_64-linux-gnu-g++-8"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build609841839=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

**Comment by askuy** [comment]
使用go get github.com/beego/bee指令
