### ISSUE TITLE
bee安装失败

### ISSUE THREAD

**Issue by LanceAdd** [beego/bee#617]
go: github.com/derekparker/delve@v1.2.0: parsing go.mod: unexpected module path "github.com/go-delve/delve"
go: error loading module requirements
我是go version go1.12.7 darwin/amd64

**Comment by changrui** [comment]
Me too.

**Comment by hustjiangtao** [comment]
Me too +1
---
go version go1.12.9 darwin/amd64

**Comment by hustjiangtao** [comment]
@shanyujie @changrui fix it by using `go get -fix` without go mod on macOS `go version go1.12.9 darwin/amd64`

```bash
# first
export GO111MODULE=off
# then
go get -fix github.com/beego/bee
```

It will take a little time. Be patient.

**Comment by askuy** [comment]
use go > 1.12
go get github.com/beego/bee
