### ISSUE TITLE
bee tool install breaks on delve

### ISSUE THREAD

**Issue by mpetavy** [beego/bee#622]
I installed the latest version of BEEGO and wanted to continue with the BEE tool but it break with an error due to delve:

[ransom@xmas ~]$ go get -u github.com/beego/bee
go: finding github.com/derekparker/delve/service/rpc2 latest
go: finding github.com/derekparker/delve/service/rpccommon latest
go: finding github.com/derekparker/delve/service latest
go: finding github.com/derekparker/delve/terminal latest
go: finding github.com/astaxie/beego/utils latest
go: finding github.com/astaxie/beego/swagger latest
go: github.com/derekparker/delve@v1.2.0: parsing go.mod: unexpected module path "github.com/go-delve/delve"
go: error loading module requirements

My GO environment:

go version go1.12.7 linux/amd64

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ransom/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ransom/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build881946035=/tmp/go-build -gno-record-gcc-switches"

**Comment by imac-beep** [comment]
The same issue for me.Since this issue is closed, how did you solve this ? @mpetavy

**Comment by mpetavy** [comment]
Brute force, I simply removed the "<GOPATH>\pkg" dir and recompiled everything from scratch.
Hope this help u2.
