### ISSUE TITLE
bee run -runmode=prod

### ISSUE THREAD

**Issue by iclings** [beego/bee#628]
...

**Comment by uidsun** [comment]
app.conf
`appname = wxgo

[dev]
httpport = 8080
[test]
httpport = 8888
[prod]
httpport = 80`

running...
`2019/09/06 09:47:23 INFO     ▶ 0001 Using 'wxgo' as 'appname'
2019/09/06 09:47:23 INFO     ▶ 0002 Using 'prod' as 'runmode'
2019/09/06 09:47:23 INFO     ▶ 0003 Initializing watcher...
2019/09/06 09:47:25 SUCCESS  ▶ 0004 Built Successfully!
2019/09/06 09:47:25 INFO     ▶ 0005 Restarting 'wxgo'...
2019/09/06 09:47:25 SUCCESS  ▶ 0006 './wxgo' is running...
2019/09/06 09:47:25.267 [I]  http server Running on http://:8080
`

**Comment by guhan121** [comment]
what happen？
