### ISSUE TITLE
bee rundocs gives "unknown subcommand" after updating bee tool

### ISSUE THREAD

**Issue by maboueita** [beego/bee#63]
After updating to 
bee   :1.2.2
beego :1.4.0

running ' bee rundocs -isDownload=true '  to run the auto-generate documents gives 
bee: unknown subcommand "rundocs"

**Comment by orospakr** [comment]
Hm, `bee run -gendoc=true` also fails with:

```
$ bee run -gendoc=true
flag provided but not defined: -gendoc
```
