### ISSUE TITLE
vendor 目录不该提交

### ISSUE THREAD

**Issue by sinkcup** [beego/bee#634]
vendor 是第三方网络库，应该通过网络安装，而禁止提交代码仓库。

https://github.com/beego/bee/tree/develop/vendor

![image](https://user-images.githubusercontent.com/4971414/66533792-bba68000-eb46-11e9-9f4c-27628653052f.png)

**Comment by niuge666** [comment]
对于国内被墙的用户来说，提交完整vender简直太棒了，你这B不要没事找事，滚一边玩去

**Comment by DennisMao** [comment]
@sinkcup  这里有些历史遗留，毕竟创建Bee的时候还没有GOPROXY,直接拉会比较麻烦。作者应该也考虑到国内用户。

**Comment by sinkcup** [comment]
@DennisMao 是的，不过国内用户知道上 GitHub 的，一般网络都搞好了。

我估计是当初 Go 还不支持 module，真奇怪 Google 在这么早期不成熟的阶段放出来给大家用，就像微信小程序，很晚才支持 npm……导致初期项目质量非常垃圾。

**Comment by DennisMao** [comment]
等delve那个去掉应该就能升级到go mod 然后把vendor去掉了。
