### ISSUE TITLE
Can I customize my appName , with bee pack ?

### ISSUE THREAD

**Issue by xavierror** [beego/bee#639]
Can I customize my appName , with bee pack ?
like this:
`bee pack -be appName=bootstrap`

I want to make my all projects' binary file use bootstrap as the filename , but I cannot rename my projects with the same name

**Comment by guhan121** [comment]
you want change build binary file name?

**Comment by guhan121** [comment]
```
git clone https://github.com/guhan121/bee.git
cd bee
git checkout v1.10.2
go build 
# copy bee into PATH As in the next step
cp ./bee  $GOPATH/bin
```

`bee pack -a=appAliasName`

**Comment by guhan121** [comment]
@xavierror  new version support app  AliasName .

**Comment by xavierror** [comment]
> @xavierror new version support app AliasName .

Thank you for all your assistance
