### ISSUE TITLE
bee  什么时候能够支持go mod

### ISSUE THREAD

**Issue by bayern0815** [beego/bee#640]
一些项目不想用gopath ,希望bee能够增加对go mod 的支持

**Comment by jeeyshe** [comment]
确实是的， 现在使用 go get 下载bee会出现问题

```
go: github.com/beego/bee imports
	github.com/beego/bee/cmd imports
	github.com/beego/bee/cmd/commands/dlv imports
	github.com/derekparker/delve/service: github.com/derekparker/delve@v1.3.2: parsing go.mod:
	module declares its path as: github.com/go-delve/delve
	        but was required as: github.com/derekparker/delve
```

**Comment by yanhao1** [comment]
什么时候解决一下呀！

**Comment by DennisMao** [comment]
@jeeyshe   @yanhao1    GO111MODULE=off go get

**Comment by zsboss** [comment]
> @jeeyshe @yanhao1 GO111MODULE=off go get

关闭GO111MODULE  还是一样的问题

**Comment by yuzhewo** [comment]
> 确实是的， 现在使用 go get 下载bee会出现问题
> 
> ```
> go: github.com/beego/bee imports
> 	github.com/beego/bee/cmd imports
> 	github.com/beego/bee/cmd/commands/dlv imports
> 	github.com/derekparker/delve/service: github.com/derekparker/delve@v1.3.2: parsing go.mod:
> 	module declares its path as: github.com/go-delve/delve
> 	        but was required as: github.com/derekparker/delve
> ```

这个问题如何解决？

**Comment by gadelkareem** [comment]
any updates on this?

**Comment by guhan121** [comment]
@bayern0815 @yanhao1 @yuzhewo 

```
replace  github.com/beego/bee  v1.10.1 ->  github.com/guhan121/bee v1.10.1
```

i fix some command for `go modules`

hope it is useful.

**Comment by guhan121** [comment]
#651
