### ISSUE TITLE
go mod环境下，在非gopath目录下运行bee run，runmode=dev无法自动生成commentsRouter_controllers.go

### ISSUE THREAD

**Issue by 3930615** [beego/bee#643]
#1 go mod环境
#2 同样一份代码，并且app.conf中runmode设置为dev
#3 将代码分别在GOPATH和非GOPATH下运行
结果是GOPATH下commentsRouter_controllers.go正常生成，非GOPATH下不生成

**Comment by guhan121** [comment]
这个是beego的问题

https://github.com/astaxie/beego/pull/3998

**Comment by guhan121** [comment]
也不知道谢大神什么时候有时间来修这些问题

**Comment by flycash** [comment]
这个问题应该算是修复，我已经把生成注解路由的功能挪过来了bee这里，可以通过参数来指定路径。

**Comment by jimashi** [comment]
> 这个问题应该算是修复，我已经把生成注解路由的功能挪过来了bee这里，可以通过参数来指定路径。

把beego注解路由生成的功能删除后，如果要使用注解路由的功能，只能使用bee工具生成打包代码了吗？如果代码使用了注解路由，直接用 go build 是不行了吗？

**Comment by flycash** [comment]
> > 这个问题应该算是修复，我已经把生成注解路由的功能挪过来了bee这里，可以通过参数来指定路径。
> 
> 把beego注解路由生成的功能删除后，如果要使用注解路由的功能，只能使用bee工具生成打包代码了吗？如果代码使用了注解路由，直接用 go build 是不行了吗？

嗯，你在开发阶段生成注解路由之后，就可以用go build的。开发阶段修改完注解，需要自己主动 bee generate 一下，我觉得这种方式，会给你们更好的控制感

**Comment by zenghnn** [comment]
有一说一，这个可太坑了

**Comment by YongMingMao** [comment]
兄弟，最后是怎么解决的？我的情况基本和你一样

**Comment by flycash** [comment]
你可以看一下bee命令的文档，大概是 bee generate route，然后传入你的源文件和目标文件，试一下就知道，很简单的

YongMingMao ***@***.***>于2022年2月28日 周一下午6:42写道：
