### ISSUE TITLE
GO 1.23.5 go get github.com/beego/bee ERROR

### ISSUE THREAD

**Issue by CoderXv** [beego/bee#648]
I set up beego environment with command `go get github.com/beego/bee` on MacOS Mojave then failed in this:

go: github.com/beego/bee imports
	github.com/beego/bee/cmd imports
	github.com/beego/bee/cmd/commands/dlv imports
	github.com/derekparker/delve/service: github.com/derekparker/delve@v1.4.0: parsing 
	module declares its path as: github.com/go-delve/delve
	        but was required as: github.com/derekparker/delve

Is there some pkg path changed? and how to solve it, thanks a lot. my go env:

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/local/Library/Caches/go-build"
GOENV="/Users/local/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/local/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/jc/km_cck5x0b39_xwgvcmqdnc00000gn/T/go-build204447358=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by DennisMao** [comment]
GO111MODULE=off  go get

**Comment by CoderXv** [comment]
> GO111MODULE=off go get
yes, my command is `export GO111MODULE=off && go get -u github.com/beego/bee`

**Comment by CoderXv** [comment]
> GO111MODULE=off go get

thanks alot
