### ISSUE TITLE
go get github.com/beego/bee 失败

### ISSUE THREAD

**Issue by zsboss** [beego/bee#651]
github.com/beego/bee imports
	github.com/beego/bee/cmd imports
	github.com/beego/bee/cmd/commands/dlv imports
	github.com/derekparker/delve/service: github.com/derekparker/delve@v1.4.0: parsing go.mod:
	module declares its path as: github.com/go-delve/delve
	        but was required as: github.com/derekparker/delve
src go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/boss/Library/Caches/go-build"
GOENV="/Users/boss/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zsb/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fl/7phg01l121s1kw5r62x5zssh0000gn/T/go-build626978598=/tmp/go-build -gno-record-gcc-switches -fno-common"

这种问题怎么解决呢？

**Comment by Vahanerevan** [comment]
+1

**Comment by zillani** [comment]
+1

**Comment by Wiidz** [comment]
+1

**Comment by aipame** [comment]
+1

**Comment by aipame** [comment]
http://www.678fly.cn/d/3-go-mod-bee 来这个已经解决 亲测可用

**Comment by guhan121** [comment]
#640

**Comment by XiaoWuCalvin** [comment]
确实会失败，我国内代理镜像也设置了就是么用

**Comment by flycash** [comment]
```
export GOPROXY=https://goproxy.cn
go get -u github.com/beego/bee/v2@master
```
