### ISSUE TITLE
swagger添加API认证,但是请求头没有添加Authorization

### ISSUE THREAD

**Issue by yangmingbai** [beego/bee#652]
在router中添加swagger注释
// @SecurityDefinition token apiKey Authorization header

swagger页面中配置了Authorization
但是curl时 header中并没有添加Authorization，仍然是以下内容：
curl -X GET "http://....../...../v1/object/" -H  "accept: application/json"

**Comment by Osub** [comment]
解决了吗？

**Comment by flycash** [comment]
没有，可以帮忙解决一下吗？
