### ISSUE TITLE
module declares its path as: github.com/go-delve/delve      but was required as: github.com/derekparker/delve

### ISSUE THREAD

**Issue by mrxlhm** [beego/bee#655]
**prerequisite**
OS:  MacBook-Air.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

**go env**
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/Work/go/bin"
GOCACHE="/Users/Work/Library/Caches/go-build"
GOENV="/Users/Work/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/Work/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hm/gkjrx7ws2lb3r30_b2lbmgf00000gn/T/go-build169987667=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Error**
go get github.com/beego/bee
go: downloading github.com/beego/bee v1.10.0
go: github.com/beego/bee upgrade => v1.10.0
go: finding module for package gopkg.in/yaml.v2
go: finding module for package github.com/astaxie/beego/swagger
go: finding module for package github.com/astaxie/beego/utils
go: finding module for package github.com/derekparker/delve/service/rpccommon
go: finding module for package github.com/derekparker/delve/service
go: finding module for package github.com/derekparker/delve/service/rpc2
go: finding module for package github.com/gorilla/websocket
go: finding module for package github.com/derekparker/delve/terminal
go: finding module for package github.com/fsnotify/fsnotify
go: finding module for package github.com/lib/pq
go: downloading github.com/astaxie/beego v1.12.1
go: finding module for package github.com/go-sql-driver/mysql
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/derekparker/delve v1.4.0
go: downloading github.com/lib/pq v1.4.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: found gopkg.in/yaml.v2 in gopkg.in/yaml.v2 v2.2.8
go: found github.com/astaxie/beego/swagger in github.com/astaxie/beego v1.12.1
go: found github.com/derekparker/delve/service in github.com/derekparker/delve v1.4.0
go: found github.com/fsnotify/fsnotify in github.com/fsnotify/fsnotify v1.4.9
go: found github.com/gorilla/websocket in github.com/gorilla/websocket v1.4.2
go: found github.com/go-sql-driver/mysql in github.com/go-sql-driver/mysql v1.5.0
go: found github.com/lib/pq in github.com/lib/pq v1.4.0
go: github.com/beego/bee imports
	github.com/beego/bee/cmd imports
	github.com/beego/bee/cmd/commands/dlv imports
	github.com/derekparker/delve/service: github.com/derekparker/delve@v1.4.0: parsing go.mod:
	module declares its path as: github.com/go-delve/delve
	        but was required as: github.com/derekparker/delve

**Comment by guhan121** [comment]
```
replace  github.com/beego/bee  v1.10.0 ->  github.com/guhan121/bee v1.10.1

**Comment by askuy** [comment]
support go mod
