### ISSUE TITLE
bee command not fount

### ISSUE THREAD

**Issue by Aaron630** [beego/bee#657]
bee command not fount....       %GOPATH%/bin No bee. Exe   ???

**Comment by qq734628996** [comment]
I had the same problem with win10. After I go get, I couldn't find bee.exe in %gopath%/bin.

**Comment by guhan121** [comment]
@Aaron630 @qq734628996 you can build it,and copy it to %gopath%/bin

**Comment by askuy** [comment]
use go version > 1.12
export GO111MODULE=on && go get -u github.com/beego/bee
