### ISSUE TITLE
Can not mapping pointer of primitive data type when parsing form request

### ISSUE THREAD

**Issue by taivtse** [beego/bee#659]
I get a problem when create a filter controller(GET method). 
I have a struct contains many field. This struct will mapped with query params on URL. 
That struct contains a field type bool.
The problem is: when user do not input this field, its default value is false -> its value the same with user select false, so It caused confusion.

Can I using *bool for that field, when user do not add it will be nil

Here is my beego version:
├── Beego     : 1.12.1
├── GoVersion : go1.13.10
├── GOOS      : darwin
├── GOARCH    : amd64

Thank you so much.

**Comment by guhan121** [comment]
this a  test 
```
// @router /:id [get]
func (c *Test1Controller) GetOne() {
	selectValue := c.Input().Get(`select`)
	logs.Info("[%v] ", selectValue)
	if selectValue == `true` {
		logs.Info(`set true`)
	} else if selectValue == `false` {
		logs.Info(`set false`)
	} else if selectValue == `` {
		logs.Info(`not select`)
	} else {
		logs.Info(`bad set`)
	}
	c.Data[`json`] = fmt.Sprintf(`[%v]`, c.Ctx.Input.Param(":id"))
	c.ServeJSON()
}

```
`http://127.0.0.1:18080/v1/test5/6?select=true ` =>
```
2020/05/26 17:51:41.676 [I] [controller.go:218]  [true] 
2020/05/26 17:51:41.676 [I] [controller.go:218]  set true
```

`http://127.0.0.1:18080/v1/test5/6?select=true1 ` =>
```
2020/05/26 17:53:12.365 [I] [controller.go:218]  [true1] 
2020/05/26 17:53:12.365 [I] [controller.go:218]  bad set
```


`http://127.0.0.1:18080/v1/test5/6` =>
```
2020/05/26 17:51:33.769 [I] [controller.go:218]  [] 
2020/05/26 17:51:33.769 [I] [controller.go:218]  not select
```

so, i  think   is useful.

**Comment by taivtse** [comment]
@guhan121 thank you so much.
