### ISSUE TITLE
bee run failed

### ISSUE THREAD

**Issue by xiaodaiit** [beego/bee#662]
2020/05/30 20:03:57 INFO     ▶ 0001 Using 'hello' as 'appname'
2020/05/30 20:03:57 INFO     ▶ 0002 Initializing watcher...
main.go:4:2: package hello/routers is not in GOROOT (/usr/local/go/src/hello/routers)
2020/05/30 20:03:57 ERROR    ▶ 0003 Failed to build the application: main.go:4:2: package hello/routers is not in GOROOT (/usr/local/go/src/hello/routers)

why?

**Comment by guhan121** [comment]
use `go mod`? v1.10.0 not support `go mod`

**Comment by guhan121** [comment]
@xiaodaiit 你们准备更新bee了么？
