### ISSUE TITLE
The command '/bin/sh -c go get github.com/beego/bee' returned a non-zero code: 2 

### ISSUE THREAD

**Issue by Anu-N-2** [beego/bee#667]
Getting this error when we run go get github.com/beego/bee command

RUN go get github.com/beego/bee
15:15:13  ---> Running in 6fe12e2fb303
15:15:33 [91m# github.com/beego/bee/cmd/commands/dlv
15:15:33 src/github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:151:3: unknown field 'AttachPid' in struct literal of type service.Config
15:15:33 src/github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:153:3: unknown field 'WorkingDir' in struct literal of type service.Config
15:15:33 src/github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:166:32: not enough arguments in call to client.Restart
15:15:33 	have ()
15:15:33 	want (bool)
15:15:33 [0mThe command '/bin/sh -c go get github.com/beego/bee' returned a non-zero code: 2

**Comment by askuy** [comment]
please use go version > 1.12
export GO111MODULE=on && go get github.com/beego/bee
