### ISSUE TITLE
go get github.com/beego/bee fails when using golang version 1.14

### ISSUE THREAD

**Issue by satvirgrewal** [beego/bee#668]
github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:151:3: unknown field 'AttachPid' in struct literal of type service.Config
github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:153:3: unknown field 'WorkingDir' in struct literal of type service.Config
github.com/beego/bee/cmd/commands/dlv/dlv_amd64.go:166:32: not enough arguments in call to client.Restart
        have ()
        want (bool)

**Code from dlv_amd64.go:**

![image](https://user-images.githubusercontent.com/21002217/85184447-726e0a80-b255-11ea-9e77-d47ded3c2c87.png)

**Issue:** It seems the dlv_amd64.go is trying to use some fields that don't exist in service.config as seen in the delve code below.

**Code from dlv_amd64.go:**
`type Config struct {
	// Debugger configuration object, used to configure the underlying
	// debugger used by the server.
	Debugger debugger.Config

	// Listener is used to serve requests.
	Listener net.Listener

	// ProcessArgs are the arguments to launch a new process.
	ProcessArgs []string

	// AcceptMulti configures the server to accept multiple connection.
	// Note that the server API is not reentrant and clients will have to coordinate.
	AcceptMulti bool

	// APIVersion selects which version of the API to serve (default: 1).
	APIVersion int

	// CheckLocalConnUser is true if the debugger should check that local
	// connections come from the same user that started the headless server
	CheckLocalConnUser bool

	// DisconnectChan will be closed by the server when the client disconnects
	DisconnectChan chan<- struct{}
}`

Because of unresolved dependency the beego package doesnt compile and as a result, nobody is able to do **go get github.com/beego/bee**

**Comment by satvirgrewal** [comment]
It is still not working.

The error has changed now:
`github.com/gadelkareem/delve/service/debugger
../../github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/rpccommon
../../github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/siru`

Please check

**Comment by askuy** [comment]
> It is still not working.
> 
> The error has changed now:
> `github.com/gadelkareem/delve/service/debugger
> ../../github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
> 
> # github.com/gadelkareem/delve/service/rpccommon
> ../../github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/siru`
> 
> Please check

you not use go mod, I find vendor filefolder
please use go version > 1.12
export GO111MODULE = on && go  get github.com/beego/bee

**Comment by satvirgrewal** [comment]
Thanks @askuy it worked.

**Comment by sysujerome** [comment]
Hi, I meet the same quetion as yours. I cannot understand the solution of @askuy .Could you share how to fix it?
![image](https://user-images.githubusercontent.com/37723367/86011665-8ed92680-ba4f-11ea-9505-e7e3a12f7cd2.png)

**Comment by tqdo** [comment]
I have the same problem and I am using Go 1.14.4, which is >1.12 and still has the same problem. @askuy Could you clarify your answer? I also don't quite get it. Thanks

**Comment by khanzadimahdi** [comment]
@tqdo 

run the below command in terminal

```bash
GO111MODULE=on go get github.com/beego/bee
```

**Comment by wangshuzheng** [comment]
@sysujerome  your commend need export GO111MODULE=on && go get github.com/beego/bee
so export between key / = and value with no  Space(" ")

**Comment by sysujerome** [comment]
> @sysujerome your commend need export GO111MODULE=on && go get github.com/beego/bee
> so export between key / = and value with no Space(" ")

It worked! Thank you!
