### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by tj297202234** [beego/bee#672]
# github.com/beego/bee/cmd/commands/dlv
D:\go\src\github.com\beego\bee\cmd\commands\dlv\dlv_amd64.go:151:3: unknown field 'AttachPid' in struct literal of type service.Config
D:\go\src\github.com\beego\bee\cmd\commands\dlv\dlv_amd64.go:153:3: unknown field 'WorkingDir' in struct literal of type service.Config
D:\go\src\github.com\beego\bee\cmd\commands\dlv\dlv_amd64.go:166:32: not enough arguments in call to client.Restart
        have ()
        want (bool)

**Comment by simonqiang** [comment]
I had the same issue.

**Comment by yitea** [comment]
use go version  > 1.12
go get github.com/beego/bee

**Comment by askuy** [comment]
> # github.com/beego/bee/cmd/commands/dlv
> D:\go\src\github.com\beego\bee\cmd\commands\dlv\dlv_amd64.go:151:3: unknown field 'AttachPid' in struct literal of type service.Config
> D:\go\src\github.com\beego\bee\cmd\commands\dlv\dlv_amd64.go:153:3: unknown field 'WorkingDir' in struct literal of type service.Config
> D:\go\src\github.com\beego\bee\cmd\commands\dlv\dlv_amd64.go:166:32: not enough arguments in call to client.Restart
> have ()
> want (bool)

use go version > 1.12
go get github.com/beego/bee
