### ISSUE TITLE
Error not enough arguments in call to client.Restart

### ISSUE THREAD

**Issue by zafer06** [beego/bee#673]
https://github.com/beego/bee/blob/8ebb7977f94c7a476d77355b97a28c6ac6458ca9/cmd/commands/dlv/dlv_amd64.go#L170

Above line get error "not enough arguments in call to client.Restart"

**Comment by askuy** [comment]
please let go version > 1.12, execute the following command
exprot GO111MODULE=on && go get github.com/beego/bee
