### ISSUE TITLE
Dependency: "github.com/go-delve/delve/pkg/terminal" error

### ISSUE THREAD

**Issue by A1311981684** [beego/bee#675]
I use go get -u to install bee, but it reports this:
# github.com/go-delve/delve/pkg/terminal
..\..\..\..\pkg\mod\github.com\go-delve\delve@v1.4.1\pkg\terminal\command.go:1045:28: cannot use ([]rune)(args) (type []rune) as type string in arg
ument to argv.Argv
..\..\..\..\pkg\mod\github.com\go-delve\delve@v1.4.1\pkg\terminal\command.go:1045:36: undefined: argv.ParseEnv
..\..\..\..\pkg\mod\github.com\go-delve\delve@v1.4.1\pkg\terminal\command.go:1046:3: cannot use func literal (type func([]rune, map[string]string)
([]rune, error)) as type argv.Expander in argument to argv.Argv

**Comment by anoymouscoder** [comment]
I have encountered similar problems:
I just build docker with Dockerfile
```bash
FROM library/golang

# Godep for vendoring
RUN go get github.com/tools/godep

# Recompile the standard library without CGO
RUN CGO_ENABLED=0 go install -a std

ENV APP_DIR $GOPATH/src/poseidon
RUN mkdir -p $APP_DIR

ADD . $APP_DIR
WORKDIR $APP_DIR

# Compile the binary and statically link
RUN godep get && CGO_ENABLED=0 godep go build -ldflags '-w -s'
RUN go get -u github.com/astaxie/beego && go get github.com/beego/bee
```
but build failed with error
```bash
# github.com/gadelkareem/delve/service/debugger
84../github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
85# github.com/gadelkareem/delve/service/rpccommon
86../github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
87The command '/bin/sh -c go get -u github.com/astaxie/beego && go get github.com/beego/bee' returned a non-zero code: 2
88{"exitCode":8, "message":"docker build failed or timeout[2]"}
```

**Comment by HikaruHe** [comment]
> I have encountered similar problems:
> I just build docker with Dockerfile
> 
> ```shell
> FROM library/golang
> 
> # Godep for vendoring
> RUN go get github.com/tools/godep
> 
> # Recompile the standard library without CGO
> RUN CGO_ENABLED=0 go install -a std
> 
> ENV APP_DIR $GOPATH/src/poseidon
> RUN mkdir -p $APP_DIR
> 
> ADD . $APP_DIR
> WORKDIR $APP_DIR
> 
> # Compile the binary and statically link
> RUN godep get && CGO_ENABLED=0 godep go build -ldflags '-w -s'
> RUN go get -u github.com/astaxie/beego && go get github.com/beego/bee
> ```
> 
> but build failed with error
> 
> ```shell
> # github.com/gadelkareem/delve/service/debugger
> 84../github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
> 85# github.com/gadelkareem/delve/service/rpccommon
> 86../github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
> 87The command '/bin/sh -c go get -u github.com/astaxie/beego && go get github.com/beego/bee' returned a non-zero code: 2
> 88{"exitCode":8, "message":"docker build failed or timeout[2]"}
> ```

I encountered the same problem，any way to solve it??

**Comment by diagutierrezro** [comment]
> I have encountered similar problems:
> I just build docker with Dockerfile
> 
> ```shell
> FROM library/golang
> 
> # Godep for vendoring
> RUN go get github.com/tools/godep
> 
> # Recompile the standard library without CGO
> RUN CGO_ENABLED=0 go install -a std
> 
> ENV APP_DIR $GOPATH/src/poseidon
> RUN mkdir -p $APP_DIR
> 
> ADD . $APP_DIR
> WORKDIR $APP_DIR
> 
> # Compile the binary and statically link
> RUN godep get && CGO_ENABLED=0 godep go build -ldflags '-w -s'
> RUN go get -u github.com/astaxie/beego && go get github.com/beego/bee
> ```
> 
> but build failed with error
> 
> ```shell
> # github.com/gadelkareem/delve/service/debugger
> 84../github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
> 85# github.com/gadelkareem/delve/service/rpccommon
> 86../github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
> 87The command '/bin/sh -c go get -u github.com/astaxie/beego && go get github.com/beego/bee' returned a non-zero code: 2
> 88{"exitCode":8, "message":"docker build failed or timeout[2]"}
> ```
Everything seems to indicate that it is something of the new update, I used a project that I already had with docker and when I dockerized it again (without making any changes) I had the same error.

**Comment by ducnt114** [comment]
I think this commit causes the problem: https://github.com/beego/bee/commit/1334a998108bf090430ab58ab8056241f8a5ad66

It changed imported lib from `github.com/go-delve/delve` to `github.com/gadelkareem/delve`

**Comment by askuy** [comment]
> I think this commit causes the problem: [1334a99](https://github.com/beego/bee/commit/1334a998108bf090430ab58ab8056241f8a5ad66)
> 
> It changed imported lib from `github.com/go-delve/delve` to `github.com/gadelkareem/delve`

please use go get github.com/beego/bee or go get -u github.com/beego/bee@develop
https://github.com/go-delve/delve/pull/2088 causes this problem
We will solve this problem as soon as possible

**Comment by tuleminh** [comment]
Currently I have used to `go get github.com/beego/bee`, but still get the errors @askuy :
```
# github.com/gadelkareem/delve/service/debugger
src/github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value

# github.com/gadelkareem/delve/service/rpccommon
 src/github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
```
