### ISSUE TITLE
Error when docker compose build

### ISSUE THREAD

**Issue by cyc1e** [beego/bee#678]
**got such an error today:**

Building backend_app
Step 1/13 : FROM golang:1.14.3-alpine3.11
 ---> 459ae5e869df
Step 2/13 : RUN apk add --no-cache git mercurial
 ---> Using cache
 ---> c5a5415ae5b5
Step 3/13 : ARG app_name=app
 ---> Using cache
 ---> a8430db2bec6
Step 4/13 : ARG http_port=8080
 ---> Using cache
 ---> fa00df1911e1
Step 5/13 : ARG https_port=10443
 ---> Using cache
 ---> 64a28be7773a
Step 6/13 : RUN go get -u github.com/astaxie/beego
 ---> Using cache
 ---> a561121a7157
Step 7/13 : RUN go get -u github.com/beego/bee
 ---> Running in 50a5afdb8bb4
-# github.com/gadelkareem/delve/service/debugger
src/github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
-# github.com/gadelkareem/delve/service/rpccommon
src/github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type ---------*"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
ERROR: Service 'backend_app' failed to build: The command '/bin/sh -c go get -u github.com/beego/bee' returned a non-zero code: 2

**my dockerfile** :

FROM golang:1.14.3-alpine3.11
RUN apk add --no-cache git mercurial
-# ENV GOPATH /go
-# Install beego & bee

-# ENV GOPATH /go

ARG app_name=app
ARG http_port=8080
ARG https_port=10443

-# Install beego & bee
RUN go get -u github.com/astaxie/beego
RUN go get -u github.com/beego/bee

-# Expose port to public
EXPOSE $http_port
EXPOSE $https_port

-# Copy the source code from current directory to /go/src in container
-# Place the Dockerfile into source code directory and build Docker image
RUN mkdir -p /go/src/$app_name
COPY . /go/src/$app_name
WORKDIR /go/src/$app_name

-# Launch Beego when the container is created
CMD bee run

**Comment by harikuttan** [comment]
**I am also facing the same issue.**
Status: Downloaded newer image for golang:1.12
 ---> ffcaee6f7d8b
Step 2/5 : RUN mkdir -p /go/src/nordsud/api
 ---> Running in 26b7b8646296
Removing intermediate container 26b7b8646296
 ---> c4d13f139073
Step 3/5 : WORKDIR /go/src/nordsud/api
 ---> Running in 799c82bd2993
Removing intermediate container 799c82bd2993
 ---> 20e966c541cf
Step 4/5 : RUN go get github.com/astaxie/beego
 ---> Running in 0b1589b65bcb
 Removing intermediate container 0b1589b65bcb
 ---> df6a5af89e25
Step 5/5 : RUN go get -u github.com/beego/bee
 ---> Running in dbe7bd9fd72a
# github.com/gadelkareem/delve/service/debugger
../../github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/rpccommon
../../github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
ERROR: Service 'sewnapi' failed to build: The command '/bin/sh -c go get -u github.com/beego/bee' returned a non-zero code: 2

Tried with different versions go

**Comment by askuy** [comment]
please let go version > 1.12, execute the following command
exprot GO111MODULE=on && go get github.com/beego/bee
