### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by evgeniispirin** [beego/bee#679]
`$ go get github.com/beego/bee`

Error:
github.com/gadelkareem/delve/service/debugger
../github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
github.com/gadelkareem/delve/service/rpccommon
../github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value

`$ go version`

go version go1.14.3 darwin/amd64

**Comment by askuy** [comment]
please use go version > 1.12
export GO111MODULE=on && go get -u github.com/beego/bee

**Comment by chandraaditya** [comment]
I have go1.14.4 darwin/amd64 but even then it's not working

**Comment by gupf0719** [comment]
go version go1.14.4 darwin/amd64

# github.com/gadelkareem/delve/service/rpccommon
programming/go/src/github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/debugger
programming/go/src/github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
gupengfei@MacBook-Pro ~ % go get -u github.com/beego/bee
# cd /Users/gupengfei/programming/go/src/golang.org/x/sys; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/sys/': Received HTTP code 503 from proxy after CONNECT

**Comment by canrofeather** [comment]
I have the same issue as the upstair. how to solve this?

**Comment by chandraaditya** [comment]
Set environment variable GO111MODULE to on

**Comment by 523013796** [comment]
添加环境变量：
$ export GO111MODULE=on
$ export GOPROXY=https://goproxy.io
