### ISSUE TITLE
go.mod issue in bee new

### ISSUE THREAD

**Issue by xin344** [beego/bee#680]
When use "bee new", it creates a new project folder in src, I think it should also touch a go.mod file in the project folder to prevent the error:
go: cannot find main module; see 'go help modules'

I solve this problem with "touch go.mod" in the project folder.

**Comment by askuy** [comment]
do you want to make pr?

**Comment by xin344** [comment]
> do you want to make pr?

I am so sorry,
I am a new golang user, I am not able to make a PR, so I can just solve this by "touch go.mod" in shell.
I wish I can make PR in days later.

**Comment by guhan121** [comment]
@askuy 啥时候合我的PR啊 https://github.com/beego/bee/pull/674#issue-437665362

**Comment by askuy** [comment]
> @askuy 啥时候合我的PR啊 [#674 (comment)](https://github.com/beego/bee/pull/674#issue-437665362)

merged
