### ISSUE TITLE
{ bee } 下-无法使用记录器 

### ISSUE THREAD

**Issue by continent-001** [beego/bee#682]
中文
github.com网站\gadelkareem\delve\service\debugger公司\调试器。go:129：3:无法使用记录器（类型*“github.com/go-delve/delve/供应商/github.com/sirupsen/logrus“.Entry）作为类型*”github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus“。输入字段值

English

$ go get -u github.com/beego/bee
# github.com/gadelkareem/delve/service/rpccommon
D:\Go\go_1\src\github.com\gadelkareem\delve\service\rpccommon\server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value

# github.com/gadelkareem/delve/service/debugger
D:\Go\go_1\src\github.com\gadelkareem\delve\service\debugger\debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value

At present, I don't know what the problem is. Please help solve it. Thank you

**Comment by sysujerome** [comment]
I meet the same quetion at win10 and linux sub system at the same time.
![image](https://user-images.githubusercontent.com/37723367/86008476-6fd89580-ba4b-11ea-8499-f39c1b5eb204.png)
![image](https://user-images.githubusercontent.com/37723367/86008564-8979dd00-ba4b-11ea-9505-d114e519c43c.png)

**Comment by einsli** [comment]
I upgrade go's version to 1.14.4 on the platform of MacOS and run the following command to install the bee and encountered the same problems.
 The command is get -u github.com/beego/bee
![image](https://user-images.githubusercontent.com/37534114/86267172-e961b680-bbf8-11ea-9db1-376c232ef0f0.png)

**Comment by sysujerome** [comment]
MayBe you can try these command:&nbsp;&nbsp;
export GO111MODULE=on;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
export GOPROXY=https://goproxy.io
get -u github.com/beego/bee

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"弘树"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 凌晨0:14
收件人:&nbsp;"beego/bee"<bee@noreply.github.com&gt;;
抄送:&nbsp;"1570992296"<1570992296@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [beego/bee] { bee } 下-无法使用记录器  (#682)





 
I upgrade go's version to 1.14.4 on the platform of MacOS and run the following command to install the bee and encountered the same problems.
 The command is get -u github.com/beego/bee

**Comment by einsli** [comment]
> get -u github.com/beego/bee

Yes, In the platform of MacOS, following the instructions of master sysujerome it works!
The correct method to install the bee is with go's version 1.14.4:
$ export GO111MODULE=on
$  export GOPROXY=https://goproxy.io
$ get -u github.com/beego/bee

when the tool downloads completed, you are supposed to run the command to copy the binary file bee to $GOROOT/bin, otherwise when you type bee on the terminal, you can get following output 
command not found: bee
so just run the command to copy bee to $GOROOT/bin

$ cp $GOBIN/bee  $GOROOT/bin (NOTE if you have not configured the GOBIN, just run the command export GOBIN=$GOPATH/bin)

Finally, it works!

**Comment by IamCathal** [comment]
I am also experiencing this problem on go 1.13.4. Is there any other fix for this issue apart from inputting those commands? I'm not quite sure if theres a knock on effect with those when working on other projects @einsli

**Comment by DenOlijf** [comment]
> MayBe you can try these command: export GO111MODULE=on; export GOPROXY=https://goproxy.io get -u github.com/beego/bee &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"弘树"<notifications@github.com&gt;; 发送时间:&nbsp;2020年7月2日(星期四) 凌晨0:14 收件人:&nbsp;"beego/bee"<bee@noreply.github.com&gt;; 抄送:&nbsp;"1570992296"<1570992296@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [beego/bee] { bee } 下-无法使用记录器 (#682) I upgrade go's version to 1.14.4 on the platform of MacOS and run the following command to install the bee and encountered the same problems. The command is get -u github.com/beego/bee — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Solution also works for go 1.13.8, bee version 1.12.0 succesfully installed.
