### ISSUE TITLE
Need an option to include files when `bee pack`

### ISSUE THREAD

**Issue by fandayrockworld** [beego/bee#684]
There are 3 options to exclude files when `bee pack`(`-exp -exr -exs`), but no one option to include files. I think it is necessary to add an include option.

**Comment by flycash** [comment]
When you run the command, all go files under the project will be packed so we just need `exclude` option. 

I can not imagine the scene that we need the `include` option

**Comment by noroot777** [comment]
> I can not imagine the scene that we need the include option

If there're hug number of files, but I just want to include one file.
