### ISSUE TITLE
How install Bee on windows

### ISSUE THREAD

**Issue by zanisis** [beego/bee#685]
this my go env

> set GO111MODULE=
> set GOARCH=amd64
> set GOBIN=
> set GOCACHE=C:\Users\Az\AppData\Local\go-build
> set GOENV=C:\Users\Az\AppData\Roaming\go\env
> set GOEXE=.exe
> set GOFLAGS=
> set GOHOSTARCH=amd64
> set GOHOSTOS=windows
> set GOINSECURE=
> set GONOPROXY=
> set GONOSUMDB=
> set GOOS=windows
> set GOPATH=F:\gocode
> set GOPRIVATE=
> set GOPROXY=https://proxy.golang.org,direct
> set GOROOT=c:\go
> set GOSUMDB=sum.golang.org
> set GOTMPDIR=
> set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
> set GCCGO=gccgo
> set AR=ar
> set CC=gcc
> set CXX=g++
> set CGO_ENABLED=1
> set GOMOD=
> set CGO_CFLAGS=-g -O2
> set CGO_CPPFLAGS=
> set CGO_CXXFLAGS=-g -O2
> set CGO_FFLAGS=-g -O2
> set CGO_LDFLAGS=-g -O2
> set PKG_CONFIG=pkg-config
> set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Az\AppData\Local\Temp\go-build271140554=/tmp/go-build -gno-record-gcc-switches

when i install go get github.com/beego/bee
i have note like below. so i can get bee.exe on go/bin

# github.com/gadelkareem/delve/service/debugger
F:\gocode\src\github.com\gadelkareem\delve\service\debugger\debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/rpccommon
F:\gocode\src\github.com\gadelkareem\delve\service\rpccommon\server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value

**Comment by septiyanmudhiya502** [comment]
run go env -w GO111MODULE=on in your terminal
