### ISSUE TITLE
使用bee run时，常常遇到下面的情况

### ISSUE THREAD

**Issue by yangqinjiang** [beego/bee#686]
1，每当修改代码时， bee热重启，有时候却重启失败， 说有另一个exe文件在运行，这个exe文件就是在下面的图片内的文件夹内

2，在系统的temp目录下生成一大堆 exe的目录，但bee又不自动删除,造成系统盘容量暴减

![QQ五笔截图未命名](https://user-images.githubusercontent.com/1914373/87212639-2e50c000-c352-11ea-8716-0a511b1853b4.png)

说实话， 这个bee有不少的坑 ：）

**Comment by flycash** [comment]
这个应该算是beego的问题。本质上是beego在执行热重启的时候生成的这些文件，可以去beego提一下这个issue么？后面我们看看怎么解决……不过……目前看来，我一时半会难以复现这个问题

**Comment by flycash** [comment]
无法复现=。=
