### ISSUE TITLE
can not get bee.

### ISSUE THREAD

**Issue by weidongbcn** [beego/bee#688]
go get github.com/beego/bee
# github.com/gadelkareem/delve/service/rpccommon
../go/src/github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/debugger
../go/src/github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value

**Comment by guhan121** [comment]
```
export GO111MODULE=on
go get github.com/beego/bee
```
try it
