### ISSUE TITLE
bak file err

### ISSUE THREAD

**Issue by wangle201210** [beego/bee#693]
In windows the path of bak file is error

**Comment by windzhu** [comment]
2020/07/29 13:46:27 INFO     ▶ 0001 Create C:\Users\Administrator\.beego/beego-pro Success!
2020/07/29 13:46:27 INFO     ▶ 0002 git pull C:\Users\Administrator\.beego\beego-pro
2020/07/29 13:46:29 INFO     ▶ 0003 Using 'blog' as name
2020/07/29 13:46:29 INFO     ▶ 0004 Using 'blog' as package name from controllers
2020/07/29 13:46:29 INFO     ▶ 0005 bak file './bak/E:\MyWorks\gomod\admin\beego\beeblog\controllers\bee_default_controller.go.2020.07.29.13.46.29.bak'
2020/07/29 13:46:29 FATAL    ▶ 0006 Could not create file: file is bak error, path is ./bak/E:\MyWorks\gomod\admin\beego\beeblog\controllers\bee_default_controller.go.2020.07.29.13.46.29.bak

**Comment by wangle201210** [comment]
#707
