### ISSUE TITLE
使用bee工具遇到两个问题：

### ISSUE THREAD

**Issue by AllenX2018** [beego/bee#704]
1：使用命令 bee api demo1 和  bee new demo2， 管理包方式不一样，一个用gopath、另一个是mod，这一点能否统一？
2：目前发行版本是1.12.0，更新到最新版本，输入：bee  version ；还是显示：1.11.0，这个变量或常量需要保持一致；

**Comment by wangle201210** [comment]
问题二的话已经修改了，等合并pr后就能修复
