### ISSUE TITLE
bee install error

### ISSUE THREAD

**Issue by toplinuxsir** [beego/bee#716]
with go 1.15 newest version : 
go get -u github.com/beego/bee
# github.com/gadelkareem/delve/service/rpccommon
/data1/soft/go/go1.15/gopath/src/github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/debugger
/data1/soft/go/go1.15/gopath/src/github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value

**Comment by softwhole** [comment]
hi, try to run this command from your shell,

export GO111MODULE=on && go get -u github.com/beego/bee
cd $GOPATH/src/github.com/beego/bee
make install

**Comment by toplinuxsir** [comment]
@softwhole 
Thanks , it works !

**Comment by herdiansc** [comment]
> hi, try to run this command from your shell,
> 
> export GO111MODULE=on && go get -u github.com/beego/bee
> cd $GOPATH/src/github.com/beego/bee
> make install

It works. On my env, it's without `make install`

**Comment by kushalhalder** [comment]
The `make install` is important. Otherwise, I was stuck with `GO111MODULE=on` as a prefix for all the go commands. Things went really messy without the `make`!!!
