### ISSUE TITLE
"go get github.com/com/beego/bee" failed

### ISSUE THREAD

**Issue by stevechan1993** [beego/bee#717]
```
# github.com/gadelkareem/delve/service/debugger
Golang/src/github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/rpccommon
Golang/src/github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
```

**Comment by ashfaqahmed** [comment]
Same here

``` github.com/gadelkareem/delve/service/rpccommon
../github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
```

```
# github.com/gadelkareem/delve/service/debugger
../github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value

```

**Comment by ashfaqahmed** [comment]
I got it working by download from git repo and installing it manually from the source.

**Comment by sanzhikee** [comment]
Same here

# github.com/gadelkareem/delve/service/debugger
../github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/rpccommon
../github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value

**Comment by wangle201210** [comment]
change go env
```bash
set GO111MODULE=on
set GOPROXY=https://goproxy.io
```
and try again

**Comment by wuxiangzhou2010** [comment]
same issue , reproduced on macOS 10.15.6.

**Comment by wangle201210** [comment]
> same issue , reproduced on macOS 10.15.6.

show me the "go env"

**Comment by wuxiangzhou2010** [comment]
Thanks, I notice the mistake
 `export`  should be used on a nix system, it works fine

```sh
export GO111MODULE=on
export  GOPROXY=https://goproxy.io
```

**Comment by jakalky** [comment]
> change go env
> 
> ```shell
> set GO111MODULE=on
> set GOPROXY=https://goproxy.io
> ```
> 
> and try again

Good. This fix the issue. Thanks.

**Comment by gaurav-sardana** [comment]
But unable to use bee commands 
Getting error : `zsh: command not found: bee`
