### ISSUE TITLE
bee version 问题

### ISSUE THREAD

**Issue by zhangbest5** [beego/bee#721]
菜鸟一枚，高手别嫌弃哈
刚
```
go get github.com/astaxie/beego
go get github.com/beego/bee
bee version
```
显示结果
```
PS C:\Users\Administrator> bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.11.0

├── Beego     : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego
├── GoVersion : go1.15
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : C:\Users\Administrator\go
├── GOROOT    : c:\go
├── Compiler  : gc
└── Date      : Monday, 14 Sep 2020
```
两点问题
1.我下载的不是1.12么？ v1.11.0是 忘记改了么？
2.Date      : Monday, 14 Sep 2020 这怎么今天日期，不该是发布日期吗？

**Comment by wangle201210** [comment]
版本号在dev分支修复了的，暂时没有合并到master来
Date 那里的确就是想打印当前日期
![image](https://user-images.githubusercontent.com/19949348/93072099-876f0400-f6b3-11ea-952f-caa1bbff411c.png)

**Comment by zhangbest5** [comment]
感谢大佬指点，建议有个发布日期~

**Comment by wangle201210** [comment]
可以再下个小版本的时候加上哈

**Comment by wangle201210** [comment]
#719   
已添加，待合并

**Comment by lvzhenchao** [comment]
├── Beego     : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego
安装了beego 出现这个提示是什么原因呢，大佬？

**Comment by Sankin0410** [comment]
> ├── Beego : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego
> 安装了beego 出现这个提示是什么原因呢，大佬？

我也是这个问题，我明明都装了，GOPATH和GOROOT路径下都有这个包了，还是报错:(
