### ISSUE TITLE
Error cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type 

### ISSUE THREAD

**Issue by ludwinggsanchez** [beego/bee#722]
Getting this error when running go get github.com/beego/bee command

# github.com/gadelkareem/delve/service/rpccommon
C:\go-workspace\src\github.com\gadelkareem\delve\service\rpccommon\server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/rpc2
C:\go-workspace\src\github.com\gadelkareem\delve\service\rpc2\client.go:23:5: cannot use &RPCClient literal (type *RPCClient) as type service.Client in assignment:
        *RPCClient does not implement service.Client (wrong type for ExamineMemory method)
                have ExamineMemory(uintptr, int) ([]byte, error)
                want ExamineMemory(uint64, int) ([]byte, bool, error)

**Comment by sivarajp** [comment]
Try setting set GO111MODULE=on before running. it fixed the issue for me.

**Comment by ami-m** [comment]
same

**Comment by ludwinggsanchez** [comment]
Thank you, it worked.
