### ISSUE TITLE
无法安装bee

### ISSUE THREAD

**Issue by pppscn** [beego/bee#727]
**Describe the bug**

`# github.com/gadelkareem/delve/service/rpc2
src/github.com/gadelkareem/delve/service/rpc2/client.go:23:5: cannot use &RPCClient literal (type *RPCClient) as type service.Client in assignment:
	*RPCClient does not implement service.Client (wrong type for ExamineMemory method)
		have ExamineMemory(uintptr, int) ([]byte, error)
		want ExamineMemory(uint64, int) ([]byte, bool, error)
src/github.com/gadelkareem/delve/service/rpc2/server.go:96:52: not enough arguments in call to s.debugger.Restart
	have (bool, string, bool, []string, bool)
	want (bool, string, bool, []string, [3]string, bool)
src/github.com/gadelkareem/delve/service/rpc2/server.go:190:21: cannot assign []proc.Stackframe to out.Locations (type []api.Stackframe) in multiple assignment
src/github.com/gadelkareem/delve/service/rpc2/server.go:190:44: too many arguments in call to s.debugger.Stacktrace
	have (int, int, api.StacktraceOptions, *proc.LoadConfig)
	want (int, int, api.StacktraceOptions)
src/github.com/gadelkareem/delve/service/rpc2/server.go:321:19: cannot assign []proc.Thread to out.Threads (type []*api.Thread) in multiple assignment
src/github.com/gadelkareem/delve/service/rpc2/server.go:342:13: cannot use t (type proc.Thread) as type *api.Thread in assignment
src/github.com/gadelkareem/delve/service/rpc2/server.go:367:42: too many arguments in call to s.debugger.PackageVariables
	have (int, string, proc.LoadConfig)
	want (string, proc.LoadConfig)
src/github.com/gadelkareem/delve/service/rpc2/server.go:371:16: cannot use vars (type []*proc.Variable) as type []api.Variable in assignment
src/github.com/gadelkareem/delve/service/rpc2/server.go:398:25: s.debugger.Registers undefined (type *debugger.Debugger has no field or method Registers)
src/github.com/gadelkareem/delve/service/rpc2/server.go:419:40: not enough arguments in call to s.debugger.LocalVariables
	have (api.EvalScope, proc.LoadConfig)
	want (int, int, int, proc.LoadConfig)
src/github.com/gadelkareem/delve/service/rpc2/server.go:419:40: too many errors
# github.com/gadelkareem/delve/service/rpccommon
src/github.com/gadelkareem/delve/service/rpccommon/server.go:83:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
# github.com/gadelkareem/delve/service/debugger
src/github.com/gadelkareem/delve/service/debugger/debugger.go:129:3: cannot use logger (type *"github.com/go-delve/delve/vendor/github.com/sirupsen/logrus".Entry) as type *"github.com/gadelkareem/delve/vendor/github.com/sirupsen/logrus".Entry in field value
src/github.com/gadelkareem/delve/service/debugger/debugger.go:224:23: not enough arguments in call to native.Launch
	have ([]string, string, bool, []string, string)
	want ([]string, string, proc.LaunchFlags, []string, string, [3]string)
src/github.com/gadelkareem/delve/service/debugger/debugger.go:226:57: not enough arguments in call to gdbserial.LLDBLaunch
	have ([]string, string, bool, []string, string)
	want ([]string, string, proc.LaunchFlags, []string, string, [3]string)
src/github.com/gadelkareem/delve/service/debugger/debugger.go:233:42: not enough arguments in call to gdbserial.RecordAsync
	have ([]string, string, bool)
	want ([]string, string, bool, [3]string)
src/github.com/gadelkareem/delve/service/debugger/debugger.go:268:58: not enough arguments in call to gdbserial.LLDBLaunch
	have ([]string, string, bool, []string, string)
	want ([]string, string, proc.LaunchFlags, []string, string, [3]string)
src/github.com/gadelkareem/delve/service/debugger/debugger.go:270:23: not enough arguments in call to native.Launch
	have ([]string, string, bool, []string, string)
	want ([]string, string, proc.LaunchFlags, []string, string, [3]string)
src/github.com/gadelkareem/delve/service/debugger/debugger.go:463:43: not enough arguments in call to gdbserial.RecordAsync
	have ([]string, string, bool)
	want ([]string, string, bool, [3]string)
src/github.com/gadelkareem/delve/service/debugger/debugger.go:1210:27: cannot use dregs (type op.DwarfRegisters) as type *op.DwarfRegisters in argument to api.ConvertRegisters
src/github.com/gadelkareem/delve/service/debugger/debugger.go:1210:53: cannot use d.target.Process.BinInfo().Arch (type *proc.Arch) as type func(int, *op.DwarfRegister) (string, bool, string) in argument to api.ConvertRegisters
src/github.com/gadelkareem/delve/service/debugger/debugger.go:1575:10: undefined: api.ConvertCheckpoint
src/github.com/gadelkareem/delve/service/debugger/debugger.go:1575:10: too many errors
# github.com/gadelkareem/delve/pkg/terminal
src/github.com/gadelkareem/delve/pkg/terminal/command.go:1032:40: not enough arguments in call to t.client.RestartFrom
	have (bool, string, bool, []string, bool)
	want (bool, string, bool, []string, [3]string, bool)
src/github.com/gadelkareem/delve/pkg/terminal/command.go:1575:15: assignment mismatch: 2 variables but t.client.ExamineMemory returns 3 values
src/github.com/gadelkareem/delve/pkg/terminal/command.go:1575:48: cannot use uintptr(address) (type uintptr) as type uint64 in argument to t.client.ExamineMemory
src/github.com/gadelkareem/delve/pkg/terminal/command.go:1580:35: not enough arguments in call to api.PrettyExamineMemory
`

**To Reproduce**
`go get github.com/beego/bee`

**Versions**
 - go: go version go1.15.2 linux/amd64
 - operating system: CentOS Linux release 7.8.2003 (Core)

**Comment by flycash** [comment]
What about running `go get -u github.com/beego/bee`

**Comment by pppscn** [comment]
thx

[root@microservice ~]#go get -u github.com/beego/bee

go: github.com/beego/bee upgrade => v1.12.0
go: github.com/spf13/pflag upgrade => v1.0.5
go: github.com/pelletier/go-toml upgrade => v1.8.1
go: github.com/peterh/liner upgrade => v1.2.0
go: github.com/astaxie/beego upgrade => v1.12.2
go: gopkg.in/ini.v1 upgrade => v1.62.0
go: github.com/spf13/cast upgrade => v1.3.1
go: github.com/flosch/pongo2 upgrade => v0.0.0-20200805083417-63c99409991d
go: golang.org/x/text upgrade => v0.3.3
go: golang.org/x/arch upgrade => v0.0.0-20201008161808-52c3e6f60cff
go: github.com/mitchellh/mapstructure upgrade => v1.3.3
go: go.starlark.net upgrade => v0.0.0-20201014215153-dff0ae5b4820
go: github.com/mattn/go-colorable upgrade => v0.1.8
go: github.com/spf13/jwalterweatherman upgrade => v1.1.0
go: github.com/lib/pq upgrade => v1.8.0
go: github.com/hashicorp/golang-lru upgrade => v0.5.4
go: gopkg.in/yaml.v2 upgrade => v2.3.0
go: golang.org/x/sys upgrade => v0.0.0-20201022201747-fb209a7c41cd
go: github.com/spf13/afero upgrade => v1.4.1
go: github.com/fsnotify/fsnotify upgrade => v1.4.9
go: github.com/sirupsen/logrus upgrade => v1.7.0
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/spf13/viper upgrade => v1.7.1
go: github.com/magiconair/properties upgrade => v1.8.4
go: github.com/davecgh/go-spew upgrade => v1.1.1
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
go: github.com/go-sql-driver/mysql upgrade => v1.5.0
go: downloading github.com/astaxie/beego v1.12.2
go: downloading github.com/lib/pq v1.8.0
go: downloading github.com/sirupsen/logrus v1.7.0
go: downloading golang.org/x/sys v0.0.0-20201022201747-fb209a7c41cd
go: downloading golang.org/x/arch v0.0.0-20201008161808-52c3e6f60cff
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/pelletier/go-toml v1.8.1
go: downloading github.com/peterh/liner v1.2.0
go: downloading github.com/flosch/pongo2 v0.0.0-20200805083417-63c99409991d
go: downloading github.com/spf13/viper v1.7.1
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading go.starlark.net v0.0.0-20201014215153-dff0ae5b4820
go: downloading github.com/mattn/go-runewidth v0.0.3
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/spf13/afero v1.4.1
go: downloading github.com/magiconair/properties v1.8.4
go: downloading github.com/mitchellh/mapstructure v1.3.3
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/spf13/pflag v1.0.5
go: downloading gopkg.in/ini.v1 v1.62.0
go: downloading golang.org/x/text v0.3.3
go: github.com/mattn/go-runewidth upgrade => v0.0.9
go: downloading github.com/mattn/go-runewidth v0.0.9

**Comment by pppscn** [comment]
[root@microservice ~]# bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.11.0

├── Beego     : 1.12.2
├── GoVersion : go1.15.2
├── GOOS      : linux
├── GOARCH    : amd64
├── NumCPU    : 6
├── GOPATH    : /www/gopackage
├── GOROOT    : /usr/local/go
├── Compiler  : gc
└── Date      : Friday, 23 Oct 2020
