### ISSUE TITLE
bee tool install fail.

### ISSUE THREAD

**Issue by cyg0618** [beego/bee#728]
system WSL2 ubuntu18.04 

config : 

`go env `

![image](https://user-images.githubusercontent.com/38954059/97378914-7c3c0480-18fe-11eb-98ef-f92e2d610234.png)

`go get -v github.com/beego/bee  `

 
![image](https://user-images.githubusercontent.com/38954059/97379035-c45b2700-18fe-11eb-8602-8419dcd41e8b.png)

**Comment by flycash** [comment]
Could you try with `go get -u github.com/beego/bee`?

**Comment by killtheverse** [comment]
I have tried both 
`go get -u github.com/beego/bee` and
`go get github.com/beego/bee`.
But both of them are giving the same error.

**Comment by yvesjordan06** [comment]
Same errors!

**Comment by flycash** [comment]
The latest version is from "develop" branch and we use it to support develop-2.0. 
Could you try with "go get github.com/beego/bee@1.12.0"

**Comment by yvesjordan06** [comment]
> The latest version is from "develop" branch and we use it to support develop-2.0.
> Could you try with "go get github.com/beego/bee@1.12.0"

When  i try to run the command "go get github.com/beego/bee@1.12.0" I get the following error

go: cannot use path@version syntax in GOPATH mode

**Comment by bmcciscoding** [comment]
I have same problems. But I installed bee manually.

1 download bee from github
2 build bee project: go build main.go
3 move exec to /Users/xxxx/go/bin
4 add follow line to your .zshrc file (or bash_profile)
```
export GOPATH=/Users/xxxx/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
```
5 restart iterm

**Comment by NuVivo314** [comment]
@yvesjordan06 
```
export GO111MODULE=on
go get github.com/beego/bee@v1.12.0
```

Work on my install
