### ISSUE TITLE
panic: runtime error: index out of range [2] with length 0

### ISSUE THREAD

**Issue by 1920853199** [beego/bee#730]
leechen@leechen:/var/local/go-blog$ bee generate appcode -tables="customer" -driver="mysql" -conn="root:123456@tcp(127.0.0.1:3306)/blog" -level=3
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.11.0
2020/11/05 13:38:12 INFO     ▶ 0001 Using 'mysql' as 'SQLDriver'
2020/11/05 13:38:12 INFO     ▶ 0002 Using 'root:123456@tcp(127.0.0.1:3306)/blog' as 'SQLConn'
2020/11/05 13:38:12 INFO     ▶ 0003 Using 'customer' as 'Tables'
2020/11/05 13:38:12 INFO     ▶ 0004 Using '3' as 'Level'
2020/11/05 13:38:12 INFO     ▶ 0005 Analyzing database tables...
panic: runtime error: index out of range [2] with length 0

goroutine 1 [running]:
github.com/beego/bee/generate.extractIntSignness(0xc0002175a3, 0x3, 0xc000217598, 0x7)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/generate/g_appcode.go:930 +0xbf
github.com/beego/bee/generate.(*MysqlDB).GetColumns(0x13d7090, 0xc0002f7790, 0xc000218c60, 0xc0002af620)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/generate/g_appcode.go:481 +0xfb5
github.com/beego/bee/generate.getTableObjects(0xc0002dcb30, 0x1, 0x1, 0xc0002f7790, 0xf1bb00, 0x13d7090, 0x0, 0x1, 0x98)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/generate/g_appcode.go:363 +0x1de
github.com/beego/bee/generate.gen(0xc000217470, 0x5, 0xc0002b0270, 0x24, 0xc000289d07, 0xc000289ca8, 0xc00003a184, 0x12)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/generate/g_appcode.go:316 +0x2dc
github.com/beego/bee/generate.GenerateAppcode(0xc000217470, 0x5, 0xc0002b0270, 0x24, 0x134f9b8, 0x1, 0xc000217478, 0x8, 0xc00003a184, 0x12)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/generate/g_appcode.go:295 +0x212
github.com/beego/bee/cmd/commands/generate.appCode(0x1385240, 0xc000138020, 0x5, 0x5, 0xc00003a184, 0x12)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/cmd/commands/generate/generate.go:158 +0x693
github.com/beego/bee/cmd/commands/generate.GenerateCode(0x1385240, 0xc000138020, 0x5, 0x5, 0x0)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/cmd/commands/generate/generate.go:91 +0x285
main.main()
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/main.go:75 +0x2df

**Comment by 1920853199** [comment]
这个bug 有大佬看一下吗

**Comment by flycash** [comment]
可以提供一下customer的定义么？这样方便我复现和测试。

**Comment by 1920853199** [comment]
@flycash 
```
CREATE TABLE `customer` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `uid` varchar(50) NOT NULL COMMENT '用户ID',
  `username` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '用户名',
  `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '密码',
  `nickname` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '昵称',
  `image` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '头像',
  `url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '博客地址',
  `signature` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '个性签名',
  `email` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '邮箱',
  `phone` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '电话',
  `wishlist` int(11) DEFAULT '0' COMMENT '收藏',
  `review` int(11) DEFAULT '0' COMMENT '评论',
  `like` int(11) DEFAULT '0' COMMENT '点赞',
  `status` int(11) DEFAULT '1' COMMENT '1可用，2禁用，0删除',
  `created` datetime DEFAULT NULL COMMENT '创建时间',
  `updated` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
```
