### ISSUE TITLE
Bee install error: looking for folder core and folder server/web

### ISSUE THREAD

**Issue by JPedroGon** [beego/bee#732]
Hi,

After a vanilla installation of go and then beego (and respective GOROOT and GOPATH). When installed BEE I got the following errors:
`cannot find package "github.com/astaxie/beego/core/utils" in any of:
	/usr/local/opt/go/libexec/src/github.com/astaxie/beego/core/utils (from $GOROOT)
	/Users/pedro.goncalves/go/src/github.com/astaxie/beego/core/utils (from $GOPATH)
cannot find package "github.com/astaxie/beego/server/web/swagger" in any of:
	/usr/local/opt/go/libexec/src/github.com/astaxie/beego/server/web/swagger (from $GOROOT)
	/Users/pedro.goncalves/go/src/github.com/astaxie/beego/server/web/swagger (from $GOPATH)`

I looked into the Beego src (both the one in my gopath and in github) and Beego does not have any folder **CORE** or **SERVER**. I kind of patch it creating these folders and using ln -s to the root of the src folder since Utils and Swagger both exist in the root source folder (as it is as well in the Beego repo).

It seems to be a bug on the BEE instalment ?

**Comment by JuanCamiloMartinezLopez** [comment]
Hi,
sorry for my english
i had the same problem in windows 10, i create a environment variable GO111MODULE=on and after "go get github.com/beego/bee".
that´s work for me, hope this can help you.

**Comment by flycash** [comment]
Sorry, we release beego 2.0.0-beta. And we use beego 2.0 to rewrite the bee command. So if you are using beego 1.x, please run `go get github.com/beego/bee@1.12.0

**Comment by JPedroGon** [comment]
@JuanCamiloMartinezLopez  if you do that, when you execute code it will still fail on the libs above. Hence that bypass might work to install the bee as a module but will still fail at compile time on your code.

@flycash  understood that makes sense. Thank you!!
