### ISSUE TITLE
新手建议，显示相关版本号

### ISSUE THREAD

**Issue by zhangbest5** [beego/bee#738]
大神，作为新手经常懵逼，感觉自己好像不在最新版上
建议把小版本号也加上，
最好能获取到beego的版本（同样精确到小版本）

bee version
例如：
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.12.3【这里精确到小版本】

├── Beego     : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego
├── GoVersion : go1.15.3
├── Beego     :  v1.12.3【这里精确到小版本】
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : C:\Users\Administrator\go
├── GOROOT    : c:\go
├── Compiler  : gc
├── Built         : 【版本发布日期】
└── Date      : Thursday, 19 Nov 2020

**Comment by zhangbest5** [comment]
我去，蒙了，怎么我那beego 那没有？
 bee run 的时候也正常的
我安装了的呀？需要配置什么吗？请大神指点，谢谢

**Comment by flycash** [comment]
> 我去，蒙了，怎么我那beego 那没有？
> bee run 的时候也正常的
> 我安装了的呀？需要配置什么吗？请大神指点，谢谢

bee目前读取版本是从GOPATH/src/github.com/astaxie/beego/... 里面通过解析文件来读取的。在使用GOPATH的模式下，运作良好。但是目前在go mod大行其道的时候，很多人并不会在本地把beego源码下载下来，所以一般读不到版本信息。你可以确认一下你的GOPATH，应该是没有下载源码。

在go mod的时候，这种解析版本的机制就很蠢了。举个例子来说，我本地安装了很多个版本的beego，在GOPATH/pkg之下

![image](https://user-images.githubusercontent.com/9923838/99965294-a08ce300-2dcf-11eb-85a9-e537b0c995d0.png)

在z这种情况下，无法判断你在某一个项目中，究竟使用了beego哪个版本。

**Comment by zhangbest5** [comment]
感谢大神回复，理解了
建议增加
发布后能精确到小版本并增加build时间，
现在我的bee开机第一次运行时，总会告诉我，我的版本是1.12.0，最新的是1.12.3，但貌似我就是下载的最新的版本哈

**Comment by flycash** [comment]
这是一个好建议，我后面会在beego启动的时候让它输出自己的版本。不过，我记得在admin里面是可以看到的，只要你开启了beego的admin功能。
