### ISSUE TITLE
beev1.6.2 自动化文档问题

### ISSUE THREAD

**Issue by sudo-rm-maker** [beego/bee#739]
在models文件夹下, 有config.go和apms/config.go都定义了Config结构体。
```shell
models
  apms
    config.go ---> Config
  config.go ---> Cofnig
```
`bee run -gendoc=true`

API注释
```golang
// @Title UpdateConfig
// @Description update config for specified config type
// @Param   type  path string true "the type"
// @Param   body  body models.Config true "config detail"
// @Success 200 {string} update config success
```

概率性的正确显示， 多数情况下显示的是apms/config.go的Config结构。
bee版本是1.6.2。

**Comment by flycash** [comment]
所以，你的问题实际上是，在存在多个同名文件（不同类目）的时候，会出现问题？我有没有理解错？

**Comment by sudo-rm-maker** [comment]
@flycash 你好，感觉这个应该和文件名没关系，这两个文件里定义了同名的struct。不知道是不是版本太低的问题，或者bee有缓存。后来在一个新的环境尝试1.11的bee发现文档可以正常显示。估计后续升级bee可以解决。
