### ISSUE TITLE
bee run

### ISSUE THREAD

**Issue by lvzhenchao** [beego/bee#740]
bee run
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.12.0
2020/11/25 17:12:08 INFO     ▶ 0001 Using 'quickstart' as 'appname'
2020/11/25 17:12:08 INFO     ▶ 0002 Initializing watcher...
go: finding module for package github.com/astaxie/beego/adapter
controllers\default.go:4:2: module github.com/astaxie/beego@latest found (v1.12.3), but does not contain package github.com/astaxie/beego/adapter
2020/11/25 17:12:09 ERROR    ▶ 0003 Failed to build the application: go: finding module for package github.com/astaxie/beego/adapter
controllers\default.go:4:2: module github.com/astaxie/beego@latest found (v1.12.3), but does not contain package github.com/astaxie/beego/adapter

**Comment by lvzhenchao** [comment]
Why does it appear  "go: finding module for package github.com/astaxie/beego/adapter
controllers\default.go:4:2: module github.com/astaxie/beego@latest found (v1.12.3), but does not contain package"

**Comment by flycash** [comment]
`github.com/astaxie/beego/adapter` is v2.0 package. So v1.12.3 does not contain this package.

Please run `go get -u https://github.com/astaxie/beego@develop` to use v2.0.0-beta

**Comment by lvzhenchao** [comment]
$ bee version
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.12.0

├── Beego     : Beego is not installed. Please do consider installing it first: https://github.com/astaxie/beego
├── GoVersion : go1.15.5
├── GOOS      : windows
├── GOARCH    : amd64
├── NumCPU    : 8
├── GOPATH    : E:\GoPath
├── GOROOT    : E:\Go
├── Compiler  : gc
└── Date      : Thursday, 26 Nov 2020
![image](https://user-images.githubusercontent.com/22174614/100299248-28404080-2fce-11eb-97f3-0c0a8b9586e6.png)
![image](https://user-images.githubusercontent.com/22174614/100299347-6d647280-2fce-11eb-8c73-f116e81adafe.png)

虽然可以成功运行bee run了，但是项目里面显示引入包为红色
Although bee run can be run successfully, the imported package is displayed in red in the project
