### ISSUE TITLE
Cannot generate a project that has version 2 of beego

### ISSUE THREAD

**Issue by ISITWW** [beego/bee#748]
Hi, i am trying to use this command (bee new beego) to generate a new beego project , but what gets installed is the older version 1, so what can i do with this ? 

Thanks for help and support

**Comment by flycash** [comment]
please upgrade your bee command:
go get -u -f github.com/beego/bee

**Comment by ISITWW** [comment]
This is what i get 

go: downloading github.com/beego/bee v1.12.3
go: github.com/beego/bee upgrade => v1.12.3
go: downloading github.com/astaxie/beego v1.12.1
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/smartwalle/pongo2render v1.0.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/pelletier/go-toml v1.2.0
go: downloading github.com/lib/pq v1.7.0
go: downloading github.com/flosch/pongo2 v0.0.0-20200529170236-5abacdfa4915
go: downloading github.com/spf13/viper v1.7.0
go: downloading github.com/gadelkareem/delve v1.4.2-0.20200619175259-dcd01330766f
go: downloading golang.org/x/sys v0.0.0-20191005200804-aed5e4c7ecf9
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading gopkg.in/ini.v1 v1.51.0
go: downloading github.com/spf13/jwalterweatherman v1.0.0
go: downloading github.com/spf13/afero v1.1.2
go: downloading github.com/spf13/pflag v1.0.3
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/spf13/cast v1.3.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/cosiner/argv v0.1.0
go: downloading github.com/mattn/go-colorable v0.0.9
go: downloading go.starlark.net v0.0.0-20190702223751-32f345186213
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/peterh/liner v0.0.0-20170317030525-88609521dc4b
go: downloading github.com/mattn/go-isatty v0.0.3
go: downloading golang.org/x/arch v0.0.0-20190927153633-4e8777c89be4
go: downloading github.com/sirupsen/logrus v1.6.0
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.3

**Comment by ISITWW** [comment]
I tried this command also 

go get -u -v -f github.com/beego/bee

and this is the result:

go get: -f flag is a no-op when using modules
go: github.com/beego/bee upgrade => v1.12.3
go: github.com/astaxie/beego upgrade => v1.12.3
go: github.com/lib/pq upgrade => v1.9.0
go: github.com/mattn/go-colorable upgrade => v0.1.8
go: github.com/pelletier/go-toml upgrade => v1.8.1
go: golang.org/x/text upgrade => v0.3.4
go: gopkg.in/yaml.v2 upgrade => v2.4.0
go: github.com/flosch/pongo2 upgrade => v0.0.0-20200913210552-0d938eb266f3
go: github.com/spf13/pflag upgrade => v1.0.5
go: github.com/spf13/afero upgrade => v1.5.1
go: github.com/spf13/viper upgrade => v1.7.1
go: go.starlark.net upgrade => v0.0.0-20201210151846-e81fc95f7bd5
go: github.com/peterh/liner upgrade => v1.2.1
go: gopkg.in/ini.v1 upgrade => v1.62.0
go: github.com/spf13/cast upgrade => v1.3.1
go: github.com/davecgh/go-spew upgrade => v1.1.1
go: github.com/hashicorp/golang-lru upgrade => v0.5.4
go: github.com/mitchellh/mapstructure upgrade => v1.4.0
go: github.com/go-sql-driver/mysql upgrade => v1.5.0
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: golang.org/x/sys upgrade => v0.0.0-20201214210602-f9fddec55a1e
go: github.com/fsnotify/fsnotify upgrade => v1.4.9
go: github.com/magiconair/properties upgrade => v1.8.4
go: github.com/spf13/jwalterweatherman upgrade => v1.1.0
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
go: github.com/sirupsen/logrus upgrade => v1.7.0
go: golang.org/x/arch upgrade => v0.0.0-20201207233722-1e68675e650f
go: github.com/mattn/go-runewidth upgrade => v0.0.9

**Comment by ISITWW** [comment]
It always downloads version 1.12.3

**Comment by flycash** [comment]
Try this：
go get -u github.com/beego/bee@master

**Comment by ISITWW** [comment]
I deleted the whole GOPATH folder and did as you wrote and i got this 

go: github.com/beego/bee master => v1.12.0
go: github.com/mitchellh/mapstructure upgrade => v1.4.0
go: github.com/lib/pq upgrade => v1.9.0
go: github.com/davecgh/go-spew upgrade => v1.1.1
go: github.com/spf13/jwalterweatherman upgrade => v1.1.0
go: gopkg.in/yaml.v2 upgrade => v2.4.0
go: github.com/flosch/pongo2 upgrade => v0.0.0-20200913210552-0d938eb266f3
go: github.com/hashicorp/golang-lru upgrade => v0.5.4
go: github.com/sirupsen/logrus upgrade => v1.7.0
go: golang.org/x/text upgrade => v0.3.4
go: golang.org/x/sys upgrade => v0.0.0-20201214210602-f9fddec55a1e
go: golang.org/x/arch upgrade => v0.0.0-20201207233722-1e68675e650f
go: github.com/spf13/pflag upgrade => v1.0.5
go: github.com/spf13/viper upgrade => v1.7.1
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/spf13/afero upgrade => v1.5.1
go: github.com/peterh/liner upgrade => v1.2.1
go: gopkg.in/ini.v1 upgrade => v1.62.0
go: github.com/mattn/go-colorable upgrade => v0.1.8
go: github.com/astaxie/beego upgrade => v1.12.3
go: github.com/konsorten/go-windows-terminal-sequences upgrade => v1.0.3
go: github.com/pelletier/go-toml upgrade => v1.8.1
go: github.com/go-sql-driver/mysql upgrade => v1.5.0
go: github.com/spf13/cast upgrade => v1.3.1
go: go.starlark.net upgrade => v0.0.0-20201210151846-e81fc95f7bd5
go: github.com/fsnotify/fsnotify upgrade => v1.4.9
go: github.com/magiconair/properties upgrade => v1.8.4
go: github.com/mattn/go-runewidth upgrade => v0.0.9


Here its saying 

go: github.com/astaxie/beego upgrade => v1.12.3

The new beego repo is in beego/beego not in astaxie/beego , so still the problem wasnt solved

**Comment by ISITWW** [comment]
I made a new project and this is the cat of the go.mod file

module beego

go 1.15

require github.com/astaxie/beego v1.12.3

require (
	github.com/beego/bee v1.12.0 // indirect
	github.com/flosch/pongo2 v0.0.0-20200913210552-0d938eb266f3 // indirect
	github.com/lib/pq v1.9.0 // indirect
	github.com/magiconair/properties v1.8.4 // indirect
	github.com/mattn/go-colorable v0.1.8 // indirect
	github.com/mattn/go-runewidth v0.0.9 // indirect
	github.com/mitchellh/mapstructure v1.4.0 // indirect
	github.com/pelletier/go-toml v1.8.1 // indirect
	github.com/peterh/liner v1.2.1 // indirect
	github.com/sirupsen/logrus v1.7.0 // indirect
	github.com/smartystreets/goconvey v1.6.4
	github.com/spf13/afero v1.5.1 // indirect
	github.com/spf13/cast v1.3.1 // indirect
	github.com/spf13/jwalterweatherman v1.1.0 // indirect
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/spf13/viper v1.7.1 // indirect
	go.starlark.net v0.0.0-20201210151846-e81fc95f7bd5 // indirect
	golang.org/x/arch v0.0.0-20201207233722-1e68675e650f // indirect
	golang.org/x/sys v0.0.0-20201214210602-f9fddec55a1e // indirect
	golang.org/x/text v0.3.4 // indirect
	gopkg.in/ini.v1 v1.62.0 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
)

**Comment by ISITWW** [comment]
I solved it using:

go get -v -u github.com/beego/bee@develop

I tried making a new project and it worked , the latest version is installed , but is the develop safe ??

**Comment by flycash** [comment]
Now you can use `go get github.com/beego/bee/v2@latest`.

We fix module name and then you can use stable version.

**Comment by ISITWW** [comment]
Thank you for help and support, note also that when i used `bee update` , it downgraded the current version

**Comment by flycash** [comment]
`bee update` running `go get -u github.com/beego/bee/v2`. I think I need to change it to `go get -u github.com/beego/bee/v2@latest` next version.
