### ISSUE TITLE
默认生成的test/default_test.go文件 第29行出现没有实现的代码

### ISSUE THREAD

**Issue by liuyongchen** [beego/bee#766]
import 路径：beego "github.com/beego/beego/v2/server/web"

代码原文：beego.Trace("testing", "TestBeego", "Code[%d]\n%s", w.Code, w.Body.String())

beego版本：github.com/beego/beego/v2 v2.0.1

**Comment by flycash** [comment]
这个已经被修复了。你可以切到bee master分支。
或者自己修改为 logs.Trace
其中`logs`是beego下面的core 里面的包。
