### ISSUE TITLE
 "go get github.com/beego/bee“ install error

### ISSUE THREAD

**Issue by wangfly80** [beego/bee#771]
when i ran  "go get github.com/beego/bee“ ,error:
main.go:21:2: cannot find package "github.com/beego/bee/v2/cmd" in any of:
	/usr/lib/go-1.6/src/github.com/beego/bee/v2/cmd (from $GOROOT)
	$HOME/go/src/github.com/beego/bee/v2/cmd (from $GOPATH)
main.go:22:2: cannot find package "github.com/beego/bee/v2/cmd/commands" in any of:
	/usr/lib/go-1.6/src/github.com/beego/bee/v2/cmd/commands (from $GOROOT)
	$HOME/go/src/github.com/beego/bee/v2/cmd/commands (from $GOPATH)
main.go:23:2: cannot find package "github.com/beego/bee/v2/config" in any of:
	/usr/lib/go-1.6/src/github.com/beego/bee/v2/config (from $GOROOT)
	$HOME/go/src/github.com/beego/bee/v2/config (from $GOPATH)
main.go:24:2: cannot find package "github.com/beego/bee/v2/utils" in any of:
	/usr/lib/go-1.6/src/github.com/beego/bee/v2/utils (from $GOROOT)
	$HOME/go/src/github.com/beego/bee/v2/utils (from $GOPATH)

**Comment by flycash** [comment]
run 
```go
go get github.com/beego/bee/v2@latest
```

**Comment by alivardar** [comment]
GO111MODULE=on go get github.com/beego/bee

solved my problem

**Comment by flycash** [comment]
> GO111MODULE=on go get github.com/beego/bee
> 
> solved my problem

Yes, now we are using GO mod.
