### ISSUE TITLE
用bee创建的初始项目，生产的测试文件有问题

### ISSUE THREAD

**Issue by overstarry** [beego/bee#773]
![image](https://user-images.githubusercontent.com/23260162/116178117-8fae1800-a747-11eb-982e-ee299916ad3e.png)
![image](https://user-images.githubusercontent.com/23260162/116178167-a48aab80-a747-11eb-8863-1eb6118a684b.png)
bee versioon 2.02

**Comment by overstarry** [comment]
bee api的是正常
bee new 是错误

**Comment by flycash** [comment]
已经修复了这个问题。需要更新到`develop`，感谢反馈！
