### ISSUE TITLE
cant find bee tool in "GOPATH/bin", when I installed the beego and bee following your steps

### ISSUE THREAD

**Issue by Beaelf** [beego/bee#776]

**Comment by overstarry** [comment]
GOPATH/bin Add to environment variables

**Comment by flycash** [comment]
What did you mean? Did you find the file under `GOPATH/bin`?
Please check two things:
1. you are using `go mod`
2. after running install command, you found the file under `GOPATH/bin`
3. check you `PATH` and make sure that it contains `GOPATH/bin` directory

**Comment by Beaelf** [comment]
thank you, I have solved this problem
