### ISSUE TITLE
使用swagger时的错误

### ISSUE THREAD

**Issue by meilihao** [beego/bee#78]
bee:1.2.2
beego:1.4.1
go:1.3.3 windows/amd64

问题1:
参考:http://my.oschina.net/astaxie/blog/284072

运行"bee run -gendoc=true -downdoc=true"后,swagger下载正常,控制台也提示了"Start delete src file swagger.zip",发现swagger.zip已解压但并没有删除.而且访问http://127.0.0.1:8080/swagger/swagger-1/,提示"Forbidden(403页)".

问题2:
参考:http://beego.me/docs/advantage/docs.md

按照docs.md尝试生成文档时,发现bee中没有"bee rundocs"命令

**Comment by sergeylanzman** [comment]
Please check again. bee generate docs rewrite with swagger 2.0. If this still relevant, please reopen issue
