### ISSUE TITLE
Can't get beego version

### ISSUE THREAD

**Issue by tianwen01** [beego/bee#793]
After executing the bee version command，Beego version display as:

Beego is not installed. Please do consider installing it first: https://github.com/beego/beego/v2. If you are using go mod, and you don't install the beego under $GOPATH/src/github.com/astaxie, just ignore this.

![image](https://user-images.githubusercontent.com/39637414/124232431-3b0e8b00-db44-11eb-8632-19c9f64d31be.png)

**Comment by flycash** [comment]
Yes, we will remove this feature because using go mod, you could read your go mod file. It's hard for us to do this because `GOPATH/mod` may have several `Beego`
![image](https://user-images.githubusercontent.com/9923838/124357172-b3607380-dc4c-11eb-81d4-3cbecb03223f.png)
