### ISSUE TITLE
 can't evaluate field BeegoVersion in type version.RuntimeInfo

### ISSUE THREAD

**Issue by maxproc** [beego/bee#823]
beego version v2.0.3
i want to upgrade bee version from v2.0.2 to v2.0.3
after  `bee update`,i execute `bee version`,it occurs error as below,but I can use bee normally.
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v2.0.2

├── Beego     : 2022/06/01 11:14:50 ERROR    ▶ 0001 template: banner:8:25: executing "banner" at <.BeegoVersion>: can't evaluate field BeegoVersion in type version.RuntimeInfo

**Comment by x827506590** [comment]
你好，这个解决了吗，我也遇到了，只要打bee命令就必然报这个错误

**Comment by maxproc** [comment]
> 你好，这个解决了吗，我也遇到了，只要打bee命令就必然报这个错误

# go 1.16 以前的版本
go get -u github.com/beego/bee/v2

# go 1.16及以后的版本
go install github.com/beego/bee/v2@latest

**Comment by flycash** [comment]
v2.0.4 可以试试
