### ISSUE TITLE
Default 'bee api' returns 404

### ISSUE THREAD

**Issue by reavessm** [beego/bee#828]
Running 'bee api foo' creates a project, but 'bee run' returns 404 no matter what endpoint you hit.

bee version: 1.12.0
go version: 1.16.15

![Screenshot from 2022-06-15 11-44-41](https://user-images.githubusercontent.com/23387932/173871136-45fa0d20-f7d0-4c21-a843-8d655e2990c9.png)

I wonder if it has something to do with the router.go file being different than the 'bee new' command.

https://github.com/beego/bee/blob/develop/cmd/commands/api/apiapp.go#L124-L154

vs

https://github.com/beego/bee/blob/develop/cmd/commands/new/new.go#L81-L91

**Comment by reavessm** [comment]
I tried this on a different system with a different version of go and it worked.  Must be a setup error then...

**Comment by OtezVikentiy** [comment]
@reavessm could you please tell on which versions it works? have same issue on go version 1.23 and beego 1.12
