### ISSUE TITLE
升级、版本号、v1和v2共存问题

### ISSUE THREAD

**Issue by zhangbest5** [beego/bee#842]
1、之前安装过bee v1.12，怎么卸载？
我是把%GOPATH%/bin下的bee.exe改名后，才能使用v2的bee
2、现在bee version 显示v2.0.2，是您忘记改版本号了？还是我没整对？(现在最新版不是v2.0.4么)
3、bee v1怎么与 v2共存？

还请大神指点，谢谢

**Comment by flycash** [comment]
目前的话暂时没啥好的方法。你可以考虑安装1.12 之后重命名为 bee1，然后再安装 bee 2.0.x。那么你就使用 bee1 来用 bee 1.12.x，用 bee 来执行 bee 2.0.x

**Comment by zhangbest5** [comment]
个人处理思路，希望能帮助别人，我这也小白水平，概不负责啊
1、通过 `cmd` 使用 `where bee` 查看获得 `bee` 的实际路径，就是死活升级不上去的那个v2.0.2
2、不知道什么时候，我的环境变量（用户环境变量）`path` 里有了个 `%USERPROFILE%\go\bin` （实际路径就是 C:\Users\Administrator\go\bin）
3、反正没几个项目，我把 `path` 里的 `%USERPROFILE%\go\bin`  删了，这个 C:\Users\Administrator\go目录也删了（不知道有什么影响）
4、进入 `GoPath` 下的 `pkg\mod\github.com\beego\bee` 找到 `v2@v2.0.4`
执行 `go build -o bee.exe main.go`  把生成的 bee.exe 挪到 `GoPath` 下的 `bin`  目录下，世界核平~

**Comment by zhangbest5** [comment]
后记：
重启，执行
`go get -u github.com/beego/bee/v2`
`go get -u github.com/beego/beego/v2@latest`

bee new xxx
bee run
go mod tidy
bee run
世界终于核平了
