### ISSUE TITLE
bee v2 install fail

### ISSUE THREAD

**Issue by mox1206** [beego/bee#855]
Golang version: go1.20.5 windows/amd64
Beego version: 2.1.0
error: 
# github.com/go-delve/delve/service/dap
..\..\pkg\mod\github.com\go-delve\delve@v1.20.2\service\dap\server.go:1972:24: cannot use dap.Source{…} (value of type "github.com/google/go-dap".Source) as *"github.com/google/go-dap".Source value in assignment
..\..\pkg\mod\github.com\go-delve\delve@v1.20.2\service\dap\server.go:3057:31: cannot use dap.Source{…} (value of type "github.com/google/go-dap".Source) as *"github.com/google/go-dap".Source value in assignment
..\..\pkg\mod\github.com\go-delve\delve@v1.20.2\service\dap\server.go:3679:13: cannot use dap.Source{…} (value of type "github.com/google/go-dap".Source) as *"github.com/google/go-dap".Source value in struct literal

**Comment by flycash** [comment]
I think this is the version conflict of `github.com/go-delve/delve`,  and I check Beego, it dose not rely on this module.

**Comment by flycash** [comment]
why did you keep using v1.x bee?

**Comment by flycash** [comment]
can you keep using the v1.5.0? only for the bee.

**Comment by flycash** [comment]
I will upgrade it this weekend or next week.

**Comment by flycash** [comment]
you can try bee@develop branch and if you got any problem, you can reopen this issue. Or I will release a new version next week.
