### ISSUE TITLE
Bee test command not found

### ISSUE THREAD

**Issue by patrickandroid** [beego/bee#92]
The "bee test" command is listed in the docs: http://beego.me/docs/install/bee.md#command-test
But it is not available when testing with the latest version of bee:

MacBook-Air-8:app $ bee version
bee   :1.2.3
beego :1.4.2
Go    :go version go1.3.3 darwin/amd64

MacBook-Air-8:app $ bee test
bee: unknown subcommand "test"
Run 'bee help' for usage.

MacBook-Air-8:app $ bee help
Bee is a tool for managing beego framework.

Usage:

```
bee command [arguments]
```

The commands are:

```
new         Create a Beego application
run         run the app and start a Web server for development
pack        Compress a beego project into a single file
api         create an API beego application
bale        packs non-Go files to Go source files
version     show the Bee, Beego and Go version
generate    source code generator
migrate     run database migrations
```

Use "bee help [command]" for more information about a command.

Additional help topics:

Use "bee help [topic]" for more information about that topic.

**Comment by Gr1N** [comment]
Up! While no `test` command can you advise a way to run the tests?

**Comment by xtea** [comment]
Test is really essential tool for development , hope to see it asap

**Comment by sergeylanzman** [comment]
You can create this command with bee rs. From 1.8.1 bee support custom command. Set in Beefile your test command.

**Comment by gnanakeethan** [comment]
@sergeylanzman  Can you suggest a way to create a custom command for generating test file?
