### ISSUE TITLE
API Swagger Annotation with different request / response models

### ISSUE THREAD

**Issue by initzero** [beego/bee#94]
I'm experiencing an issue with the generated Swagger docs when my controller is annotated to return a different object type than the request body type.

Consider (when @Param and @Success objects are both NewUserRequest):

``` go
// @Title Test
// @Description Test
// @Param body body models.users.NewUserRequest true "User"
// @Success 200 {object} models.users.NewUserRequest
// @Failure 400 auth
// @router /test [post]
func (this *PublicServicesController) Test() {

}
```

Swagger UI looks like:

![swagger_1](https://cloud.githubusercontent.com/assets/1383268/5696778/35d36cd8-99aa-11e4-869b-a25fd41d0c69.png)

Now, if I change the @Success object to NewUserResponse model:

``` go
// @Title Test
// @Description Test
// @Param body body models.users.NewUserRequest true "User"
// @Success 200 {object} models.users.NewUserResponse
// @Failure 400 auth
// @router /test [post]
func (this *PublicServicesController) Test() {

}
```

I get a broken request data type model in Swagger UI:

![swagger_2](https://cloud.githubusercontent.com/assets/1383268/5696784/84d66d12-99aa-11e4-8b88-ee2bac9b0145.png)

Am I using this incorrectly or is this unexpected behavior?

**Comment by patrickbanks** [comment]
It looks like the method parserComments in the file github.com/beego/bee/g_docs.go is not appending any models found in the @Param line.

A quick (dirty) fix could be something like this (adding to the end of the the "@Param" section of the if else statement ("} else if strings.HasPrefix(t, "@Param") {"):

```golang
if !((para.DataType == "string") || (para.DataType == "int") || (para.DataType == "int64"))  {
	cmpath, m, mod, realTypes := getModel(p[2])
	para.DataType = m
	if _, ok := modelsList[pkgpath+controllerName]; !ok {
		modelsList[pkgpath+controllerName] = make(map[string]swagger.Model, 0)
	}
	modelsList[pkgpath+controllerName][p[2]] = mod
	appendModels(cmpath, pkgpath, controllerName, realTypes)
}
```

The code is from the same file, in the @Success if else statement.

**Comment by sergeylanzman** [comment]
Please check again. bee generate docs rewrite with swagger 2.0. If this still relevant, please reopen issue
