### ISSUE TITLE
Best practice with bower_components

### ISSUE THREAD

**Issue by digitalcraftsman** [beego/bee#97]
I use Bower to use my dependencies in my beego app. The ```/static``` directory already contains a structure for imgs, css etc. Bower stores usually the files of each dependencie e.g. Bootstrap 3 in ```/bower_components ```, but this behavior would break the default folder structure of beego?

Has anyone a good idea to combine both?

**Comment by ws6** [comment]
use multiple static folder?
beego.StaticDir["/bower_install"] = "bower_components"
beego.StaticDir["/my_public_html"] = "public"

**Comment by digitalcraftsman** [comment]
Thanks for this approach in beego. Since I tried gulp.js for automatisation-purposes I will move the necessary file from the `bower_components` folder into  one named `public`. 

This allows me to ignore the `bower_components` for commits with the `.gitignore` file.
Thanks anywaay ;)
