### ISSUE TITLE
bee new，如果目录存在，会直接退出

### ISSUE THREAD

**Issue by cst05001** [beego/bee#99]
bee new，如果目录存在，会直接退出。

我觉得如果加一个参数 -f ，如果目录存在，继续执行。会比较好。

场景：我从 github clone  一个新项目下来。已经存在目录了，我想在这个目录下 bee new 做初始化。

**Comment by ws6** [comment]
up

**Comment by ws6** [comment]
You can modify the beego code yourself. Just like what I did in here https://github.com/ws6/bee/blob/master/g_appcode.go#L740
and by pass lane 739 
 if askForConfirmation() {
Becareful, all the newly generated files will overwrite and keep your custom changes into separate files for non-clashing
